
make file generated by Autoconfig: dont edit

# build definitions
config = debug
compiler = gcc
system = linux
target_type = qt_plugin

# include general build instructions
include $(SHACIRADIR)/Targ/platforms/linux_gcc.defs

# include dependencies
-include linux_gcc_debug.dep

A_I_PATHS = \
	-I../../../Src/GUIFramework/QTFramework \
	-I../../../Src/GUIFramework/QTFramework/Keypads \
	-Ilinux_gcc_debug \
	-I/prj/qt3/include \
	-I/prj/qt3/makespecs/default
A_GEN_HEADERS = \
	linux_gcc_debug/qt_keyboard_layout_german.h \
	linux_gcc_debug/qt_keyboard_layout_standard.h

A_L_PATHS = \
	-L"/prj/qt3/lib"
A_LIBS = \
	-lqt-mt
A_OBJECTS = \
	linux_gcc_debug/moc_qt_keyboard.o \
	linux_gcc_debug/moc_qt_keyboard_button.o \
	linux_gcc_debug/moc_qt_keyboard_layout.o \
	linux_gcc_debug/moc_qt_keyboard_layout_german.o \
	linux_gcc_debug/moc_qt_keyboard_layout_standard.o \
	linux_gcc_debug/qt_keyboard.o \
	linux_gcc_debug/qt_keyboard_button.o \
	linux_gcc_debug/qt_keyboard_layout.o \
	linux_gcc_debug/qt_keyboard_layout_german.o \
	linux_gcc_debug/qt_keyboard_layout_standard.o \
	linux_gcc_debug/qt_plugin.o \
	linux_gcc_debug/qt_plugin_register.o
A_TARGETS = \
	linux_gcc_debug/qt_keyboard_layout_german.h \
	linux_gcc_debug/qt_keyboard_layout_standard.h \
	linux_gcc_debug/moc_qt_keyboard.cpp \
	linux_gcc_debug/moc_qt_keyboard_button.cpp \
	linux_gcc_debug/moc_qt_keyboard_layout.cpp \
	linux_gcc_debug/moc_qt_keyboard_layout_german.cpp \
	linux_gcc_debug/moc_qt_keyboard_layout_standard.cpp \
	linux_gcc_debug/qt_keyboard_layout_german.cpp \
	linux_gcc_debug/qt_keyboard_layout_standard.cpp \
	linux_gcc_debug/moc_qt_keyboard.o \
	linux_gcc_debug/moc_qt_keyboard_button.o \
	linux_gcc_debug/moc_qt_keyboard_layout.o \
	linux_gcc_debug/moc_qt_keyboard_layout_german.o \
	linux_gcc_debug/moc_qt_keyboard_layout_standard.o \
	linux_gcc_debug/qt_keyboard.o \
	linux_gcc_debug/qt_keyboard_button.o \
	linux_gcc_debug/qt_keyboard_layout.o \
	linux_gcc_debug/qt_keyboard_layout_german.o \
	linux_gcc_debug/qt_keyboard_layout_standard.o \
	linux_gcc_debug/qt_plugin.o \
	linux_gcc_debug/qt_plugin_register.o

.PHONY: linux_gcc_debug all clean


dependencies:

clean:
	-rm $(A_TARGETS)

linux_gcc_debug/libKeyboardLayouts.so: $(A_TARGETS)
	$(share)

$(QTDIR)/plugins/designer/libKeyboardLayouts.so: linux_gcc_debug/libKeyboardLayouts.so
	$(cp) $< $@

all: dependencies linux_gcc_debug $(A_TARGETS) $(QTDIR)/plugins/designer/libKeyboardLayouts.so

linux_gcc_debug: linux_gcc_debug.mk
	$(mkdir) $@

linux_gcc_debug/moc_qt_keyboard_layout_german.o: linux_gcc_debug/moc_qt_keyboard_layout_german.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_standard.o: linux_gcc_debug/moc_qt_keyboard_layout_standard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard.o: linux_gcc_debug/moc_qt_keyboard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_button.o: linux_gcc_debug/moc_qt_keyboard_button.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout.o: linux_gcc_debug/moc_qt_keyboard_layout.cpp
	$(cpp)

linux_gcc_debug/qt_keyboard_layout_german.o: linux_gcc_debug/qt_keyboard_layout_german.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_german.cpp: linux_gcc_debug/qt_keyboard_layout_german.h
	$(QTDIR)/bin/moc linux_gcc_debug/qt_keyboard_layout_german.h -olinux_gcc_debug/moc_qt_keyboard_layout_german.cpp

linux_gcc_debug/qt_keyboard_layout_standard.o: linux_gcc_debug/qt_keyboard_layout_standard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_standard.cpp: linux_gcc_debug/qt_keyboard_layout_standard.h
	$(QTDIR)/bin/moc linux_gcc_debug/qt_keyboard_layout_standard.h -olinux_gcc_debug/moc_qt_keyboard_layout_standard.cpp

linux_gcc_debug/qt_keyboard.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard.h -olinux_gcc_debug/moc_qt_keyboard.cpp

linux_gcc_debug/qt_keyboard_button.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_button.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_button.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_button.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_button.h -olinux_gcc_debug/moc_qt_keyboard_button.cpp

linux_gcc_debug/qt_keyboard_layout.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout.h -olinux_gcc_debug/moc_qt_keyboard_layout.cpp

linux_gcc_debug/qt_keyboard_layout_german.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -o linux_gcc_debug/qt_keyboard_layout_german.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -i linux_gcc_debug/qt_keyboard_layout_german.h -o linux_gcc_debug/qt_keyboard_layout_german.cpp
linux_gcc_debug/qt_keyboard_layout_german.h: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -o linux_gcc_debug/qt_keyboard_layout_german.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -i linux_gcc_debug/qt_keyboard_layout_german.h -o linux_gcc_debug/qt_keyboard_layout_german.cpp

linux_gcc_debug/qt_keyboard_layout_standard.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -o linux_gcc_debug/qt_keyboard_layout_standard.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -i linux_gcc_debug/qt_keyboard_layout_standard.h -o linux_gcc_debug/qt_keyboard_layout_standard.cpp
linux_gcc_debug/qt_keyboard_layout_standard.h: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -o linux_gcc_debug/qt_keyboard_layout_standard.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -i linux_gcc_debug/qt_keyboard_layout_standard.h -o linux_gcc_debug/qt_keyboard_layout_standard.cpp

linux_gcc_debug/qt_plugin.o: ../../../Src/GUIFramework/QTFramework/Keypads/Plugin/qt_plugin.cpp
	$(cpp)

linux_gcc_debug/qt_plugin_register.o: ../../../Src/GUIFramework/QTFramework/Keypads/Plugin/qt_plugin_register.cpp
	$(cpp)

