/*.SI.***********************************************************************/
#ifndef _syntax
#include <syntax.h>
#define _syntax
#endif
#ifndef _platform
#include <platform.h>
#define _platform
#endif
#ifndef _basicio
#include <basicio.h>
#define _basicio
#endif
/*.EI.***********************************************************************/

#ifndef __dmpio__
#define __dmpio__

GLOBAL const IO_MODULE * DMP_Module();

#endif   /* dmpio */

