
make file generated by Autoconfig: dont edit

# build definitions
config = debug
compiler = gcc
system = linux
target_type = static_library

# include general build instructions
include $(SHACIRADIR)/Targ/platforms/linux_gcc.defs

# include dependencies
-include linux_gcc_debug.dep

A_I_PATHS = \
	-I../../../Extern/ECL/src
A_GEN_HEADERS =

A_L_PATHS = \
	-L"linux_gcc_debug"
A_LIBS = \
	-lecl
A_OBJECTS = \
	linux_gcc_debug/base.o \
	linux_gcc_debug/bprintf.o \
	linux_gcc_debug/collect.o \
	linux_gcc_debug/enum_procs.o \
	linux_gcc_debug/error.o \
	linux_gcc_debug/event.o \
	linux_gcc_debug/list.o \
	linux_gcc_debug/logfile.o \
	linux_gcc_debug/map.o \
	linux_gcc_debug/message.o \
	linux_gcc_debug/mn.o \
	linux_gcc_debug/mn_local.o \
	linux_gcc_debug/mn_mslot.o \
	linux_gcc_debug/mn_npipe.o \
	linux_gcc_debug/mn_queue.o \
	linux_gcc_debug/namedpipe.o \
	linux_gcc_debug/object.o \
	linux_gcc_debug/osbase.o \
	linux_gcc_debug/osversion.o \
	linux_gcc_debug/process.o \
	linux_gcc_debug/profile.o \
	linux_gcc_debug/queue.o \
	linux_gcc_debug/ring.o \
	linux_gcc_debug/semaphore.o \
	linux_gcc_debug/sharedmem.o \
	linux_gcc_debug/string.o \
	linux_gcc_debug/string_ex.o \
	linux_gcc_debug/thread.o
A_TARGETS = \
	linux_gcc_debug/base.o \
	linux_gcc_debug/bprintf.o \
	linux_gcc_debug/collect.o \
	linux_gcc_debug/enum_procs.o \
	linux_gcc_debug/error.o \
	linux_gcc_debug/event.o \
	linux_gcc_debug/list.o \
	linux_gcc_debug/logfile.o \
	linux_gcc_debug/map.o \
	linux_gcc_debug/message.o \
	linux_gcc_debug/mn.o \
	linux_gcc_debug/mn_local.o \
	linux_gcc_debug/mn_mslot.o \
	linux_gcc_debug/mn_npipe.o \
	linux_gcc_debug/mn_queue.o \
	linux_gcc_debug/namedpipe.o \
	linux_gcc_debug/object.o \
	linux_gcc_debug/osbase.o \
	linux_gcc_debug/osversion.o \
	linux_gcc_debug/process.o \
	linux_gcc_debug/profile.o \
	linux_gcc_debug/queue.o \
	linux_gcc_debug/ring.o \
	linux_gcc_debug/semaphore.o \
	linux_gcc_debug/sharedmem.o \
	linux_gcc_debug/string.o \
	linux_gcc_debug/string_ex.o \
	linux_gcc_debug/thread.o

.PHONY: linux_gcc_debug all clean


dependencies:

clean:
	-rm $(A_TARGETS)

linux_gcc_debug/libecl.a: $(A_TARGETS)
	$(lib)

all: dependencies linux_gcc_debug $(A_TARGETS) linux_gcc_debug/libecl.a

linux_gcc_debug: linux_gcc_debug.mk
	$(mkdir) $@

linux_gcc_debug/base.o: ../../../Extern/ECL/src/base/base.cpp
	$(cpp)

linux_gcc_debug/bprintf.o: ../../../Extern/ECL/src/base/bprintf.cpp
	$(cpp)

linux_gcc_debug/collect.o: ../../../Extern/ECL/src/base/collect.cpp
	$(cpp)

linux_gcc_debug/enum_procs.o: ../../../Extern/ECL/src/base/system/enum_procs.cpp
	$(cpp)

linux_gcc_debug/error.o: ../../../Extern/ECL/src/base/error.cpp
	$(cpp)

linux_gcc_debug/event.o: ../../../Extern/ECL/src/base/event.cpp
	$(cpp)

linux_gcc_debug/list.o: ../../../Extern/ECL/src/base/list.cpp
	$(cpp)

linux_gcc_debug/logfile.o: ../../../Extern/ECL/src/base/logfile.cpp
	$(cpp)

linux_gcc_debug/map.o: ../../../Extern/ECL/src/base/map.cpp
	$(cpp)

linux_gcc_debug/message.o: ../../../Extern/ECL/src/base/message.cpp
	$(cpp)

linux_gcc_debug/mn.o: ../../../Extern/ECL/src/base/driver/mn.cpp
	$(cpp)

linux_gcc_debug/mn_local.o: ../../../Extern/ECL/src/base/driver/mn_local.cpp
	$(cpp)

linux_gcc_debug/mn_mslot.o: ../../../Extern/ECL/src/base/driver/mn_mslot.cpp
	$(cpp)

linux_gcc_debug/mn_npipe.o: ../../../Extern/ECL/src/base/driver/mn_npipe.cpp
	$(cpp)

linux_gcc_debug/mn_queue.o: ../../../Extern/ECL/src/base/driver/mn_queue.cpp
	$(cpp)

linux_gcc_debug/namedpipe.o: ../../../Extern/ECL/src/base/namedpipe.cpp
	$(cpp)

linux_gcc_debug/object.o: ../../../Extern/ECL/src/base/object.cpp
	$(cpp)

linux_gcc_debug/osbase.o: ../../../Extern/ECL/src/base/osbase.cpp
	$(cpp)

linux_gcc_debug/osversion.o: ../../../Extern/ECL/src/base/osversion.cpp
	$(cpp)

linux_gcc_debug/process.o: ../../../Extern/ECL/src/base/process.cpp
	$(cpp)

linux_gcc_debug/profile.o: ../../../Extern/ECL/src/base/profile.cpp
	$(cpp)

linux_gcc_debug/queue.o: ../../../Extern/ECL/src/base/queue.cpp
	$(cpp)

linux_gcc_debug/ring.o: ../../../Extern/ECL/src/base/ring.cpp
	$(cpp)

linux_gcc_debug/semaphore.o: ../../../Extern/ECL/src/base/semaphore.cpp
	$(cpp)

linux_gcc_debug/sharedmem.o: ../../../Extern/ECL/src/base/sharedmem.cpp
	$(cpp)

linux_gcc_debug/string.o: ../../../Extern/ECL/src/base/string.cpp
	$(cpp)

linux_gcc_debug/string_ex.o: ../../../Extern/ECL/src/base/string_ex.cpp
	$(cpp)

linux_gcc_debug/thread.o: ../../../Extern/ECL/src/base/thread.cpp
	$(cpp)

