
make file generated by Autoconfig: dont edit

# build definitions
config = debug
compiler = gcc
system = linux
target_type = static_library

# include general build instructions
include $(SHACIRADIR)/Targ/platforms/linux_gcc.defs

# include dependencies
-include linux_gcc_debug.dep

A_I_PATHS = \
	-I../../../Extern/STYX/src \
	-I../../../Extern/STYX/src/inc \
	-I../../../Extern/STYX/src/libbase \
	-I../../../Extern/STYX/src/modstd
A_GEN_HEADERS =

A_L_PATHS = \
	-L"linux_gcc_debug"
A_LIBS = \
	-lstyx
A_OBJECTS = \
	linux_gcc_debug/binimg.o \
	linux_gcc_debug/binset.o \
	linux_gcc_debug/ccnv_lim.o \
	linux_gcc_debug/cfg_abs.o \
	linux_gcc_debug/cfg_dfn.o \
	linux_gcc_debug/charlib.o \
	linux_gcc_debug/cmd_int.o \
	linux_gcc_debug/cmd_lim.o \
	linux_gcc_debug/cmd_pim.o \
	linux_gcc_debug/com_get.o \
	linux_gcc_debug/ctoh_cim.o \
	linux_gcc_debug/ctx.o \
	linux_gcc_debug/ctx_app.o \
	linux_gcc_debug/dict.o \
	linux_gcc_debug/dicts.o \
	linux_gcc_debug/glo_tab.o \
	linux_gcc_debug/gls.o \
	linux_gcc_debug/gstream.o \
	linux_gcc_debug/hmap.o \
	linux_gcc_debug/hpat.o \
	linux_gcc_debug/hpat_int.o \
	linux_gcc_debug/hpat_lim.o \
	linux_gcc_debug/hpat_pim.o \
	linux_gcc_debug/hset.o \
	linux_gcc_debug/lim__cim.o \
	linux_gcc_debug/line_scn.o \
	linux_gcc_debug/list.o \
	linux_gcc_debug/literal.o \
	linux_gcc_debug/memosx.o \
	linux_gcc_debug/olist.o \
	linux_gcc_debug/otab.o \
	linux_gcc_debug/pathes.o \
	linux_gcc_debug/pgm_base.o \
	linux_gcc_debug/pim__cim.o \
	linux_gcc_debug/prim.o \
	linux_gcc_debug/prs.o \
	linux_gcc_debug/prs_abs.o \
	linux_gcc_debug/prs_gen.o \
	linux_gcc_debug/prs_io.o \
	linux_gcc_debug/ptm.o \
	linux_gcc_debug/ptm__cim.o \
	linux_gcc_debug/ptm_gen.o \
	linux_gcc_debug/ptm_pp.o \
	linux_gcc_debug/reg_exp.o \
	linux_gcc_debug/rexp_lim.o \
	linux_gcc_debug/scn_abs.o \
	linux_gcc_debug/scn_base.o \
	linux_gcc_debug/scn_gen.o \
	linux_gcc_debug/scn_io.o \
	linux_gcc_debug/scn_pre.o \
	linux_gcc_debug/sink.o \
	linux_gcc_debug/styd_cim.o \
	linux_gcc_debug/styp_cim.o \
	linux_gcc_debug/styx_cim.o \
	linux_gcc_debug/styx_gen.o \
	linux_gcc_debug/styx_int.o \
	linux_gcc_debug/styx_lim.o \
	linux_gcc_debug/styx_pim.o \
	linux_gcc_debug/symbols.o \
	linux_gcc_debug/sysbase0.o \
	linux_gcc_debug/sysbase1.o
A_TARGETS = \
	linux_gcc_debug/binimg.o \
	linux_gcc_debug/binset.o \
	linux_gcc_debug/ccnv_lim.o \
	linux_gcc_debug/cfg_abs.o \
	linux_gcc_debug/cfg_dfn.o \
	linux_gcc_debug/charlib.o \
	linux_gcc_debug/cmd_int.o \
	linux_gcc_debug/cmd_lim.o \
	linux_gcc_debug/cmd_pim.o \
	linux_gcc_debug/com_get.o \
	linux_gcc_debug/ctoh_cim.o \
	linux_gcc_debug/ctx.o \
	linux_gcc_debug/ctx_app.o \
	linux_gcc_debug/dict.o \
	linux_gcc_debug/dicts.o \
	linux_gcc_debug/glo_tab.o \
	linux_gcc_debug/gls.o \
	linux_gcc_debug/gstream.o \
	linux_gcc_debug/hmap.o \
	linux_gcc_debug/hpat.o \
	linux_gcc_debug/hpat_int.o \
	linux_gcc_debug/hpat_lim.o \
	linux_gcc_debug/hpat_pim.o \
	linux_gcc_debug/hset.o \
	linux_gcc_debug/lim__cim.o \
	linux_gcc_debug/line_scn.o \
	linux_gcc_debug/list.o \
	linux_gcc_debug/literal.o \
	linux_gcc_debug/memosx.o \
	linux_gcc_debug/olist.o \
	linux_gcc_debug/otab.o \
	linux_gcc_debug/pathes.o \
	linux_gcc_debug/pgm_base.o \
	linux_gcc_debug/pim__cim.o \
	linux_gcc_debug/prim.o \
	linux_gcc_debug/prs.o \
	linux_gcc_debug/prs_abs.o \
	linux_gcc_debug/prs_gen.o \
	linux_gcc_debug/prs_io.o \
	linux_gcc_debug/ptm.o \
	linux_gcc_debug/ptm__cim.o \
	linux_gcc_debug/ptm_gen.o \
	linux_gcc_debug/ptm_pp.o \
	linux_gcc_debug/reg_exp.o \
	linux_gcc_debug/rexp_lim.o \
	linux_gcc_debug/scn_abs.o \
	linux_gcc_debug/scn_base.o \
	linux_gcc_debug/scn_gen.o \
	linux_gcc_debug/scn_io.o \
	linux_gcc_debug/scn_pre.o \
	linux_gcc_debug/sink.o \
	linux_gcc_debug/styd_cim.o \
	linux_gcc_debug/styp_cim.o \
	linux_gcc_debug/styx_cim.o \
	linux_gcc_debug/styx_gen.o \
	linux_gcc_debug/styx_int.o \
	linux_gcc_debug/styx_lim.o \
	linux_gcc_debug/styx_pim.o \
	linux_gcc_debug/symbols.o \
	linux_gcc_debug/sysbase0.o \
	linux_gcc_debug/sysbase1.o

.PHONY: linux_gcc_debug all clean


dependencies:

clean:
	-rm $(A_TARGETS)

linux_gcc_debug/libstyx.a: $(A_TARGETS)
	$(lib)

all: dependencies linux_gcc_debug $(A_TARGETS) linux_gcc_debug/libstyx.a

linux_gcc_debug: linux_gcc_debug.mk
	$(mkdir) $@

linux_gcc_debug/binimg.o: ../../../Extern/STYX/src/libbase/binimg.c
	$(ccc)

linux_gcc_debug/binset.o: ../../../Extern/STYX/src/libbase/binset.c
	$(ccc)

linux_gcc_debug/ccnv_lim.o: ../../../Extern/STYX/src/gen/ccnv_lim.c
	$(ccc)

linux_gcc_debug/cfg_abs.o: ../../../Extern/STYX/src/libbase/cfg_abs.c
	$(ccc)

linux_gcc_debug/cfg_dfn.o: ../../../Extern/STYX/src/libbase/cfg_dfn.c
	$(ccc)

linux_gcc_debug/charlib.o: ../../../Extern/STYX/src/libutil/charlib.c
	$(ccc)

linux_gcc_debug/cmd_int.o: ../../../Extern/STYX/src/gen/cmd_int.c
	$(ccc)

linux_gcc_debug/cmd_lim.o: ../../../Extern/STYX/src/gen/cmd_lim.c
	$(ccc)

linux_gcc_debug/cmd_pim.o: ../../../Extern/STYX/src/gen/cmd_pim.c
	$(ccc)

linux_gcc_debug/com_get.o: ../../../Extern/STYX/src/libutil/com_get.c
	$(ccc)

linux_gcc_debug/ctoh_cim.o: ../../../Extern/STYX/src/gen/ctoh_cim.c
	$(ccc)

linux_gcc_debug/ctx.o: ../../../Extern/STYX/src/libutil/ctx.c
	$(ccc)

linux_gcc_debug/ctx_app.o: ../../../Extern/STYX/src/libbase/ctx_app.c
	$(ccc)

linux_gcc_debug/dict.o: ../../../Extern/STYX/src/libutil/dict.c
	$(ccc)

linux_gcc_debug/dicts.o: ../../../Extern/STYX/src/libutil/dicts.c
	$(ccc)

linux_gcc_debug/glo_tab.o: ../../../Extern/STYX/src/libbase/glo_tab.c
	$(ccc)

linux_gcc_debug/gls.o: ../../../Extern/STYX/src/modstd/gls.c
	$(ccc)

linux_gcc_debug/gstream.o: ../../../Extern/STYX/src/libbase/gstream.c
	$(ccc)

linux_gcc_debug/hmap.o: ../../../Extern/STYX/src/libbase/hmap.c
	$(ccc)

linux_gcc_debug/hpat.o: ../../../Extern/STYX/src/libutil/hpat.c
	$(ccc)

linux_gcc_debug/hpat_int.o: ../../../Extern/STYX/src/gen/hpat_int.c
	$(ccc)

linux_gcc_debug/hpat_lim.o: ../../../Extern/STYX/src/gen/hpat_lim.c
	$(ccc)

linux_gcc_debug/hpat_pim.o: ../../../Extern/STYX/src/gen/hpat_pim.c
	$(ccc)

linux_gcc_debug/hset.o: ../../../Extern/STYX/src/libbase/hset.c
	$(ccc)

linux_gcc_debug/lim__cim.o: ../../../Extern/STYX/src/gen/lim__cim.c
	$(ccc)

linux_gcc_debug/line_scn.o: ../../../Extern/STYX/src/libbase/line_scn.c
	$(ccc)

linux_gcc_debug/list.o: ../../../Extern/STYX/src/libbase/list.c
	$(ccc)

linux_gcc_debug/literal.o: ../../../Extern/STYX/src/libbase/literal.c
	$(ccc)

linux_gcc_debug/memosx.o: ../../../Extern/STYX/src/modstd/memosx.c
	$(ccc)

linux_gcc_debug/olist.o: ../../../Extern/STYX/src/libutil/olist.c
	$(ccc)

linux_gcc_debug/otab.o: ../../../Extern/STYX/src/libbase/otab.c
	$(ccc)

linux_gcc_debug/pathes.o: ../../../Extern/STYX/src/libbase/pathes.c
	$(ccc)

linux_gcc_debug/pgm_base.o: ../../../Extern/STYX/src/libutil/pgm_base.c
	$(ccc)

linux_gcc_debug/pim__cim.o: ../../../Extern/STYX/src/gen/pim__cim.c
	$(ccc)

linux_gcc_debug/prim.o: ../../../Extern/STYX/src/libbase/prim.c
	$(ccc)

linux_gcc_debug/prs.o: ../../../Extern/STYX/src/libbase/prs.c
	$(ccc)

linux_gcc_debug/prs_abs.o: ../../../Extern/STYX/src/libbase/prs_abs.c
	$(ccc)

linux_gcc_debug/prs_gen.o: ../../../Extern/STYX/src/libstyx/prs_gen.c
	$(ccc)

linux_gcc_debug/prs_io.o: ../../../Extern/STYX/src/libbase/prs_io.c
	$(ccc)

linux_gcc_debug/ptm.o: ../../../Extern/STYX/src/libbase/ptm.c
	$(ccc)

linux_gcc_debug/ptm__cim.o: ../../../Extern/STYX/src/gen/ptm__cim.c
	$(ccc)

linux_gcc_debug/ptm_gen.o: ../../../Extern/STYX/src/libbase/ptm_gen.c
	$(ccc)

linux_gcc_debug/ptm_pp.o: ../../../Extern/STYX/src/libbase/ptm_pp.c
	$(ccc)

linux_gcc_debug/reg_exp.o: ../../../Extern/STYX/src/libstyx/reg_exp.c
	$(ccc)

linux_gcc_debug/rexp_lim.o: ../../../Extern/STYX/src/gen/rexp_lim.c
	$(ccc)

linux_gcc_debug/scn_abs.o: ../../../Extern/STYX/src/libbase/scn_abs.c
	$(ccc)

linux_gcc_debug/scn_base.o: ../../../Extern/STYX/src/libbase/scn_base.c
	$(ccc)

linux_gcc_debug/scn_gen.o: ../../../Extern/STYX/src/libstyx/scn_gen.c
	$(ccc)

linux_gcc_debug/scn_io.o: ../../../Extern/STYX/src/libbase/scn_io.c
	$(ccc)

linux_gcc_debug/scn_pre.o: ../../../Extern/STYX/src/libbase/scn_pre.c
	$(ccc)

linux_gcc_debug/sink.o: ../../../Extern/STYX/src/libbase/sink.c
	$(ccc)

linux_gcc_debug/styd_cim.o: ../../../Extern/STYX/src/gen/styd_cim.c
	$(ccc)

linux_gcc_debug/styp_cim.o: ../../../Extern/STYX/src/gen/styp_cim.c
	$(ccc)

linux_gcc_debug/styx_cim.o: ../../../Extern/STYX/src/gen/styx_cim.c
	$(ccc)

linux_gcc_debug/styx_gen.o: ../../../Extern/STYX/src/libstyx/styx_gen.c
	$(ccc)

linux_gcc_debug/styx_int.o: ../../../Extern/STYX/src/gen/styx_int.c
	$(ccc)

linux_gcc_debug/styx_lim.o: ../../../Extern/STYX/src/gen/styx_lim.c
	$(ccc)

linux_gcc_debug/styx_pim.o: ../../../Extern/STYX/src/gen/styx_pim.c
	$(ccc)

linux_gcc_debug/symbols.o: ../../../Extern/STYX/src/libbase/symbols.c
	$(ccc)

linux_gcc_debug/sysbase0.o: ../../../Extern/STYX/src/libbase/sysbase0.c
	$(ccc)

linux_gcc_debug/sysbase1.o: ../../../Extern/STYX/src/libbase/sysbase1.c
	$(ccc)

