
make file generated by Autoconfig: dont edit

# build definitions
config = debug
compiler = gcc
system = linux
target_type = static_library
project_defs = -D_NO_QT_

# include general build instructions
include $(SHACIRADIR)/Targ/platforms/linux_gcc.defs

# include dependencies
-include linux_gcc_debug.dep

A_I_PATHS = \
	-I../../../Src \
	-I../../../Src/Include \
	-I../../../Src/Orb \
	-Ilinux_gcc_debug \
	-I../../../Extern/ECL/src \
	-I/prj/omniORB-4.0.7/include \
	-I/prj/omniORB-4.0.7/include/COS \
	-I/prj/omniORB-4.0.7/include/omniORB4 \
	-I../../../Extern/STYX/src \
	-I../../../Extern/STYX/src/inc \
	-I../../../Extern/STYX/src/libbase \
	-I../../../Extern/STYX/src/modstd
A_GEN_HEADERS = \
	linux_gcc_debug/Control.hh \
	linux_gcc_debug/EM63_int.h \
	linux_gcc_debug/EM63_lim.h \
	linux_gcc_debug/EM63_pim.h \
	linux_gcc_debug/Shacira_int.h \
	linux_gcc_debug/Shacira_lim.h \
	linux_gcc_debug/Shacira_pim.h

A_L_PATHS = \
	-L"../styx/linux_gcc_debug" \
	-L"/prj/omniORB-4.0.7/lib" \
	-L"../ecl/linux_gcc_debug" \
	-L"linux_gcc_debug"
A_LIBS = \
	-lccs \
	-lecl \
	-lomniDynamic4 \
	-lomniORB4 \
	-lomnithread \
	-lstyx
A_OBJECTS = \
	linux_gcc_debug/CNTRDATA.o \
	linux_gcc_debug/ControlDynSK.o \
	linux_gcc_debug/ControlSK.o \
	linux_gcc_debug/CorbaDefinitions.o \
	linux_gcc_debug/CosEventChannelAdminDynSK.o \
	linux_gcc_debug/CosEventChannelAdminSK.o \
	linux_gcc_debug/CosEventCommDynSK.o \
	linux_gcc_debug/CosEventCommSK.o \
	linux_gcc_debug/CosLifeCycleDynSK.o \
	linux_gcc_debug/CosLifeCycleSK.o \
	linux_gcc_debug/EM63_int.o \
	linux_gcc_debug/EM63_lim.o \
	linux_gcc_debug/EM63_pim.o \
	linux_gcc_debug/INSTDATA.o \
	linux_gcc_debug/OBJDATA.o \
	linux_gcc_debug/OrbUtils.o \
	linux_gcc_debug/Perfdata.o \
	linux_gcc_debug/Shacira_int.o \
	linux_gcc_debug/Shacira_lim.o \
	linux_gcc_debug/Shacira_pim.o \
	linux_gcc_debug/SystemText.o \
	linux_gcc_debug/cAbortCmd.o \
	linux_gcc_debug/cAbstractFileSystem.o \
	linux_gcc_debug/cActLine.o \
	linux_gcc_debug/cActProcedure.o \
	linux_gcc_debug/cActProgram.o \
	linux_gcc_debug/cAdapter.o \
	linux_gcc_debug/cAdapterFactory.o \
	linux_gcc_debug/cAddiStandard.o \
	linux_gcc_debug/cAlarm.o \
	linux_gcc_debug/cArgument.o \
	linux_gcc_debug/cAsyncChannel.o \
	linux_gcc_debug/cAtomicCondition.o \
	linux_gcc_debug/cBBRAMStorage.o \
	linux_gcc_debug/cBackupThread.o \
	linux_gcc_debug/cBitOperator.o \
	linux_gcc_debug/cBlob.o \
	linux_gcc_debug/cBlockBuffer.o \
	linux_gcc_debug/cBlockCache.o \
	linux_gcc_debug/cBlockQueue.o \
	linux_gcc_debug/cBridgeControl.o \
	linux_gcc_debug/cBroker.o \
	linux_gcc_debug/cBufferedFile.o \
	linux_gcc_debug/cCOSChannel.o \
	linux_gcc_debug/cCSAddress.o \
	linux_gcc_debug/cCSComm.o \
	linux_gcc_debug/cCSMsg.o \
	linux_gcc_debug/cCache.o \
	linux_gcc_debug/cCacheControl.o \
	linux_gcc_debug/cCell.o \
	linux_gcc_debug/cCellProcess.o \
	linux_gcc_debug/cCellProxy.o \
	linux_gcc_debug/cChannel.o \
	linux_gcc_debug/cChannelFactory.o \
	linux_gcc_debug/cChannelProxy.o \
	linux_gcc_debug/cCharReceiver.o \
	linux_gcc_debug/cCharRingBuffer.o \
	linux_gcc_debug/cClient.o \
	linux_gcc_debug/cClientData.o \
	linux_gcc_debug/cClients.o \
	linux_gcc_debug/cCondition.o \
	linux_gcc_debug/cConfiguration.o \
	linux_gcc_debug/cConfigurationDevice.o \
	linux_gcc_debug/cConfigurationObject.o \
	linux_gcc_debug/cConnector.o \
	linux_gcc_debug/cConsole.o \
	linux_gcc_debug/cConstInt.o \
	linux_gcc_debug/cConstReal.o \
	linux_gcc_debug/cConstString.o \
	linux_gcc_debug/cContext.o \
	linux_gcc_debug/cControlCondition.o \
	linux_gcc_debug/cControlProcedure.o \
	linux_gcc_debug/cControlProgram.o \
	linux_gcc_debug/cControlStartCondition.o \
	linux_gcc_debug/cControlState.o \
	linux_gcc_debug/cControlThread.o \
	linux_gcc_debug/cConvUtils.o \
	linux_gcc_debug/cCorbaCellProxy.o \
	linux_gcc_debug/cCorbaProxy.o \
	linux_gcc_debug/cCosEventChannelProxy.o \
	linux_gcc_debug/cCurve.o \
	linux_gcc_debug/cCustomFunctions.o \
	linux_gcc_debug/cCyclicCondition.o \
	linux_gcc_debug/cDataChange.o \
	linux_gcc_debug/cDataChangeAdapter.o \
	linux_gcc_debug/cDataControl.o \
	linux_gcc_debug/cDataFile.o \
	linux_gcc_debug/cDataset.o \
	linux_gcc_debug/cDatasetDirectory.o \
	linux_gcc_debug/cDevice.o \
	linux_gcc_debug/cDeviceFactory.o \
	linux_gcc_debug/cDigIO.o \
	linux_gcc_debug/cDigIODevice.o \
	linux_gcc_debug/cDownloadCmd.o \
	linux_gcc_debug/cEM63Interface.o \
	linux_gcc_debug/cEM63Job.o \
	linux_gcc_debug/cEM63Parser.o \
	linux_gcc_debug/cEM63Program.o \
	linux_gcc_debug/cEM63Requester.o \
	linux_gcc_debug/cEM63Session.o \
	linux_gcc_debug/cEM63StyxParser.o \
	linux_gcc_debug/cElementRefs.o \
	linux_gcc_debug/cError.o \
	linux_gcc_debug/cEvent.o \
	linux_gcc_debug/cEventAdapter.o \
	linux_gcc_debug/cEventControl.o \
	linux_gcc_debug/cEventlogCmd.o \
	linux_gcc_debug/cExtendedObjectRing.o \
	linux_gcc_debug/cFM2Device.o \
	linux_gcc_debug/cFileConsole.o \
	linux_gcc_debug/cFileContext.o \
	linux_gcc_debug/cFileStorage.o \
	linux_gcc_debug/cFileSystemUtils.o \
	linux_gcc_debug/cFileVariable.o \
	linux_gcc_debug/cFlatObject.o \
	linux_gcc_debug/cFloatCurve.o \
	linux_gcc_debug/cFuncDecl.o \
	linux_gcc_debug/cFuncRef.o \
	linux_gcc_debug/cFuncRefArg.o \
	linux_gcc_debug/cGateway.o \
	linux_gcc_debug/cGatewayClient.o \
	linux_gcc_debug/cGatewayInterface.o \
	linux_gcc_debug/cGatewayServer.o \
	linux_gcc_debug/cGetIdCmd.o \
	linux_gcc_debug/cGetInfoCmd.o \
	linux_gcc_debug/cGrabberDevice.o \
	linux_gcc_debug/cGraphicCurve.o \
	linux_gcc_debug/cIdsGrabber.o \
	linux_gcc_debug/cImage.o \
	linux_gcc_debug/cInetAddress.o \
	linux_gcc_debug/cInfo.o \
	linux_gcc_debug/cIniFile.o \
	linux_gcc_debug/cInterfaceFilter.o \
	linux_gcc_debug/cInternalBridge.o \
	linux_gcc_debug/cInterval.o \
	linux_gcc_debug/cJob.o \
	linux_gcc_debug/cJobEntry.o \
	linux_gcc_debug/cJobManager.o \
	linux_gcc_debug/cJobSpec.o \
	linux_gcc_debug/cJobs.o \
	linux_gcc_debug/cLinuxPort.o \
	linux_gcc_debug/cLiteString.o \
	linux_gcc_debug/cLiteWString.o \
	linux_gcc_debug/cLocalChannel.o \
	linux_gcc_debug/cLocalContext.o \
	linux_gcc_debug/cLocalVariable.o \
	linux_gcc_debug/cLogFile.o \
	linux_gcc_debug/cMapping.o \
	linux_gcc_debug/cMemIO.o \
	linux_gcc_debug/cMemoryAddressedDevice.o \
	linux_gcc_debug/cMemoryConsole.o \
	linux_gcc_debug/cMemoryPtr.o \
	linux_gcc_debug/cMultiplexer.o \
	linux_gcc_debug/cNameSpace.o \
	linux_gcc_debug/cNameSpaceIterator.o \
	linux_gcc_debug/cNameSpaceNode.o \
	linux_gcc_debug/cNodeContext.o \
	linux_gcc_debug/cNodeObject.o \
	linux_gcc_debug/cNullOperator.o \
	linux_gcc_debug/cOPCClientProcess.o \
	linux_gcc_debug/cOPCRequestHandler.o \
	linux_gcc_debug/cObjectBuffer.o \
	linux_gcc_debug/cObjectLock.o \
	linux_gcc_debug/cObjectQueue.o \
	linux_gcc_debug/cOptions.o \
	linux_gcc_debug/cPA150.o \
	linux_gcc_debug/cPPCClient.o \
	linux_gcc_debug/cPPCDevice.o \
	linux_gcc_debug/cPPCOperator.o \
	linux_gcc_debug/cPPCSerialComm.o \
	linux_gcc_debug/cPPCServer.o \
	linux_gcc_debug/cParamCondition.o \
	linux_gcc_debug/cPerfDevice.o \
	linux_gcc_debug/cPerformance.o \
	linux_gcc_debug/cPersistenceChannel.o \
	linux_gcc_debug/cPersistenceManager.o \
	linux_gcc_debug/cPersistentVariable.o \
	linux_gcc_debug/cPresentationCmd.o \
	linux_gcc_debug/cProcedureLine.o \
	linux_gcc_debug/cProgram.o \
	linux_gcc_debug/cProgramFactory.o \
	linux_gcc_debug/cProgress.o \
	linux_gcc_debug/cProperty.o \
	linux_gcc_debug/cPropertyDef.o \
	linux_gcc_debug/cProxy.o \
	linux_gcc_debug/cProxyReceiver.o \
	linux_gcc_debug/cProxyRequester.o \
	linux_gcc_debug/cProxySender.o \
	linux_gcc_debug/cProxyTable.o \
	linux_gcc_debug/cPtrList.o \
	linux_gcc_debug/cRefCache.o \
	linux_gcc_debug/cRemoteBridge.o \
	linux_gcc_debug/cRemoteChannel.o \
	linux_gcc_debug/cRemoteContext.o \
	linux_gcc_debug/cRemoteVar.o \
	linux_gcc_debug/cReportCmd.o \
	linux_gcc_debug/cRequest.o \
	linux_gcc_debug/cRequestHandler.o \
	linux_gcc_debug/cResources.o \
	linux_gcc_debug/cS7Operator.o \
	linux_gcc_debug/cSCPLProgram.o \
	linux_gcc_debug/cSDDLParser.o \
	linux_gcc_debug/cSHClientProcess.o \
	linux_gcc_debug/cSHFile.o \
	linux_gcc_debug/cSHProcess.o \
	linux_gcc_debug/cSHVariant.o \
	linux_gcc_debug/cSerialBridge.o \
	linux_gcc_debug/cSerialChannel.o \
	linux_gcc_debug/cSerialChannelFactory.o \
	linux_gcc_debug/cServer.o \
	linux_gcc_debug/cServerThread.o \
	linux_gcc_debug/cSetCmd.o \
	linux_gcc_debug/cSharedLibrary.o \
	linux_gcc_debug/cShortCurve.o \
	linux_gcc_debug/cShutDownControl.o \
	linux_gcc_debug/cSocketChannel.o \
	linux_gcc_debug/cSocketConsole.o \
	linux_gcc_debug/cSocketReceiver.o \
	linux_gcc_debug/cSockets.o \
	linux_gcc_debug/cStandardChannel.o \
	linux_gcc_debug/cStandardConsole.o \
	linux_gcc_debug/cStandardFileSystem.o \
	linux_gcc_debug/cStandardLinux.o \
	linux_gcc_debug/cStandardWin32.o \
	linux_gcc_debug/cState.o \
	linux_gcc_debug/cStateVariable.o \
	linux_gcc_debug/cStaticObject.o \
	linux_gcc_debug/cStorage.o \
	linux_gcc_debug/cStringCache.o \
	linux_gcc_debug/cStringUtils.o \
	linux_gcc_debug/cStyxParser.o \
	linux_gcc_debug/cSubFile.o \
	linux_gcc_debug/cSysProcess.o \
	linux_gcc_debug/cSystemUtils.o \
	linux_gcc_debug/cTCPComm.o \
	linux_gcc_debug/cTCPReceiver.o \
	linux_gcc_debug/cTestProgram.o \
	linux_gcc_debug/cText.o \
	linux_gcc_debug/cTextTable.o \
	linux_gcc_debug/cTimeCondition.o \
	linux_gcc_debug/cTimeObject.o \
	linux_gcc_debug/cTimeProtocol.o \
	linux_gcc_debug/cTokenizer.o \
	linux_gcc_debug/cTransferObject.o \
	linux_gcc_debug/cTransientObject.o \
	linux_gcc_debug/cTree.o \
	linux_gcc_debug/cTypeDef.o \
	linux_gcc_debug/cTypeFactory.o \
	linux_gcc_debug/cUDPClient.o \
	linux_gcc_debug/cUDPComm.o \
	linux_gcc_debug/cUDPServer.o \
	linux_gcc_debug/cUnitDef.o \
	linux_gcc_debug/cUploadCmd.o \
	linux_gcc_debug/cUserInfo.o \
	linux_gcc_debug/cValue.o \
	linux_gcc_debug/cValueBuffer.o \
	linux_gcc_debug/cVarDef.o \
	linux_gcc_debug/cVarRef.o \
	linux_gcc_debug/cVarRefArg.o \
	linux_gcc_debug/cVariable.o \
	linux_gcc_debug/cVariableValues.o \
	linux_gcc_debug/cVariant.o \
	linux_gcc_debug/cVirtualSocketChannel.o \
	linux_gcc_debug/cWTNode.o \
	linux_gcc_debug/cWTNodes.o \
	linux_gcc_debug/cexceptionhnd.o \
	linux_gcc_debug/cstringlist.o \
	linux_gcc_debug/cstringsink.o \
	linux_gcc_debug/debug_log.o \
	linux_gcc_debug/iCellObject.o \
	linux_gcc_debug/utilities.o
A_TARGETS = \
	linux_gcc_debug/Control.hh \
	linux_gcc_debug/EM63_int.h \
	linux_gcc_debug/EM63_lim.h \
	linux_gcc_debug/EM63_pim.h \
	linux_gcc_debug/Shacira_int.h \
	linux_gcc_debug/Shacira_lim.h \
	linux_gcc_debug/Shacira_pim.h \
	linux_gcc_debug/ControlDynSK.cpp \
	linux_gcc_debug/ControlSK.cpp \
	linux_gcc_debug/EM63_int.c \
	linux_gcc_debug/EM63_lim.c \
	linux_gcc_debug/EM63_pim.c \
	linux_gcc_debug/Shacira_int.c \
	linux_gcc_debug/Shacira_lim.c \
	linux_gcc_debug/Shacira_pim.c \
	linux_gcc_debug/CNTRDATA.o \
	linux_gcc_debug/ControlDynSK.o \
	linux_gcc_debug/ControlSK.o \
	linux_gcc_debug/CorbaDefinitions.o \
	linux_gcc_debug/CosEventChannelAdminDynSK.o \
	linux_gcc_debug/CosEventChannelAdminSK.o \
	linux_gcc_debug/CosEventCommDynSK.o \
	linux_gcc_debug/CosEventCommSK.o \
	linux_gcc_debug/CosLifeCycleDynSK.o \
	linux_gcc_debug/CosLifeCycleSK.o \
	linux_gcc_debug/EM63_int.o \
	linux_gcc_debug/EM63_lim.o \
	linux_gcc_debug/EM63_pim.o \
	linux_gcc_debug/INSTDATA.o \
	linux_gcc_debug/OBJDATA.o \
	linux_gcc_debug/OrbUtils.o \
	linux_gcc_debug/Perfdata.o \
	linux_gcc_debug/Shacira_int.o \
	linux_gcc_debug/Shacira_lim.o \
	linux_gcc_debug/Shacira_pim.o \
	linux_gcc_debug/SystemText.o \
	linux_gcc_debug/cAbortCmd.o \
	linux_gcc_debug/cAbstractFileSystem.o \
	linux_gcc_debug/cActLine.o \
	linux_gcc_debug/cActProcedure.o \
	linux_gcc_debug/cActProgram.o \
	linux_gcc_debug/cAdapter.o \
	linux_gcc_debug/cAdapterFactory.o \
	linux_gcc_debug/cAddiStandard.o \
	linux_gcc_debug/cAlarm.o \
	linux_gcc_debug/cArgument.o \
	linux_gcc_debug/cAsyncChannel.o \
	linux_gcc_debug/cAtomicCondition.o \
	linux_gcc_debug/cBBRAMStorage.o \
	linux_gcc_debug/cBackupThread.o \
	linux_gcc_debug/cBitOperator.o \
	linux_gcc_debug/cBlob.o \
	linux_gcc_debug/cBlockBuffer.o \
	linux_gcc_debug/cBlockCache.o \
	linux_gcc_debug/cBlockQueue.o \
	linux_gcc_debug/cBridgeControl.o \
	linux_gcc_debug/cBroker.o \
	linux_gcc_debug/cBufferedFile.o \
	linux_gcc_debug/cCOSChannel.o \
	linux_gcc_debug/cCSAddress.o \
	linux_gcc_debug/cCSComm.o \
	linux_gcc_debug/cCSMsg.o \
	linux_gcc_debug/cCache.o \
	linux_gcc_debug/cCacheControl.o \
	linux_gcc_debug/cCell.o \
	linux_gcc_debug/cCellProcess.o \
	linux_gcc_debug/cCellProxy.o \
	linux_gcc_debug/cChannel.o \
	linux_gcc_debug/cChannelFactory.o \
	linux_gcc_debug/cChannelProxy.o \
	linux_gcc_debug/cCharReceiver.o \
	linux_gcc_debug/cCharRingBuffer.o \
	linux_gcc_debug/cClient.o \
	linux_gcc_debug/cClientData.o \
	linux_gcc_debug/cClients.o \
	linux_gcc_debug/cCondition.o \
	linux_gcc_debug/cConfiguration.o \
	linux_gcc_debug/cConfigurationDevice.o \
	linux_gcc_debug/cConfigurationObject.o \
	linux_gcc_debug/cConnector.o \
	linux_gcc_debug/cConsole.o \
	linux_gcc_debug/cConstInt.o \
	linux_gcc_debug/cConstReal.o \
	linux_gcc_debug/cConstString.o \
	linux_gcc_debug/cContext.o \
	linux_gcc_debug/cControlCondition.o \
	linux_gcc_debug/cControlProcedure.o \
	linux_gcc_debug/cControlProgram.o \
	linux_gcc_debug/cControlStartCondition.o \
	linux_gcc_debug/cControlState.o \
	linux_gcc_debug/cControlThread.o \
	linux_gcc_debug/cConvUtils.o \
	linux_gcc_debug/cCorbaCellProxy.o \
	linux_gcc_debug/cCorbaProxy.o \
	linux_gcc_debug/cCosEventChannelProxy.o \
	linux_gcc_debug/cCurve.o \
	linux_gcc_debug/cCustomFunctions.o \
	linux_gcc_debug/cCyclicCondition.o \
	linux_gcc_debug/cDataChange.o \
	linux_gcc_debug/cDataChangeAdapter.o \
	linux_gcc_debug/cDataControl.o \
	linux_gcc_debug/cDataFile.o \
	linux_gcc_debug/cDataset.o \
	linux_gcc_debug/cDatasetDirectory.o \
	linux_gcc_debug/cDevice.o \
	linux_gcc_debug/cDeviceFactory.o \
	linux_gcc_debug/cDigIO.o \
	linux_gcc_debug/cDigIODevice.o \
	linux_gcc_debug/cDownloadCmd.o \
	linux_gcc_debug/cEM63Interface.o \
	linux_gcc_debug/cEM63Job.o \
	linux_gcc_debug/cEM63Parser.o \
	linux_gcc_debug/cEM63Program.o \
	linux_gcc_debug/cEM63Requester.o \
	linux_gcc_debug/cEM63Session.o \
	linux_gcc_debug/cEM63StyxParser.o \
	linux_gcc_debug/cElementRefs.o \
	linux_gcc_debug/cError.o \
	linux_gcc_debug/cEvent.o \
	linux_gcc_debug/cEventAdapter.o \
	linux_gcc_debug/cEventControl.o \
	linux_gcc_debug/cEventlogCmd.o \
	linux_gcc_debug/cExtendedObjectRing.o \
	linux_gcc_debug/cFM2Device.o \
	linux_gcc_debug/cFileConsole.o \
	linux_gcc_debug/cFileContext.o \
	linux_gcc_debug/cFileStorage.o \
	linux_gcc_debug/cFileSystemUtils.o \
	linux_gcc_debug/cFileVariable.o \
	linux_gcc_debug/cFlatObject.o \
	linux_gcc_debug/cFloatCurve.o \
	linux_gcc_debug/cFuncDecl.o \
	linux_gcc_debug/cFuncRef.o \
	linux_gcc_debug/cFuncRefArg.o \
	linux_gcc_debug/cGateway.o \
	linux_gcc_debug/cGatewayClient.o \
	linux_gcc_debug/cGatewayInterface.o \
	linux_gcc_debug/cGatewayServer.o \
	linux_gcc_debug/cGetIdCmd.o \
	linux_gcc_debug/cGetInfoCmd.o \
	linux_gcc_debug/cGrabberDevice.o \
	linux_gcc_debug/cGraphicCurve.o \
	linux_gcc_debug/cIdsGrabber.o \
	linux_gcc_debug/cImage.o \
	linux_gcc_debug/cInetAddress.o \
	linux_gcc_debug/cInfo.o \
	linux_gcc_debug/cIniFile.o \
	linux_gcc_debug/cInterfaceFilter.o \
	linux_gcc_debug/cInternalBridge.o \
	linux_gcc_debug/cInterval.o \
	linux_gcc_debug/cJob.o \
	linux_gcc_debug/cJobEntry.o \
	linux_gcc_debug/cJobManager.o \
	linux_gcc_debug/cJobSpec.o \
	linux_gcc_debug/cJobs.o \
	linux_gcc_debug/cLinuxPort.o \
	linux_gcc_debug/cLiteString.o \
	linux_gcc_debug/cLiteWString.o \
	linux_gcc_debug/cLocalChannel.o \
	linux_gcc_debug/cLocalContext.o \
	linux_gcc_debug/cLocalVariable.o \
	linux_gcc_debug/cLogFile.o \
	linux_gcc_debug/cMapping.o \
	linux_gcc_debug/cMemIO.o \
	linux_gcc_debug/cMemoryAddressedDevice.o \
	linux_gcc_debug/cMemoryConsole.o \
	linux_gcc_debug/cMemoryPtr.o \
	linux_gcc_debug/cMultiplexer.o \
	linux_gcc_debug/cNameSpace.o \
	linux_gcc_debug/cNameSpaceIterator.o \
	linux_gcc_debug/cNameSpaceNode.o \
	linux_gcc_debug/cNodeContext.o \
	linux_gcc_debug/cNodeObject.o \
	linux_gcc_debug/cNullOperator.o \
	linux_gcc_debug/cOPCClientProcess.o \
	linux_gcc_debug/cOPCRequestHandler.o \
	linux_gcc_debug/cObjectBuffer.o \
	linux_gcc_debug/cObjectLock.o \
	linux_gcc_debug/cObjectQueue.o \
	linux_gcc_debug/cOptions.o \
	linux_gcc_debug/cPA150.o \
	linux_gcc_debug/cPPCClient.o \
	linux_gcc_debug/cPPCDevice.o \
	linux_gcc_debug/cPPCOperator.o \
	linux_gcc_debug/cPPCSerialComm.o \
	linux_gcc_debug/cPPCServer.o \
	linux_gcc_debug/cParamCondition.o \
	linux_gcc_debug/cPerfDevice.o \
	linux_gcc_debug/cPerformance.o \
	linux_gcc_debug/cPersistenceChannel.o \
	linux_gcc_debug/cPersistenceManager.o \
	linux_gcc_debug/cPersistentVariable.o \
	linux_gcc_debug/cPresentationCmd.o \
	linux_gcc_debug/cProcedureLine.o \
	linux_gcc_debug/cProgram.o \
	linux_gcc_debug/cProgramFactory.o \
	linux_gcc_debug/cProgress.o \
	linux_gcc_debug/cProperty.o \
	linux_gcc_debug/cPropertyDef.o \
	linux_gcc_debug/cProxy.o \
	linux_gcc_debug/cProxyReceiver.o \
	linux_gcc_debug/cProxyRequester.o \
	linux_gcc_debug/cProxySender.o \
	linux_gcc_debug/cProxyTable.o \
	linux_gcc_debug/cPtrList.o \
	linux_gcc_debug/cRefCache.o \
	linux_gcc_debug/cRemoteBridge.o \
	linux_gcc_debug/cRemoteChannel.o \
	linux_gcc_debug/cRemoteContext.o \
	linux_gcc_debug/cRemoteVar.o \
	linux_gcc_debug/cReportCmd.o \
	linux_gcc_debug/cRequest.o \
	linux_gcc_debug/cRequestHandler.o \
	linux_gcc_debug/cResources.o \
	linux_gcc_debug/cS7Operator.o \
	linux_gcc_debug/cSCPLProgram.o \
	linux_gcc_debug/cSDDLParser.o \
	linux_gcc_debug/cSHClientProcess.o \
	linux_gcc_debug/cSHFile.o \
	linux_gcc_debug/cSHProcess.o \
	linux_gcc_debug/cSHVariant.o \
	linux_gcc_debug/cSerialBridge.o \
	linux_gcc_debug/cSerialChannel.o \
	linux_gcc_debug/cSerialChannelFactory.o \
	linux_gcc_debug/cServer.o \
	linux_gcc_debug/cServerThread.o \
	linux_gcc_debug/cSetCmd.o \
	linux_gcc_debug/cSharedLibrary.o \
	linux_gcc_debug/cShortCurve.o \
	linux_gcc_debug/cShutDownControl.o \
	linux_gcc_debug/cSocketChannel.o \
	linux_gcc_debug/cSocketConsole.o \
	linux_gcc_debug/cSocketReceiver.o \
	linux_gcc_debug/cSockets.o \
	linux_gcc_debug/cStandardChannel.o \
	linux_gcc_debug/cStandardConsole.o \
	linux_gcc_debug/cStandardFileSystem.o \
	linux_gcc_debug/cStandardLinux.o \
	linux_gcc_debug/cStandardWin32.o \
	linux_gcc_debug/cState.o \
	linux_gcc_debug/cStateVariable.o \
	linux_gcc_debug/cStaticObject.o \
	linux_gcc_debug/cStorage.o \
	linux_gcc_debug/cStringCache.o \
	linux_gcc_debug/cStringUtils.o \
	linux_gcc_debug/cStyxParser.o \
	linux_gcc_debug/cSubFile.o \
	linux_gcc_debug/cSysProcess.o \
	linux_gcc_debug/cSystemUtils.o \
	linux_gcc_debug/cTCPComm.o \
	linux_gcc_debug/cTCPReceiver.o \
	linux_gcc_debug/cTestProgram.o \
	linux_gcc_debug/cText.o \
	linux_gcc_debug/cTextTable.o \
	linux_gcc_debug/cTimeCondition.o \
	linux_gcc_debug/cTimeObject.o \
	linux_gcc_debug/cTimeProtocol.o \
	linux_gcc_debug/cTokenizer.o \
	linux_gcc_debug/cTransferObject.o \
	linux_gcc_debug/cTransientObject.o \
	linux_gcc_debug/cTree.o \
	linux_gcc_debug/cTypeDef.o \
	linux_gcc_debug/cTypeFactory.o \
	linux_gcc_debug/cUDPClient.o \
	linux_gcc_debug/cUDPComm.o \
	linux_gcc_debug/cUDPServer.o \
	linux_gcc_debug/cUnitDef.o \
	linux_gcc_debug/cUploadCmd.o \
	linux_gcc_debug/cUserInfo.o \
	linux_gcc_debug/cValue.o \
	linux_gcc_debug/cValueBuffer.o \
	linux_gcc_debug/cVarDef.o \
	linux_gcc_debug/cVarRef.o \
	linux_gcc_debug/cVarRefArg.o \
	linux_gcc_debug/cVariable.o \
	linux_gcc_debug/cVariableValues.o \
	linux_gcc_debug/cVariant.o \
	linux_gcc_debug/cVirtualSocketChannel.o \
	linux_gcc_debug/cWTNode.o \
	linux_gcc_debug/cWTNodes.o \
	linux_gcc_debug/cexceptionhnd.o \
	linux_gcc_debug/cstringlist.o \
	linux_gcc_debug/cstringsink.o \
	linux_gcc_debug/debug_log.o \
	linux_gcc_debug/iCellObject.o \
	linux_gcc_debug/utilities.o

.PHONY: linux_gcc_debug all clean


dependencies:
	$(make) -C ../ecl -flinux_gcc_debug.mk all
	$(make) -C ../styx -flinux_gcc_debug.mk all

clean:
	-rm $(A_TARGETS)

linux_gcc_debug/libccs.a: $(A_TARGETS)
	$(lib)

all: dependencies linux_gcc_debug $(A_TARGETS) linux_gcc_debug/libccs.a

linux_gcc_debug: linux_gcc_debug.mk
	$(mkdir) $@

linux_gcc_debug/ControlDynSK.o: linux_gcc_debug/ControlDynSK.cpp
	$(cpp)

linux_gcc_debug/ControlSK.o: linux_gcc_debug/ControlSK.cpp
	$(cpp)

linux_gcc_debug/EM63_int.o: linux_gcc_debug/EM63_int.c
	$(ccc)

linux_gcc_debug/EM63_lim.o: linux_gcc_debug/EM63_lim.c
	$(ccc)

linux_gcc_debug/EM63_pim.o: linux_gcc_debug/EM63_pim.c
	$(ccc)

linux_gcc_debug/Shacira_int.o: linux_gcc_debug/Shacira_int.c
	$(ccc)

linux_gcc_debug/Shacira_lim.o: linux_gcc_debug/Shacira_lim.c
	$(ccc)

linux_gcc_debug/Shacira_pim.o: linux_gcc_debug/Shacira_pim.c
	$(ccc)

linux_gcc_debug/CNTRDATA.o: ../../../Src/Control/Device/Performance/CNTRDATA.C
	$(ccc)

linux_gcc_debug/Control.hh: ../../../Src/Orb/Control.idl
	$(cp) $< .
	omniidl -bcxx -WbBOA -Wba $<
	$(cp) Control.hh linux_gcc_debug
	$(cp) ControlSK.cc linux_gcc_debug/ControlSK.cpp
	$(cp) ControlDynSK.cc linux_gcc_debug/ControlDynSK.cpp
	$(rm) *.idl
	$(rm) *.hh
	$(rm) *.cc
linux_gcc_debug/ControlDynSK.cpp: ../../../Src/Orb/Control.idl
	$(cp) $< .
	omniidl -bcxx -WbBOA -Wba $<
	$(cp) Control.hh linux_gcc_debug
	$(cp) ControlSK.cc linux_gcc_debug/ControlSK.cpp
	$(cp) ControlDynSK.cc linux_gcc_debug/ControlDynSK.cpp
	$(rm) *.idl
	$(rm) *.hh
	$(rm) *.cc
linux_gcc_debug/ControlSK.cpp: ../../../Src/Orb/Control.idl
	$(cp) $< .
	omniidl -bcxx -WbBOA -Wba $<
	$(cp) Control.hh linux_gcc_debug
	$(cp) ControlSK.cc linux_gcc_debug/ControlSK.cpp
	$(cp) ControlDynSK.cc linux_gcc_debug/ControlDynSK.cpp
	$(rm) *.idl
	$(rm) *.hh
	$(rm) *.cc

linux_gcc_debug/CorbaDefinitions.o: ../../../Src/Orb/CorbaDefinitions.cpp
	$(cpp)

linux_gcc_debug/CosEventChannelAdminDynSK.o: ../../../Src/Orb/CosEventChannelAdminDynSK.cpp
	$(cpp)

linux_gcc_debug/CosEventChannelAdminSK.o: ../../../Src/Orb/CosEventChannelAdminSK.cpp
	$(cpp)

linux_gcc_debug/CosEventCommDynSK.o: ../../../Src/Orb/CosEventCommDynSK.cpp
	$(cpp)

linux_gcc_debug/CosEventCommSK.o: ../../../Src/Orb/CosEventCommSK.cpp
	$(cpp)

linux_gcc_debug/CosLifeCycleDynSK.o: ../../../Src/Orb/CosLifeCycleDynSK.cpp
	$(cpp)

linux_gcc_debug/CosLifeCycleSK.o: ../../../Src/Orb/CosLifeCycleSK.cpp
	$(cpp)

linux_gcc_debug/EM63_int.c: ../../../Src/Language/EM63.sty
	$(cp) $< .
	$(styx) EM63 -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/EM63_int.h: ../../../Src/Language/EM63.sty
	$(cp) $< .
	$(styx) EM63 -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/EM63_lim.c: ../../../Src/Language/EM63.sty
	$(cp) $< .
	$(styx) EM63 -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/EM63_lim.h: ../../../Src/Language/EM63.sty
	$(cp) $< .
	$(styx) EM63 -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/EM63_pim.c: ../../../Src/Language/EM63.sty
	$(cp) $< .
	$(styx) EM63 -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/EM63_pim.h: ../../../Src/Language/EM63.sty
	$(cp) $< .
	$(styx) EM63 -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty

linux_gcc_debug/INSTDATA.o: ../../../Src/Control/Device/Performance/INSTDATA.C
	$(ccc)

linux_gcc_debug/OBJDATA.o: ../../../Src/Control/Device/Performance/OBJDATA.C
	$(ccc)

linux_gcc_debug/OrbUtils.o: ../../../Src/Orb/OrbUtils.cpp
	$(cpp)

linux_gcc_debug/Perfdata.o: ../../../Src/Control/Device/Performance/Perfdata.c
	$(ccc)

linux_gcc_debug/Shacira_int.c: ../../../Src/Language/Shacira.sty
	$(cp) $< .
	$(styx) Shacira -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/Shacira_int.h: ../../../Src/Language/Shacira.sty
	$(cp) $< .
	$(styx) Shacira -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/Shacira_lim.c: ../../../Src/Language/Shacira.sty
	$(cp) $< .
	$(styx) Shacira -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/Shacira_lim.h: ../../../Src/Language/Shacira.sty
	$(cp) $< .
	$(styx) Shacira -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/Shacira_pim.c: ../../../Src/Language/Shacira.sty
	$(cp) $< .
	$(styx) Shacira -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty
linux_gcc_debug/Shacira_pim.h: ../../../Src/Language/Shacira.sty
	$(cp) $< .
	$(styx) Shacira -makeC -makeINT -verbose
	$(cp) *.c linux_gcc_debug
	$(ctoh) -ct -CPATH=./linux_gcc_debug -HPATH=./linux_gcc_debug -PRJ=./linux_gcc_debug
	$(rm) *.c
	$(rm) *.sty

linux_gcc_debug/SystemText.o: ../../../Src/System/Text/SystemText.cpp
	$(cpp)

linux_gcc_debug/cAbortCmd.o: ../../../Src/Control/Device/EM63/cAbortCmd.cpp
	$(cpp)

linux_gcc_debug/cAbstractFileSystem.o: ../../../Src/System/Sys/cAbstractFileSystem.cpp
	$(cpp)

linux_gcc_debug/cActLine.o: ../../../Src/System/PLC/cActLine.cpp
	$(cpp)

linux_gcc_debug/cActProcedure.o: ../../../Src/System/PLC/cActProcedure.cpp
	$(cpp)

linux_gcc_debug/cActProgram.o: ../../../Src/System/PLC/cActProgram.cpp
	$(cpp)

linux_gcc_debug/cAdapter.o: ../../../Src/System/Channel/cAdapter.cpp
	$(cpp)

linux_gcc_debug/cAdapterFactory.o: ../../../Src/System/Channel/cAdapterFactory.cpp
	$(cpp)

linux_gcc_debug/cAddiStandard.o: ../../../Src/Control/Device/DigIO/cAddiStandard.cpp
	$(cpp)

linux_gcc_debug/cAlarm.o: ../../../Src/System/Objects/cAlarm.cpp
	$(cpp)

linux_gcc_debug/cArgument.o: ../../../Src/System/Database/cArgument.cpp
	$(cpp)

linux_gcc_debug/cAsyncChannel.o: ../../../Src/System/Threads/cAsyncChannel.cpp
	$(cpp)

linux_gcc_debug/cAtomicCondition.o: ../../../Src/System/PLC/cAtomicCondition.cpp
	$(cpp)

linux_gcc_debug/cBBRAMStorage.o: ../../../Src/Control/LocalDatabase/cBBRAMStorage.cpp
	$(cpp)

linux_gcc_debug/cBackupThread.o: ../../../Src/Control/CellProcess/cBackupThread.cpp
	$(cpp)

linux_gcc_debug/cBitOperator.o: ../../../Src/Control/Device/cBitOperator.cpp
	$(cpp)

linux_gcc_debug/cBlob.o: ../../../Src/System/Database/cBlob.cpp
	$(cpp)

linux_gcc_debug/cBlockBuffer.o: ../../../Src/System/Memory/cBlockBuffer.cpp
	$(cpp)

linux_gcc_debug/cBlockCache.o: ../../../Src/Control/Device/cBlockCache.cpp
	$(cpp)

linux_gcc_debug/cBlockQueue.o: ../../../Src/System/ClientServer/cBlockQueue.cpp
	$(cpp)

linux_gcc_debug/cBridgeControl.o: ../../../Src/Control/SerialChannel/cBridgeControl.cpp
	$(cpp)

linux_gcc_debug/cBroker.o: ../../../Src/Orb/cBroker.cpp
	$(cpp)

linux_gcc_debug/cBufferedFile.o: ../../../Src/System/Sys/cBufferedFile.cpp
	$(cpp)

linux_gcc_debug/cCOSChannel.o: ../../../Src/System/Channel/cCOSChannel.cpp
	$(cpp)

linux_gcc_debug/cCSAddress.o: ../../../Src/System/ClientServer/cCSAddress.cpp
	$(cpp)

linux_gcc_debug/cCSComm.o: ../../../Src/System/ClientServer/cCSComm.cpp
	$(cpp)

linux_gcc_debug/cCSMsg.o: ../../../Src/System/ClientServer/cCSMsg.cpp
	$(cpp)

linux_gcc_debug/cCache.o: ../../../Src/Control/Device/cCache.cpp
	$(cpp)

linux_gcc_debug/cCacheControl.o: ../../../Src/Control/Device/cCacheControl.cpp
	$(cpp)

linux_gcc_debug/cCell.o: ../../../Src/Control/Cell/cCell.cpp
	$(cpp)

linux_gcc_debug/cCellProcess.o: ../../../Src/Control/CellProcess/cCellProcess.cpp
	$(cpp)

linux_gcc_debug/cCellProxy.o: ../../../Src/System/Process/cCellProxy.cpp
	$(cpp)

linux_gcc_debug/cChannel.o: ../../../Src/System/Channel/cChannel.cpp
	$(cpp)

linux_gcc_debug/cChannelFactory.o: ../../../Src/System/Channel/cChannelFactory.cpp
	$(cpp)

linux_gcc_debug/cChannelProxy.o: ../../../Src/System/Channel/cChannelProxy.cpp
	$(cpp)

linux_gcc_debug/cCharReceiver.o: ../../../Src/Control/SerialChannel/cCharReceiver.cpp
	$(cpp)

linux_gcc_debug/cCharRingBuffer.o: ../../../Src/System/Memory/cCharRingBuffer.cpp
	$(cpp)

linux_gcc_debug/cClient.o: ../../../Src/System/ClientServer/cClient.cpp
	$(cpp)

linux_gcc_debug/cClientData.o: ../../../Src/Client/ClientData/cClientData.cpp
	$(cpp)

linux_gcc_debug/cClients.o: ../../../Src/Client/ClientData/cClients.cpp
	$(cpp)

linux_gcc_debug/cCondition.o: ../../../Src/Control/Device/EM63/cCondition.cpp
	$(cpp)

linux_gcc_debug/cConfiguration.o: ../../../Src/System/Config/cConfiguration.cpp
	$(cpp)

linux_gcc_debug/cConfigurationDevice.o: ../../../Src/Control/Device/cConfigurationDevice.cpp
	$(cpp)

linux_gcc_debug/cConfigurationObject.o: ../../../Src/System/Config/cConfigurationObject.cpp
	$(cpp)

linux_gcc_debug/cConnector.o: ../../../Src/System/Channel/cConnector.cpp
	$(cpp)

linux_gcc_debug/cConsole.o: ../../../Src/System/Console/cConsole.cpp
	$(cpp)

linux_gcc_debug/cConstInt.o: ../../../Src/System/Database/cConstInt.cpp
	$(cpp)

linux_gcc_debug/cConstReal.o: ../../../Src/System/Database/cConstReal.cpp
	$(cpp)

linux_gcc_debug/cConstString.o: ../../../Src/System/Database/cConstString.cpp
	$(cpp)

linux_gcc_debug/cContext.o: ../../../Src/System/Database/cContext.cpp
	$(cpp)

linux_gcc_debug/cControlCondition.o: ../../../Src/System/PLC/cControlCondition.cpp
	$(cpp)

linux_gcc_debug/cControlProcedure.o: ../../../Src/System/PLC/cControlProcedure.cpp
	$(cpp)

linux_gcc_debug/cControlProgram.o: ../../../Src/System/PLC/cControlProgram.cpp
	$(cpp)

linux_gcc_debug/cControlStartCondition.o: ../../../Src/System/PLC/cControlStartCondition.cpp
	$(cpp)

linux_gcc_debug/cControlState.o: ../../../Src/System/PLC/cControlState.cpp
	$(cpp)

linux_gcc_debug/cControlThread.o: ../../../Src/System/Threads/cControlThread.cpp
	$(cpp)

linux_gcc_debug/cConvUtils.o: ../../../Src/System/Sys/cConvUtils.cpp
	$(cpp)

linux_gcc_debug/cCorbaCellProxy.o: ../../../Src/Orb/cCorbaCellProxy.cpp
	$(cpp)

linux_gcc_debug/cCorbaProxy.o: ../../../Src/System/Objects/cCorbaProxy.cpp
	$(cpp)

linux_gcc_debug/cCosEventChannelProxy.o: ../../../Src/Orb/cCosEventChannelProxy.cpp
	$(cpp)

linux_gcc_debug/cCurve.o: ../../../Src/System/Database/cCurve.cpp
	$(cpp)

linux_gcc_debug/cCustomFunctions.o: ../../../Src/System/cCustomFunctions.cpp
	$(cpp)

linux_gcc_debug/cCyclicCondition.o: ../../../Src/Control/Device/EM63/cCyclicCondition.cpp
	$(cpp)

linux_gcc_debug/cDataChange.o: ../../../Src/System/Objects/cDataChange.cpp
	$(cpp)

linux_gcc_debug/cDataChangeAdapter.o: ../../../Src/Client/Adapters/cDataChangeAdapter.cpp
	$(cpp)

linux_gcc_debug/cDataControl.o: ../../../Src/Client/Adapters/cDataControl.cpp
	$(cpp)

linux_gcc_debug/cDataFile.o: ../../../Src/System/Structs/cDataFile.cpp
	$(cpp)

linux_gcc_debug/cDataset.o: ../../../Src/System/Structs/cDataset.cpp
	$(cpp)

linux_gcc_debug/cDatasetDirectory.o: ../../../Src/System/Structs/cDatasetDirectory.cpp
	$(cpp)

linux_gcc_debug/cDevice.o: ../../../Src/Control/Device/cDevice.cpp
	$(cpp)

linux_gcc_debug/cDeviceFactory.o: ../../../Src/Control/Device/cDeviceFactory.cpp
	$(cpp)

linux_gcc_debug/cDigIO.o: ../../../Src/Control/Device/DigIO/cDigIO.cpp
	$(cpp)

linux_gcc_debug/cDigIODevice.o: ../../../Src/Control/Device/cDigIODevice.cpp
	$(cpp)

linux_gcc_debug/cDownloadCmd.o: ../../../Src/Control/Device/EM63/cDownloadCmd.cpp
	$(cpp)

linux_gcc_debug/cEM63Interface.o: ../../../Src/Control/Device/EM63/cEM63Interface.cpp
	$(cpp)

linux_gcc_debug/cEM63Job.o: ../../../Src/Control/Device/EM63/cEM63Job.cpp
	$(cpp)

linux_gcc_debug/cEM63Parser.o: ../../../Src/Language/cEM63Parser.cpp
	$(cpp)

linux_gcc_debug/cEM63Program.o: ../../../Src/Control/Cell/cEM63Program.cpp
	$(cpp)

linux_gcc_debug/cEM63Requester.o: ../../../Src/Control/Cell/cEM63Requester.cpp
	$(cpp)

linux_gcc_debug/cEM63Session.o: ../../../Src/Control/Device/EM63/cEM63Session.cpp
	$(cpp)

linux_gcc_debug/cEM63StyxParser.o: ../../../Src/Language/cEM63StyxParser.cpp
	$(cpp)

linux_gcc_debug/cElementRefs.o: ../../../Src/Control/Device/cElementRefs.cpp
	$(cpp)

linux_gcc_debug/cError.o: ../../../Src/System/cError.cpp
	$(cpp)

linux_gcc_debug/cEvent.o: ../../../Src/System/Objects/cEvent.cpp
	$(cpp)

linux_gcc_debug/cEventAdapter.o: ../../../Src/Client/Adapters/cEventAdapter.cpp
	$(cpp)

linux_gcc_debug/cEventControl.o: ../../../Src/Client/Adapters/cEventControl.cpp
	$(cpp)

linux_gcc_debug/cEventlogCmd.o: ../../../Src/Control/Device/EM63/cEventlogCmd.cpp
	$(cpp)

linux_gcc_debug/cExtendedObjectRing.o: ../../../Src/System/Structs/cExtendedObjectRing.cpp
	$(cpp)

linux_gcc_debug/cFM2Device.o: ../../../Src/Control/Device/cFM2Device.cpp
	$(cpp)

linux_gcc_debug/cFileConsole.o: ../../../Src/System/Console/cFileConsole.cpp
	$(cpp)

linux_gcc_debug/cFileContext.o: ../../../Src/System/Database/cFileContext.cpp
	$(cpp)

linux_gcc_debug/cFileStorage.o: ../../../Src/Control/LocalDatabase/cFileStorage.cpp
	$(cpp)

linux_gcc_debug/cFileSystemUtils.o: ../../../Src/System/Sys/cFileSystemUtils.cpp
	$(cpp)

linux_gcc_debug/cFileVariable.o: ../../../Src/System/Database/cFileVariable.cpp
	$(cpp)

linux_gcc_debug/cFlatObject.o: ../../../Src/System/Structs/cFlatObject.cpp
	$(cpp)

linux_gcc_debug/cFloatCurve.o: ../../../Src/System/Structs/cFloatCurve.cpp
	$(cpp)

linux_gcc_debug/cFuncDecl.o: ../../../Src/System/Database/cFuncDecl.cpp
	$(cpp)

linux_gcc_debug/cFuncRef.o: ../../../Src/System/Database/cFuncRef.cpp
	$(cpp)

linux_gcc_debug/cFuncRefArg.o: ../../../Src/System/Database/cFuncRefArg.cpp
	$(cpp)

linux_gcc_debug/cGateway.o: ../../../Src/Control/Cell/cGateway.cpp
	$(cpp)

linux_gcc_debug/cGatewayClient.o: ../../../Src/Client/GatewayInterface/cGatewayClient.cpp
	$(cpp)

linux_gcc_debug/cGatewayInterface.o: ../../../Src/Client/GatewayInterface/cGatewayInterface.cpp
	$(cpp)

linux_gcc_debug/cGatewayServer.o: ../../../Src/Control/Cell/cGatewayServer.cpp
	$(cpp)

linux_gcc_debug/cGetIdCmd.o: ../../../Src/Control/Device/EM63/cGetIdCmd.cpp
	$(cpp)

linux_gcc_debug/cGetInfoCmd.o: ../../../Src/Control/Device/EM63/cGetInfoCmd.cpp
	$(cpp)

linux_gcc_debug/cGrabberDevice.o: ../../../Src/Control/Device/cGrabberDevice.cpp
	$(cpp)

linux_gcc_debug/cGraphicCurve.o: ../../../Src/System/Structs/cGraphicCurve.cpp
	$(cpp)

linux_gcc_debug/cIdsGrabber.o: ../../../Src/Control/Device/Ids/cIdsGrabber.cpp
	$(cpp)

linux_gcc_debug/cImage.o: ../../../Src/System/Database/cImage.cpp
	$(cpp)

linux_gcc_debug/cInetAddress.o: ../../../Src/System/ClientServer/cInetAddress.cpp
	$(cpp)

linux_gcc_debug/cInfo.o: ../../../Src/System/Objects/cInfo.cpp
	$(cpp)

linux_gcc_debug/cIniFile.o: ../../../Src/System/cIniFile.cpp
	$(cpp)

linux_gcc_debug/cInterfaceFilter.o: ../../../Src/System/Database/cInterfaceFilter.cpp
	$(cpp)

linux_gcc_debug/cInternalBridge.o: ../../../Src/System/Channel/cInternalBridge.cpp
	$(cpp)

linux_gcc_debug/cInterval.o: ../../../Src/Control/Device/EM63/cInterval.cpp
	$(cpp)

linux_gcc_debug/cJob.o: ../../../Src/Control/Cell/cJob.cpp
	$(cpp)

linux_gcc_debug/cJobEntry.o: ../../../Src/System/Objects/cJobEntry.cpp
	$(cpp)

linux_gcc_debug/cJobManager.o: ../../../Src/Control/Cell/cJobManager.cpp
	$(cpp)

linux_gcc_debug/cJobSpec.o: ../../../Src/System/Objects/cJobSpec.cpp
	$(cpp)

linux_gcc_debug/cJobs.o: ../../../Src/Control/Cell/cJobs.cpp
	$(cpp)

linux_gcc_debug/cLinuxPort.o: ../../../Src/System/Sys/cLinuxPort.cpp
	$(cpp)

linux_gcc_debug/cLiteString.o: ../../../Src/System/cLiteString.cpp
	$(cpp)

linux_gcc_debug/cLiteWString.o: ../../../Src/System/cLiteWString.cpp
	$(cpp)

linux_gcc_debug/cLocalChannel.o: ../../../Src/System/Channel/cLocalChannel.cpp
	$(cpp)

linux_gcc_debug/cLocalContext.o: ../../../Src/Control/LocalDatabase/cLocalContext.cpp
	$(cpp)

linux_gcc_debug/cLocalVariable.o: ../../../Src/Control/LocalDatabase/cLocalVariable.cpp
	$(cpp)

linux_gcc_debug/cLogFile.o: ../../../Src/System/cLogFile.cpp
	$(cpp)

linux_gcc_debug/cMapping.o: ../../../Src/System/Database/cMapping.cpp
	$(cpp)

linux_gcc_debug/cMemIO.o: ../../../Src/Control/Device/DigIO/cMemIO.cpp
	$(cpp)

linux_gcc_debug/cMemoryAddressedDevice.o: ../../../Src/Control/Device/cMemoryAddressedDevice.cpp
	$(cpp)

linux_gcc_debug/cMemoryConsole.o: ../../../Src/System/Console/cMemoryConsole.cpp
	$(cpp)

linux_gcc_debug/cMemoryPtr.o: ../../../Src/System/Memory/cMemoryPtr.cpp
	$(cpp)

linux_gcc_debug/cMultiplexer.o: ../../../Src/Control/SerialChannel/cMultiplexer.cpp
	$(cpp)

linux_gcc_debug/cNameSpace.o: ../../../Src/System/Namespace/cNameSpace.cpp
	$(cpp)

linux_gcc_debug/cNameSpaceIterator.o: ../../../Src/System/Namespace/cNameSpaceIterator.cpp
	$(cpp)

linux_gcc_debug/cNameSpaceNode.o: ../../../Src/System/Namespace/cNameSpaceNode.cpp
	$(cpp)

linux_gcc_debug/cNodeContext.o: ../../../Src/System/Namespace/cNodeContext.cpp
	$(cpp)

linux_gcc_debug/cNodeObject.o: ../../../Src/System/Namespace/cNodeObject.cpp
	$(cpp)

linux_gcc_debug/cNullOperator.o: ../../../Src/Control/Device/cNullOperator.cpp
	$(cpp)

linux_gcc_debug/cOPCClientProcess.o: ../../../Src/System/Process/cOPCClientProcess.cpp
	$(cpp)

linux_gcc_debug/cOPCRequestHandler.o: ../../../Src/System/Process/cOPCRequestHandler.cpp
	$(cpp)

linux_gcc_debug/cObjectBuffer.o: ../../../Src/System/Objects/cObjectBuffer.cpp
	$(cpp)

linux_gcc_debug/cObjectLock.o: ../../../Src/System/Objects/cObjectLock.cpp
	$(cpp)

linux_gcc_debug/cObjectQueue.o: ../../../Src/System/Objects/cObjectQueue.cpp
	$(cpp)

linux_gcc_debug/cOptions.o: ../../../Src/System/Process/cOptions.cpp
	$(cpp)

linux_gcc_debug/cPA150.o: ../../../Src/Control/Device/DigIO/cPA150.cpp
	$(cpp)

linux_gcc_debug/cPPCClient.o: ../../../Src/Control/Device/PPCCom/cPPCClient.cpp
	$(cpp)

linux_gcc_debug/cPPCDevice.o: ../../../Src/Control/Device/PPCCom/cPPCDevice.cpp
	$(cpp)

linux_gcc_debug/cPPCOperator.o: ../../../Src/Control/Device/PPCCom/cPPCOperator.cpp
	$(cpp)

linux_gcc_debug/cPPCSerialComm.o: ../../../Src/Control/Device/PPCCom/cPPCSerialComm.cpp
	$(cpp)

linux_gcc_debug/cPPCServer.o: ../../../Src/Control/Device/PPCCom/cPPCServer.cpp
	$(cpp)

linux_gcc_debug/cParamCondition.o: ../../../Src/Control/Device/EM63/cParamCondition.cpp
	$(cpp)

linux_gcc_debug/cPerfDevice.o: ../../../Src/Control/Device/Performance/cPerfDevice.cpp
	$(cpp)

linux_gcc_debug/cPerformance.o: ../../../Src/Control/Device/Performance/cPerformance.cpp
	$(cpp)

linux_gcc_debug/cPersistenceChannel.o: ../../../Src/Control/LocalDatabase/cPersistenceChannel.cpp
	$(cpp)

linux_gcc_debug/cPersistenceManager.o: ../../../Src/Control/LocalDatabase/cPersistenceManager.cpp
	$(cpp)

linux_gcc_debug/cPersistentVariable.o: ../../../Src/Control/LocalDatabase/cPersistentVariable.cpp
	$(cpp)

linux_gcc_debug/cPresentationCmd.o: ../../../Src/Control/Device/EM63/cPresentationCmd.cpp
	$(cpp)

linux_gcc_debug/cProcedureLine.o: ../../../Src/System/PLC/cProcedureLine.cpp
	$(cpp)

linux_gcc_debug/cProgram.o: ../../../Src/Control/Cell/cProgram.cpp
	$(cpp)

linux_gcc_debug/cProgramFactory.o: ../../../Src/Control/Cell/cProgramFactory.cpp
	$(cpp)

linux_gcc_debug/cProgress.o: ../../../Src/System/Objects/cProgress.cpp
	$(cpp)

linux_gcc_debug/cProperty.o: ../../../Src/System/Config/cProperty.cpp
	$(cpp)

linux_gcc_debug/cPropertyDef.o: ../../../Src/System/Config/cPropertyDef.cpp
	$(cpp)

linux_gcc_debug/cProxy.o: ../../../Src/System/Objects/cProxy.cpp
	$(cpp)

linux_gcc_debug/cProxyReceiver.o: ../../../Src/System/Comm/cProxyReceiver.cpp
	$(cpp)

linux_gcc_debug/cProxyRequester.o: ../../../Src/System/Comm/cProxyRequester.cpp
	$(cpp)

linux_gcc_debug/cProxySender.o: ../../../Src/System/Comm/cProxySender.cpp
	$(cpp)

linux_gcc_debug/cProxyTable.o: ../../../Src/System/Comm/cProxyTable.cpp
	$(cpp)

linux_gcc_debug/cPtrList.o: ../../../Src/System/Memory/cPtrList.cpp
	$(cpp)

linux_gcc_debug/cRefCache.o: ../../../Src/System/Database/cRefCache.cpp
	$(cpp)

linux_gcc_debug/cRemoteBridge.o: ../../../Src/System/Channel/cRemoteBridge.cpp
	$(cpp)

linux_gcc_debug/cRemoteChannel.o: ../../../Src/System/Channel/cRemoteChannel.cpp
	$(cpp)

linux_gcc_debug/cRemoteContext.o: ../../../Src/Client/RemoteDatabase/cRemoteContext.cpp
	$(cpp)

linux_gcc_debug/cRemoteVar.o: ../../../Src/Client/RemoteDatabase/cRemoteVar.cpp
	$(cpp)

linux_gcc_debug/cReportCmd.o: ../../../Src/Control/Device/EM63/cReportCmd.cpp
	$(cpp)

linux_gcc_debug/cRequest.o: ../../../Src/System/Objects/cRequest.cpp
	$(cpp)

linux_gcc_debug/cRequestHandler.o: ../../../Src/System/Process/cRequestHandler.cpp
	$(cpp)

linux_gcc_debug/cResources.o: ../../../Src/System/Process/cResources.cpp
	$(cpp)

linux_gcc_debug/cS7Operator.o: ../../../Src/Control/Device/cS7Operator.cpp
	$(cpp)

linux_gcc_debug/cSCPLProgram.o: ../../../Src/Control/Cell/cSCPLProgram.cpp
	$(cpp)

linux_gcc_debug/cSDDLParser.o: ../../../Src/Language/cSDDLParser.cpp
	$(cpp)

linux_gcc_debug/cSHClientProcess.o: ../../../Src/System/Process/cSHClientProcess.cpp
	$(cpp)

linux_gcc_debug/cSHFile.o: ../../../Src/System/Sys/cSHFile.cpp
	$(cpp)

linux_gcc_debug/cSHProcess.o: ../../../Src/System/Process/cSHProcess.cpp
	$(cpp)

linux_gcc_debug/cSHVariant.o: ../../../Src/System/Database/cSHVariant.cpp
	$(cpp)

linux_gcc_debug/cSerialBridge.o: ../../../Src/Control/SerialChannel/cSerialBridge.cpp
	$(cpp)

linux_gcc_debug/cSerialChannel.o: ../../../Src/Control/SerialChannel/cSerialChannel.cpp
	$(cpp)

linux_gcc_debug/cSerialChannelFactory.o: ../../../Src/Control/SerialChannel/cSerialChannelFactory.cpp
	$(cpp)

linux_gcc_debug/cServer.o: ../../../Src/System/ClientServer/cServer.cpp
	$(cpp)

linux_gcc_debug/cServerThread.o: ../../../Src/System/ClientServer/cServerThread.cpp
	$(cpp)

linux_gcc_debug/cSetCmd.o: ../../../Src/Control/Device/EM63/cSetCmd.cpp
	$(cpp)

linux_gcc_debug/cSharedLibrary.o: ../../../Src/System/Sys/cSharedLibrary.cpp
	$(cpp)

linux_gcc_debug/cShortCurve.o: ../../../Src/System/Structs/cShortCurve.cpp
	$(cpp)

linux_gcc_debug/cShutDownControl.o: ../../../Src/System/Process/cShutDownControl.cpp
	$(cpp)

linux_gcc_debug/cSocketChannel.o: ../../../Src/Control/SerialChannel/cSocketChannel.cpp
	$(cpp)

linux_gcc_debug/cSocketConsole.o: ../../../Src/System/Console/cSocketConsole.cpp
	$(cpp)

linux_gcc_debug/cSocketReceiver.o: ../../../Src/Control/SerialChannel/cSocketReceiver.cpp
	$(cpp)

linux_gcc_debug/cSockets.o: ../../../Src/System/Sys/cSockets.cpp
	$(cpp)

linux_gcc_debug/cStandardChannel.o: ../../../Src/Control/SerialChannel/cStandardChannel.cpp
	$(cpp)

linux_gcc_debug/cStandardConsole.o: ../../../Src/System/Console/cStandardConsole.cpp
	$(cpp)

linux_gcc_debug/cStandardFileSystem.o: ../../../Src/System/Sys/cStandardFileSystem.cpp
	$(cpp)

linux_gcc_debug/cStandardLinux.o: ../../../Src/Control/SerialChannel/Base/cStandardLinux.cpp
	$(cpp)

linux_gcc_debug/cStandardWin32.o: ../../../Src/Control/SerialChannel/Base/cStandardWin32.cpp
	$(cpp)

linux_gcc_debug/cState.o: ../../../Src/System/Objects/cState.cpp
	$(cpp)

linux_gcc_debug/cStateVariable.o: ../../../Src/System/PLC/cStateVariable.cpp
	$(cpp)

linux_gcc_debug/cStaticObject.o: ../../../Src/System/Objects/cStaticObject.cpp
	$(cpp)

linux_gcc_debug/cStorage.o: ../../../Src/Control/LocalDatabase/cStorage.cpp
	$(cpp)

linux_gcc_debug/cStringCache.o: ../../../Src/Control/Device/cStringCache.cpp
	$(cpp)

linux_gcc_debug/cStringUtils.o: ../../../Src/System/cStringUtils.cpp
	$(cpp)

linux_gcc_debug/cStyxParser.o: ../../../Src/Language/cStyxParser.cpp
	$(cpp)

linux_gcc_debug/cSubFile.o: ../../../Src/Control/LocalDatabase/cSubFile.cpp
	$(cpp)

linux_gcc_debug/cSysProcess.o: ../../../Src/System/Sys/cSysProcess.cpp
	$(cpp)

linux_gcc_debug/cSystemUtils.o: ../../../Src/System/Sys/cSystemUtils.cpp
	$(cpp)

linux_gcc_debug/cTCPComm.o: ../../../Src/System/ClientServer/cTCPComm.cpp
	$(cpp)

linux_gcc_debug/cTCPReceiver.o: ../../../Src/Control/SerialChannel/cTCPReceiver.cpp
	$(cpp)

linux_gcc_debug/cTestProgram.o: ../../../Src/Control/Cell/Programs/cTestProgram.cpp
	$(cpp)

linux_gcc_debug/cText.o: ../../../Src/System/Text/cText.cpp
	$(cpp)

linux_gcc_debug/cTextTable.o: ../../../Src/System/Text/cTextTable.cpp
	$(cpp)

linux_gcc_debug/cTimeCondition.o: ../../../Src/Control/Device/EM63/cTimeCondition.cpp
	$(cpp)

linux_gcc_debug/cTimeObject.o: ../../../Src/System/cTimeObject.cpp
	$(cpp)

linux_gcc_debug/cTimeProtocol.o: ../../../Src/System/cTimeProtocol.cpp
	$(cpp)

linux_gcc_debug/cTokenizer.o: ../../../Src/System/cTokenizer.cpp
	$(cpp)

linux_gcc_debug/cTransferObject.o: ../../../Src/System/Objects/cTransferObject.cpp
	$(cpp)

linux_gcc_debug/cTransientObject.o: ../../../Src/System/Objects/cTransientObject.cpp
	$(cpp)

linux_gcc_debug/cTree.o: ../../../Src/System/Namespace/cTree.cpp
	$(cpp)

linux_gcc_debug/cTypeDef.o: ../../../Src/System/Config/cTypeDef.cpp
	$(cpp)

linux_gcc_debug/cTypeFactory.o: ../../../Src/System/Config/cTypeFactory.cpp
	$(cpp)

linux_gcc_debug/cUDPClient.o: ../../../Src/System/ClientServer/cUDPClient.cpp
	$(cpp)

linux_gcc_debug/cUDPComm.o: ../../../Src/System/ClientServer/cUDPComm.cpp
	$(cpp)

linux_gcc_debug/cUDPServer.o: ../../../Src/System/ClientServer/cUDPServer.cpp
	$(cpp)

linux_gcc_debug/cUnitDef.o: ../../../Src/System/Database/cUnitDef.cpp
	$(cpp)

linux_gcc_debug/cUploadCmd.o: ../../../Src/Control/Device/EM63/cUploadCmd.cpp
	$(cpp)

linux_gcc_debug/cUserInfo.o: ../../../Src/System/Objects/cUserInfo.cpp
	$(cpp)

linux_gcc_debug/cValue.o: ../../../Src/System/Config/cValue.cpp
	$(cpp)

linux_gcc_debug/cValueBuffer.o: ../../../Src/Control/LocalDatabase/cValueBuffer.cpp
	$(cpp)

linux_gcc_debug/cVarDef.o: ../../../Src/System/Database/cVarDef.cpp
	$(cpp)

linux_gcc_debug/cVarRef.o: ../../../Src/System/Database/cVarRef.cpp
	$(cpp)

linux_gcc_debug/cVarRefArg.o: ../../../Src/System/Database/cVarRefArg.cpp
	$(cpp)

linux_gcc_debug/cVariable.o: ../../../Src/System/Database/cVariable.cpp
	$(cpp)

linux_gcc_debug/cVariableValues.o: ../../../Src/System/Database/cVariableValues.cpp
	$(cpp)

linux_gcc_debug/cVariant.o: ../../../Src/System/cVariant.cpp
	$(cpp)

linux_gcc_debug/cVirtualSocketChannel.o: ../../../Src/Control/SerialChannel/cVirtualSocketChannel.cpp
	$(cpp)

linux_gcc_debug/cWTNode.o: ../../../Src/Control/SerialChannel/cWTNode.cpp
	$(cpp)

linux_gcc_debug/cWTNodes.o: ../../../Src/Control/SerialChannel/cWTNodes.cpp
	$(cpp)

linux_gcc_debug/cexceptionhnd.o: ../../../Src/System/Sys/cexceptionhnd.cpp
	$(cpp)

linux_gcc_debug/cstringlist.o: ../../../Src/Tools/utilities/cstringlist.cpp
	$(cpp)

linux_gcc_debug/cstringsink.o: ../../../Src/Tools/utilities/cstringsink.cpp
	$(cpp)

linux_gcc_debug/debug_log.o: ../../../Src/System/Process/debug_log.cpp
	$(cpp)

linux_gcc_debug/iCellObject.o: ../../../Src/Orb/iCellObject.cpp
	$(cpp)

linux_gcc_debug/utilities.o: ../../../Src/Tools/utilities/utilities.cpp
	$(cpp)

