
make file generated by Autoconfig: dont edit

# build definitions
config = debug
compiler = gcc
system = linux
target_type = static_library

# include general build instructions
include $(SHACIRADIR)/Targ/platforms/linux_gcc.defs

# include dependencies
-include linux_gcc_debug.dep

A_I_PATHS = \
	-I../../../Src/GUIFramework \
	-I../../../Src/GUIFramework/QTFramework \
	-I../../../Src/GUIFramework/QTFramework/CWidgets \
	-I../../../Src/GUIFramework/QTFramework/Dialogs \
	-I../../../Src/GUIFramework/QTFramework/HTML \
	-I../../../Src/GUIFramework/QTFramework/Keypads \
	-Ilinux_gcc_debug \
	-I../../../Src \
	-I../../../Src/Include \
	-I../../../Src/Orb \
	-I../ccs/linux_gcc_debug \
	-I../../../Extern/ECL/src \
	-I/prj/omniORB-4.0.7/include \
	-I/prj/omniORB-4.0.7/include/COS \
	-I/prj/omniORB-4.0.7/include/omniORB4 \
	-I../../../Extern/STYX/src \
	-I../../../Extern/STYX/src/inc \
	-I../../../Extern/STYX/src/libbase \
	-I../../../Extern/STYX/src/modstd \
	-I/prj/qt3/include \
	-I/prj/qt3/makespecs/default \
	-I/prj/qt3/tools/designer/interfaces
A_GEN_HEADERS = \
	linux_gcc_debug/ContextExplorer.h \
	linux_gcc_debug/cactiondialog.h \
	linux_gcc_debug/cactvalue.h \
	linux_gcc_debug/calarmwidget.h \
	linux_gcc_debug/cappframe.h \
	linux_gcc_debug/cbuttongroup.h \
	linux_gcc_debug/ccheckbox.h \
	linux_gcc_debug/ccombobox.h \
	linux_gcc_debug/ccomplistview.h \
	linux_gcc_debug/ccomposedstack.h \
	linux_gcc_debug/ccoordsystem.h \
	linux_gcc_debug/cdate.h \
	linux_gcc_debug/cdatetime.h \
	linux_gcc_debug/cdirectory.h \
	linux_gcc_debug/cfixtext.h \
	linux_gcc_debug/cframe.h \
	linux_gcc_debug/cgraphic.h \
	linux_gcc_debug/cgroupbox.h \
	linux_gcc_debug/cgroupselectbutton.h \
	linux_gcc_debug/cindreqvalue.h \
	linux_gcc_debug/cinfolabel.h \
	linux_gcc_debug/clistview.h \
	linux_gcc_debug/cpage.h \
	linux_gcc_debug/cprocgraphic.h \
	linux_gcc_debug/cprogressbar.h \
	linux_gcc_debug/cpushbutton.h \
	linux_gcc_debug/cradiobutton.h \
	linux_gcc_debug/creqvalue.h \
	linux_gcc_debug/cringgraphic.h \
	linux_gcc_debug/cscrollbar.h \
	linux_gcc_debug/csimplegraphic.h \
	linux_gcc_debug/cslider.h \
	linux_gcc_debug/cspinbox.h \
	linux_gcc_debug/cstartupform.h \
	linux_gcc_debug/cstatebutton.h \
	linux_gcc_debug/ctable.h \
	linux_gcc_debug/ctabwidget.h \
	linux_gcc_debug/ctextedit.h \
	linux_gcc_debug/ctime.h \
	linux_gcc_debug/ctoolbutton.h \
	linux_gcc_debug/cvardimension.h \
	linux_gcc_debug/cvideo.h \
	linux_gcc_debug/cvirtualkeyboard.h \
	linux_gcc_debug/cwidget.h \
	linux_gcc_debug/cwidgetstack.h \
	linux_gcc_debug/qt_keyboard_layout_german.h \
	linux_gcc_debug/qt_keyboard_layout_standard.h \
	linux_gcc_debug/qt_keyboardalpha.h \
	linux_gcc_debug/qt_keypadnumeric.h

A_L_PATHS = \
	-L"/prj/qt3/lib" \
	-L"../styx/linux_gcc_debug" \
	-L"/prj/omniORB-4.0.7/lib" \
	-L"../ecl/linux_gcc_debug" \
	-L"../ccs/linux_gcc_debug" \
	-L"linux_gcc_debug"
A_LIBS = \
	-lguiframework \
	-lccs \
	-lecl \
	-lomniDynamic4 \
	-lomniORB4 \
	-lomnithread \
	-lstyx \
	-lqt-mt
A_OBJECTS = \
	linux_gcc_debug/ContextExplorer.o \
	linux_gcc_debug/ContextExplorerDialog.o \
	linux_gcc_debug/cCCSInterface.o \
	linux_gcc_debug/cContextChooser.o \
	linux_gcc_debug/cContextExplorer.o \
	linux_gcc_debug/cFormRequest.o \
	linux_gcc_debug/cGroup.o \
	linux_gcc_debug/cGroupList.o \
	linux_gcc_debug/cHTMLDocument.o \
	linux_gcc_debug/cHTMLElement.o \
	linux_gcc_debug/cHelpInterface.o \
	linux_gcc_debug/cNode.o \
	linux_gcc_debug/cNodeList.o \
	linux_gcc_debug/cQTUserInterface.o \
	linux_gcc_debug/cQtKeyboardAlpha.o \
	linux_gcc_debug/cQtKeypadNumeric.o \
	linux_gcc_debug/cSyncView.o \
	linux_gcc_debug/cUserInterface.o \
	linux_gcc_debug/cactiondialog.o \
	linux_gcc_debug/cactvalue.o \
	linux_gcc_debug/calarmwidget.o \
	linux_gcc_debug/cappframe.o \
	linux_gcc_debug/casyncfunction.o \
	linux_gcc_debug/cbuttongroup.o \
	linux_gcc_debug/ccheckbox.o \
	linux_gcc_debug/ccombobox.o \
	linux_gcc_debug/ccomplistview.o \
	linux_gcc_debug/ccomposedstack.o \
	linux_gcc_debug/ccoordsystem.o \
	linux_gcc_debug/cdate.o \
	linux_gcc_debug/cdatetime.o \
	linux_gcc_debug/cdirectory.o \
	linux_gcc_debug/cfixtext.o \
	linux_gcc_debug/cframe.o \
	linux_gcc_debug/cgraphic.o \
	linux_gcc_debug/cgroupbox.o \
	linux_gcc_debug/cgroupselectbutton.o \
	linux_gcc_debug/cguievents.o \
	linux_gcc_debug/cindreqvalue.o \
	linux_gcc_debug/cinfolabel.o \
	linux_gcc_debug/cinput.o \
	linux_gcc_debug/clistview.o \
	linux_gcc_debug/cpage.o \
	linux_gcc_debug/cpaintutils.o \
	linux_gcc_debug/cprocgraphic.o \
	linux_gcc_debug/cprogressbar.o \
	linux_gcc_debug/cpushbutton.o \
	linux_gcc_debug/cradiobutton.o \
	linux_gcc_debug/creqvalue.o \
	linux_gcc_debug/cringgraphic.o \
	linux_gcc_debug/crubberband.o \
	linux_gcc_debug/cscrollbar.o \
	linux_gcc_debug/csignalmanager.o \
	linux_gcc_debug/csimplegraphic.o \
	linux_gcc_debug/cslider.o \
	linux_gcc_debug/cspinbox.o \
	linux_gcc_debug/cstartupform.o \
	linux_gcc_debug/cstatebutton.o \
	linux_gcc_debug/ctable.o \
	linux_gcc_debug/ctabwidget.o \
	linux_gcc_debug/ctextedit.o \
	linux_gcc_debug/ctime.o \
	linux_gcc_debug/ctoolbutton.o \
	linux_gcc_debug/cvardimension.o \
	linux_gcc_debug/cvideo.o \
	linux_gcc_debug/cvirtualkeyboard.o \
	linux_gcc_debug/cwidget.o \
	linux_gcc_debug/cwidgetbase.o \
	linux_gcc_debug/cwidgetcomm.o \
	linux_gcc_debug/cwidgethelper.o \
	linux_gcc_debug/cwidgetstack.o \
	linux_gcc_debug/moc_ContextExplorer.o \
	linux_gcc_debug/moc_ContextExplorerDialog.o \
	linux_gcc_debug/moc_cQtKeyboardAlpha.o \
	linux_gcc_debug/moc_cQtKeypadNumeric.o \
	linux_gcc_debug/moc_cactiondialog.o \
	linux_gcc_debug/moc_cactvalue.o \
	linux_gcc_debug/moc_calarmwidget.o \
	linux_gcc_debug/moc_cappframe.o \
	linux_gcc_debug/moc_cbuttongroup.o \
	linux_gcc_debug/moc_ccheckbox.o \
	linux_gcc_debug/moc_ccombobox.o \
	linux_gcc_debug/moc_ccomplistview.o \
	linux_gcc_debug/moc_ccomposedstack.o \
	linux_gcc_debug/moc_ccoordsystem.o \
	linux_gcc_debug/moc_cdate.o \
	linux_gcc_debug/moc_cdatetime.o \
	linux_gcc_debug/moc_cdirectory.o \
	linux_gcc_debug/moc_cfixtext.o \
	linux_gcc_debug/moc_cframe.o \
	linux_gcc_debug/moc_cgraphic.o \
	linux_gcc_debug/moc_cgroupbox.o \
	linux_gcc_debug/moc_cgroupselectbutton.o \
	linux_gcc_debug/moc_cindreqvalue.o \
	linux_gcc_debug/moc_cinfolabel.o \
	linux_gcc_debug/moc_clistview.o \
	linux_gcc_debug/moc_cpage.o \
	linux_gcc_debug/moc_cprocgraphic.o \
	linux_gcc_debug/moc_cprogressbar.o \
	linux_gcc_debug/moc_cpublicdialog.o \
	linux_gcc_debug/moc_cpushbutton.o \
	linux_gcc_debug/moc_cradiobutton.o \
	linux_gcc_debug/moc_creqvalue.o \
	linux_gcc_debug/moc_cringgraphic.o \
	linux_gcc_debug/moc_cscrollbar.o \
	linux_gcc_debug/moc_csimplegraphic.o \
	linux_gcc_debug/moc_cslider.o \
	linux_gcc_debug/moc_cspinbox.o \
	linux_gcc_debug/moc_cstartupform.o \
	linux_gcc_debug/moc_cstatebutton.o \
	linux_gcc_debug/moc_ctable.o \
	linux_gcc_debug/moc_ctabwidget.o \
	linux_gcc_debug/moc_ctextedit.o \
	linux_gcc_debug/moc_ctime.o \
	linux_gcc_debug/moc_ctoolbutton.o \
	linux_gcc_debug/moc_cvardimension.o \
	linux_gcc_debug/moc_cvideo.o \
	linux_gcc_debug/moc_cvirtualkeyboard.o \
	linux_gcc_debug/moc_cwidget.o \
	linux_gcc_debug/moc_cwidgetcomm.o \
	linux_gcc_debug/moc_cwidgetstack.o \
	linux_gcc_debug/moc_qt_keyboard.o \
	linux_gcc_debug/moc_qt_keyboard_button.o \
	linux_gcc_debug/moc_qt_keyboard_input.o \
	linux_gcc_debug/moc_qt_keyboard_layout.o \
	linux_gcc_debug/moc_qt_keyboard_layout_german.o \
	linux_gcc_debug/moc_qt_keyboard_layout_standard.o \
	linux_gcc_debug/moc_qt_keyboardalpha.o \
	linux_gcc_debug/moc_qt_keypadnumeric.o \
	linux_gcc_debug/moc_touch_style.o \
	linux_gcc_debug/pluginlog.o \
	linux_gcc_debug/qt_keyboard.o \
	linux_gcc_debug/qt_keyboard_button.o \
	linux_gcc_debug/qt_keyboard_input.o \
	linux_gcc_debug/qt_keyboard_layout.o \
	linux_gcc_debug/qt_keyboard_layout_german.o \
	linux_gcc_debug/qt_keyboard_layout_standard.o \
	linux_gcc_debug/qt_keyboardalpha.o \
	linux_gcc_debug/qt_keypadnumeric.o \
	linux_gcc_debug/qt_navigation_widget.o \
	linux_gcc_debug/qt_number_validator.o \
	linux_gcc_debug/qt_property_widget.o \
	linux_gcc_debug/qt_string_validator.o \
	linux_gcc_debug/touch_style.o
A_TARGETS = \
	linux_gcc_debug/ContextExplorer.h \
	linux_gcc_debug/cactiondialog.h \
	linux_gcc_debug/cactvalue.h \
	linux_gcc_debug/calarmwidget.h \
	linux_gcc_debug/cappframe.h \
	linux_gcc_debug/cbuttongroup.h \
	linux_gcc_debug/ccheckbox.h \
	linux_gcc_debug/ccombobox.h \
	linux_gcc_debug/ccomplistview.h \
	linux_gcc_debug/ccomposedstack.h \
	linux_gcc_debug/ccoordsystem.h \
	linux_gcc_debug/cdate.h \
	linux_gcc_debug/cdatetime.h \
	linux_gcc_debug/cdirectory.h \
	linux_gcc_debug/cfixtext.h \
	linux_gcc_debug/cframe.h \
	linux_gcc_debug/cgraphic.h \
	linux_gcc_debug/cgroupbox.h \
	linux_gcc_debug/cgroupselectbutton.h \
	linux_gcc_debug/cindreqvalue.h \
	linux_gcc_debug/cinfolabel.h \
	linux_gcc_debug/clistview.h \
	linux_gcc_debug/cpage.h \
	linux_gcc_debug/cprocgraphic.h \
	linux_gcc_debug/cprogressbar.h \
	linux_gcc_debug/cpushbutton.h \
	linux_gcc_debug/cradiobutton.h \
	linux_gcc_debug/creqvalue.h \
	linux_gcc_debug/cringgraphic.h \
	linux_gcc_debug/cscrollbar.h \
	linux_gcc_debug/csimplegraphic.h \
	linux_gcc_debug/cslider.h \
	linux_gcc_debug/cspinbox.h \
	linux_gcc_debug/cstartupform.h \
	linux_gcc_debug/cstatebutton.h \
	linux_gcc_debug/ctable.h \
	linux_gcc_debug/ctabwidget.h \
	linux_gcc_debug/ctextedit.h \
	linux_gcc_debug/ctime.h \
	linux_gcc_debug/ctoolbutton.h \
	linux_gcc_debug/cvardimension.h \
	linux_gcc_debug/cvideo.h \
	linux_gcc_debug/cvirtualkeyboard.h \
	linux_gcc_debug/cwidget.h \
	linux_gcc_debug/cwidgetstack.h \
	linux_gcc_debug/qt_keyboard_layout_german.h \
	linux_gcc_debug/qt_keyboard_layout_standard.h \
	linux_gcc_debug/qt_keyboardalpha.h \
	linux_gcc_debug/qt_keypadnumeric.h \
	linux_gcc_debug/ContextExplorer.cpp \
	linux_gcc_debug/moc_ContextExplorer.cpp \
	linux_gcc_debug/moc_ContextExplorerDialog.cpp \
	linux_gcc_debug/moc_cQtKeyboardAlpha.cpp \
	linux_gcc_debug/moc_cQtKeypadNumeric.cpp \
	linux_gcc_debug/moc_cactiondialog.cpp \
	linux_gcc_debug/moc_cactvalue.cpp \
	linux_gcc_debug/moc_calarmwidget.cpp \
	linux_gcc_debug/moc_cappframe.cpp \
	linux_gcc_debug/moc_cbuttongroup.cpp \
	linux_gcc_debug/moc_ccheckbox.cpp \
	linux_gcc_debug/moc_ccombobox.cpp \
	linux_gcc_debug/moc_ccomplistview.cpp \
	linux_gcc_debug/moc_ccomposedstack.cpp \
	linux_gcc_debug/moc_ccoordsystem.cpp \
	linux_gcc_debug/moc_cdate.cpp \
	linux_gcc_debug/moc_cdatetime.cpp \
	linux_gcc_debug/moc_cdirectory.cpp \
	linux_gcc_debug/moc_cfixtext.cpp \
	linux_gcc_debug/moc_cframe.cpp \
	linux_gcc_debug/moc_cgraphic.cpp \
	linux_gcc_debug/moc_cgroupbox.cpp \
	linux_gcc_debug/moc_cgroupselectbutton.cpp \
	linux_gcc_debug/moc_cindreqvalue.cpp \
	linux_gcc_debug/moc_cinfolabel.cpp \
	linux_gcc_debug/moc_clistview.cpp \
	linux_gcc_debug/moc_cpage.cpp \
	linux_gcc_debug/moc_cprocgraphic.cpp \
	linux_gcc_debug/moc_cprogressbar.cpp \
	linux_gcc_debug/moc_cpublicdialog.cpp \
	linux_gcc_debug/moc_cpushbutton.cpp \
	linux_gcc_debug/moc_cradiobutton.cpp \
	linux_gcc_debug/moc_creqvalue.cpp \
	linux_gcc_debug/moc_cringgraphic.cpp \
	linux_gcc_debug/moc_cscrollbar.cpp \
	linux_gcc_debug/moc_csimplegraphic.cpp \
	linux_gcc_debug/moc_cslider.cpp \
	linux_gcc_debug/moc_cspinbox.cpp \
	linux_gcc_debug/moc_cstartupform.cpp \
	linux_gcc_debug/moc_cstatebutton.cpp \
	linux_gcc_debug/moc_ctable.cpp \
	linux_gcc_debug/moc_ctabwidget.cpp \
	linux_gcc_debug/moc_ctextedit.cpp \
	linux_gcc_debug/moc_ctime.cpp \
	linux_gcc_debug/moc_ctoolbutton.cpp \
	linux_gcc_debug/moc_cvardimension.cpp \
	linux_gcc_debug/moc_cvideo.cpp \
	linux_gcc_debug/moc_cvirtualkeyboard.cpp \
	linux_gcc_debug/moc_cwidget.cpp \
	linux_gcc_debug/moc_cwidgetcomm.cpp \
	linux_gcc_debug/moc_cwidgetstack.cpp \
	linux_gcc_debug/moc_qt_keyboard.cpp \
	linux_gcc_debug/moc_qt_keyboard_button.cpp \
	linux_gcc_debug/moc_qt_keyboard_input.cpp \
	linux_gcc_debug/moc_qt_keyboard_layout.cpp \
	linux_gcc_debug/moc_qt_keyboard_layout_german.cpp \
	linux_gcc_debug/moc_qt_keyboard_layout_standard.cpp \
	linux_gcc_debug/moc_qt_keyboardalpha.cpp \
	linux_gcc_debug/moc_qt_keypadnumeric.cpp \
	linux_gcc_debug/moc_touch_style.cpp \
	linux_gcc_debug/qt_keyboard_layout_german.cpp \
	linux_gcc_debug/qt_keyboard_layout_standard.cpp \
	linux_gcc_debug/qt_keyboardalpha.cpp \
	linux_gcc_debug/qt_keypadnumeric.cpp \
	linux_gcc_debug/ContextExplorer.o \
	linux_gcc_debug/ContextExplorerDialog.o \
	linux_gcc_debug/cCCSInterface.o \
	linux_gcc_debug/cContextChooser.o \
	linux_gcc_debug/cContextExplorer.o \
	linux_gcc_debug/cFormRequest.o \
	linux_gcc_debug/cGroup.o \
	linux_gcc_debug/cGroupList.o \
	linux_gcc_debug/cHTMLDocument.o \
	linux_gcc_debug/cHTMLElement.o \
	linux_gcc_debug/cHelpInterface.o \
	linux_gcc_debug/cNode.o \
	linux_gcc_debug/cNodeList.o \
	linux_gcc_debug/cQTUserInterface.o \
	linux_gcc_debug/cQtKeyboardAlpha.o \
	linux_gcc_debug/cQtKeypadNumeric.o \
	linux_gcc_debug/cSyncView.o \
	linux_gcc_debug/cUserInterface.o \
	linux_gcc_debug/cactiondialog.o \
	linux_gcc_debug/cactvalue.o \
	linux_gcc_debug/calarmwidget.o \
	linux_gcc_debug/cappframe.o \
	linux_gcc_debug/casyncfunction.o \
	linux_gcc_debug/cbuttongroup.o \
	linux_gcc_debug/ccheckbox.o \
	linux_gcc_debug/ccombobox.o \
	linux_gcc_debug/ccomplistview.o \
	linux_gcc_debug/ccomposedstack.o \
	linux_gcc_debug/ccoordsystem.o \
	linux_gcc_debug/cdate.o \
	linux_gcc_debug/cdatetime.o \
	linux_gcc_debug/cdirectory.o \
	linux_gcc_debug/cfixtext.o \
	linux_gcc_debug/cframe.o \
	linux_gcc_debug/cgraphic.o \
	linux_gcc_debug/cgroupbox.o \
	linux_gcc_debug/cgroupselectbutton.o \
	linux_gcc_debug/cguievents.o \
	linux_gcc_debug/cindreqvalue.o \
	linux_gcc_debug/cinfolabel.o \
	linux_gcc_debug/cinput.o \
	linux_gcc_debug/clistview.o \
	linux_gcc_debug/cpage.o \
	linux_gcc_debug/cpaintutils.o \
	linux_gcc_debug/cprocgraphic.o \
	linux_gcc_debug/cprogressbar.o \
	linux_gcc_debug/cpushbutton.o \
	linux_gcc_debug/cradiobutton.o \
	linux_gcc_debug/creqvalue.o \
	linux_gcc_debug/cringgraphic.o \
	linux_gcc_debug/crubberband.o \
	linux_gcc_debug/cscrollbar.o \
	linux_gcc_debug/csignalmanager.o \
	linux_gcc_debug/csimplegraphic.o \
	linux_gcc_debug/cslider.o \
	linux_gcc_debug/cspinbox.o \
	linux_gcc_debug/cstartupform.o \
	linux_gcc_debug/cstatebutton.o \
	linux_gcc_debug/ctable.o \
	linux_gcc_debug/ctabwidget.o \
	linux_gcc_debug/ctextedit.o \
	linux_gcc_debug/ctime.o \
	linux_gcc_debug/ctoolbutton.o \
	linux_gcc_debug/cvardimension.o \
	linux_gcc_debug/cvideo.o \
	linux_gcc_debug/cvirtualkeyboard.o \
	linux_gcc_debug/cwidget.o \
	linux_gcc_debug/cwidgetbase.o \
	linux_gcc_debug/cwidgetcomm.o \
	linux_gcc_debug/cwidgethelper.o \
	linux_gcc_debug/cwidgetstack.o \
	linux_gcc_debug/moc_ContextExplorer.o \
	linux_gcc_debug/moc_ContextExplorerDialog.o \
	linux_gcc_debug/moc_cQtKeyboardAlpha.o \
	linux_gcc_debug/moc_cQtKeypadNumeric.o \
	linux_gcc_debug/moc_cactiondialog.o \
	linux_gcc_debug/moc_cactvalue.o \
	linux_gcc_debug/moc_calarmwidget.o \
	linux_gcc_debug/moc_cappframe.o \
	linux_gcc_debug/moc_cbuttongroup.o \
	linux_gcc_debug/moc_ccheckbox.o \
	linux_gcc_debug/moc_ccombobox.o \
	linux_gcc_debug/moc_ccomplistview.o \
	linux_gcc_debug/moc_ccomposedstack.o \
	linux_gcc_debug/moc_ccoordsystem.o \
	linux_gcc_debug/moc_cdate.o \
	linux_gcc_debug/moc_cdatetime.o \
	linux_gcc_debug/moc_cdirectory.o \
	linux_gcc_debug/moc_cfixtext.o \
	linux_gcc_debug/moc_cframe.o \
	linux_gcc_debug/moc_cgraphic.o \
	linux_gcc_debug/moc_cgroupbox.o \
	linux_gcc_debug/moc_cgroupselectbutton.o \
	linux_gcc_debug/moc_cindreqvalue.o \
	linux_gcc_debug/moc_cinfolabel.o \
	linux_gcc_debug/moc_clistview.o \
	linux_gcc_debug/moc_cpage.o \
	linux_gcc_debug/moc_cprocgraphic.o \
	linux_gcc_debug/moc_cprogressbar.o \
	linux_gcc_debug/moc_cpublicdialog.o \
	linux_gcc_debug/moc_cpushbutton.o \
	linux_gcc_debug/moc_cradiobutton.o \
	linux_gcc_debug/moc_creqvalue.o \
	linux_gcc_debug/moc_cringgraphic.o \
	linux_gcc_debug/moc_cscrollbar.o \
	linux_gcc_debug/moc_csimplegraphic.o \
	linux_gcc_debug/moc_cslider.o \
	linux_gcc_debug/moc_cspinbox.o \
	linux_gcc_debug/moc_cstartupform.o \
	linux_gcc_debug/moc_cstatebutton.o \
	linux_gcc_debug/moc_ctable.o \
	linux_gcc_debug/moc_ctabwidget.o \
	linux_gcc_debug/moc_ctextedit.o \
	linux_gcc_debug/moc_ctime.o \
	linux_gcc_debug/moc_ctoolbutton.o \
	linux_gcc_debug/moc_cvardimension.o \
	linux_gcc_debug/moc_cvideo.o \
	linux_gcc_debug/moc_cvirtualkeyboard.o \
	linux_gcc_debug/moc_cwidget.o \
	linux_gcc_debug/moc_cwidgetcomm.o \
	linux_gcc_debug/moc_cwidgetstack.o \
	linux_gcc_debug/moc_qt_keyboard.o \
	linux_gcc_debug/moc_qt_keyboard_button.o \
	linux_gcc_debug/moc_qt_keyboard_input.o \
	linux_gcc_debug/moc_qt_keyboard_layout.o \
	linux_gcc_debug/moc_qt_keyboard_layout_german.o \
	linux_gcc_debug/moc_qt_keyboard_layout_standard.o \
	linux_gcc_debug/moc_qt_keyboardalpha.o \
	linux_gcc_debug/moc_qt_keypadnumeric.o \
	linux_gcc_debug/moc_touch_style.o \
	linux_gcc_debug/pluginlog.o \
	linux_gcc_debug/qt_keyboard.o \
	linux_gcc_debug/qt_keyboard_button.o \
	linux_gcc_debug/qt_keyboard_input.o \
	linux_gcc_debug/qt_keyboard_layout.o \
	linux_gcc_debug/qt_keyboard_layout_german.o \
	linux_gcc_debug/qt_keyboard_layout_standard.o \
	linux_gcc_debug/qt_keyboardalpha.o \
	linux_gcc_debug/qt_keypadnumeric.o \
	linux_gcc_debug/qt_navigation_widget.o \
	linux_gcc_debug/qt_number_validator.o \
	linux_gcc_debug/qt_property_widget.o \
	linux_gcc_debug/qt_string_validator.o \
	linux_gcc_debug/touch_style.o

.PHONY: linux_gcc_debug all clean


dependencies:
	$(make) -C ../ccs -flinux_gcc_debug.mk all

clean:
	-rm $(A_TARGETS)

linux_gcc_debug/libguiframework.a: $(A_TARGETS)
	$(lib)

all: dependencies linux_gcc_debug $(A_TARGETS) linux_gcc_debug/libguiframework.a

linux_gcc_debug: linux_gcc_debug.mk
	$(mkdir) $@

linux_gcc_debug/moc_ContextExplorer.o: linux_gcc_debug/moc_ContextExplorer.cpp
	$(cpp)

linux_gcc_debug/moc_cactiondialog.o: linux_gcc_debug/moc_cactiondialog.cpp
	$(cpp)

linux_gcc_debug/moc_cactvalue.o: linux_gcc_debug/moc_cactvalue.cpp
	$(cpp)

linux_gcc_debug/moc_calarmwidget.o: linux_gcc_debug/moc_calarmwidget.cpp
	$(cpp)

linux_gcc_debug/moc_cappframe.o: linux_gcc_debug/moc_cappframe.cpp
	$(cpp)

linux_gcc_debug/moc_cbuttongroup.o: linux_gcc_debug/moc_cbuttongroup.cpp
	$(cpp)

linux_gcc_debug/moc_ccheckbox.o: linux_gcc_debug/moc_ccheckbox.cpp
	$(cpp)

linux_gcc_debug/moc_ccombobox.o: linux_gcc_debug/moc_ccombobox.cpp
	$(cpp)

linux_gcc_debug/moc_ccomplistview.o: linux_gcc_debug/moc_ccomplistview.cpp
	$(cpp)

linux_gcc_debug/moc_ccomposedstack.o: linux_gcc_debug/moc_ccomposedstack.cpp
	$(cpp)

linux_gcc_debug/moc_ccoordsystem.o: linux_gcc_debug/moc_ccoordsystem.cpp
	$(cpp)

linux_gcc_debug/moc_cdate.o: linux_gcc_debug/moc_cdate.cpp
	$(cpp)

linux_gcc_debug/moc_cdatetime.o: linux_gcc_debug/moc_cdatetime.cpp
	$(cpp)

linux_gcc_debug/moc_cdirectory.o: linux_gcc_debug/moc_cdirectory.cpp
	$(cpp)

linux_gcc_debug/moc_cfixtext.o: linux_gcc_debug/moc_cfixtext.cpp
	$(cpp)

linux_gcc_debug/moc_cframe.o: linux_gcc_debug/moc_cframe.cpp
	$(cpp)

linux_gcc_debug/moc_cgraphic.o: linux_gcc_debug/moc_cgraphic.cpp
	$(cpp)

linux_gcc_debug/moc_cgroupbox.o: linux_gcc_debug/moc_cgroupbox.cpp
	$(cpp)

linux_gcc_debug/moc_cgroupselectbutton.o: linux_gcc_debug/moc_cgroupselectbutton.cpp
	$(cpp)

linux_gcc_debug/moc_cindreqvalue.o: linux_gcc_debug/moc_cindreqvalue.cpp
	$(cpp)

linux_gcc_debug/moc_cinfolabel.o: linux_gcc_debug/moc_cinfolabel.cpp
	$(cpp)

linux_gcc_debug/moc_clistview.o: linux_gcc_debug/moc_clistview.cpp
	$(cpp)

linux_gcc_debug/moc_cpage.o: linux_gcc_debug/moc_cpage.cpp
	$(cpp)

linux_gcc_debug/moc_cprocgraphic.o: linux_gcc_debug/moc_cprocgraphic.cpp
	$(cpp)

linux_gcc_debug/moc_cprogressbar.o: linux_gcc_debug/moc_cprogressbar.cpp
	$(cpp)

linux_gcc_debug/moc_cpushbutton.o: linux_gcc_debug/moc_cpushbutton.cpp
	$(cpp)

linux_gcc_debug/moc_cradiobutton.o: linux_gcc_debug/moc_cradiobutton.cpp
	$(cpp)

linux_gcc_debug/moc_creqvalue.o: linux_gcc_debug/moc_creqvalue.cpp
	$(cpp)

linux_gcc_debug/moc_cringgraphic.o: linux_gcc_debug/moc_cringgraphic.cpp
	$(cpp)

linux_gcc_debug/moc_cscrollbar.o: linux_gcc_debug/moc_cscrollbar.cpp
	$(cpp)

linux_gcc_debug/moc_csimplegraphic.o: linux_gcc_debug/moc_csimplegraphic.cpp
	$(cpp)

linux_gcc_debug/moc_cslider.o: linux_gcc_debug/moc_cslider.cpp
	$(cpp)

linux_gcc_debug/moc_cspinbox.o: linux_gcc_debug/moc_cspinbox.cpp
	$(cpp)

linux_gcc_debug/moc_cstartupform.o: linux_gcc_debug/moc_cstartupform.cpp
	$(cpp)

linux_gcc_debug/moc_cstatebutton.o: linux_gcc_debug/moc_cstatebutton.cpp
	$(cpp)

linux_gcc_debug/moc_ctable.o: linux_gcc_debug/moc_ctable.cpp
	$(cpp)

linux_gcc_debug/moc_ctabwidget.o: linux_gcc_debug/moc_ctabwidget.cpp
	$(cpp)

linux_gcc_debug/moc_ctextedit.o: linux_gcc_debug/moc_ctextedit.cpp
	$(cpp)

linux_gcc_debug/moc_ctime.o: linux_gcc_debug/moc_ctime.cpp
	$(cpp)

linux_gcc_debug/moc_ctoolbutton.o: linux_gcc_debug/moc_ctoolbutton.cpp
	$(cpp)

linux_gcc_debug/moc_cvardimension.o: linux_gcc_debug/moc_cvardimension.cpp
	$(cpp)

linux_gcc_debug/moc_cvideo.o: linux_gcc_debug/moc_cvideo.cpp
	$(cpp)

linux_gcc_debug/moc_cvirtualkeyboard.o: linux_gcc_debug/moc_cvirtualkeyboard.cpp
	$(cpp)

linux_gcc_debug/moc_cwidget.o: linux_gcc_debug/moc_cwidget.cpp
	$(cpp)

linux_gcc_debug/moc_cwidgetstack.o: linux_gcc_debug/moc_cwidgetstack.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_german.o: linux_gcc_debug/moc_qt_keyboard_layout_german.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_standard.o: linux_gcc_debug/moc_qt_keyboard_layout_standard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboardalpha.o: linux_gcc_debug/moc_qt_keyboardalpha.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keypadnumeric.o: linux_gcc_debug/moc_qt_keypadnumeric.cpp
	$(cpp)

linux_gcc_debug/ContextExplorer.o: linux_gcc_debug/ContextExplorer.cpp
	$(cpp)

linux_gcc_debug/moc_ContextExplorer.cpp: linux_gcc_debug/ContextExplorer.h
	$(QTDIR)/bin/moc linux_gcc_debug/ContextExplorer.h -olinux_gcc_debug/moc_ContextExplorer.cpp

linux_gcc_debug/moc_cactiondialog.cpp: linux_gcc_debug/cactiondialog.h
	$(QTDIR)/bin/moc linux_gcc_debug/cactiondialog.h -olinux_gcc_debug/moc_cactiondialog.cpp

linux_gcc_debug/moc_cactvalue.cpp: linux_gcc_debug/cactvalue.h
	$(QTDIR)/bin/moc linux_gcc_debug/cactvalue.h -olinux_gcc_debug/moc_cactvalue.cpp

linux_gcc_debug/moc_calarmwidget.cpp: linux_gcc_debug/calarmwidget.h
	$(QTDIR)/bin/moc linux_gcc_debug/calarmwidget.h -olinux_gcc_debug/moc_calarmwidget.cpp

linux_gcc_debug/moc_cappframe.cpp: linux_gcc_debug/cappframe.h
	$(QTDIR)/bin/moc linux_gcc_debug/cappframe.h -olinux_gcc_debug/moc_cappframe.cpp

linux_gcc_debug/moc_cbuttongroup.cpp: linux_gcc_debug/cbuttongroup.h
	$(QTDIR)/bin/moc linux_gcc_debug/cbuttongroup.h -olinux_gcc_debug/moc_cbuttongroup.cpp

linux_gcc_debug/moc_ccheckbox.cpp: linux_gcc_debug/ccheckbox.h
	$(QTDIR)/bin/moc linux_gcc_debug/ccheckbox.h -olinux_gcc_debug/moc_ccheckbox.cpp

linux_gcc_debug/moc_ccombobox.cpp: linux_gcc_debug/ccombobox.h
	$(QTDIR)/bin/moc linux_gcc_debug/ccombobox.h -olinux_gcc_debug/moc_ccombobox.cpp

linux_gcc_debug/moc_ccomplistview.cpp: linux_gcc_debug/ccomplistview.h
	$(QTDIR)/bin/moc linux_gcc_debug/ccomplistview.h -olinux_gcc_debug/moc_ccomplistview.cpp

linux_gcc_debug/moc_ccomposedstack.cpp: linux_gcc_debug/ccomposedstack.h
	$(QTDIR)/bin/moc linux_gcc_debug/ccomposedstack.h -olinux_gcc_debug/moc_ccomposedstack.cpp

linux_gcc_debug/moc_ccoordsystem.cpp: linux_gcc_debug/ccoordsystem.h
	$(QTDIR)/bin/moc linux_gcc_debug/ccoordsystem.h -olinux_gcc_debug/moc_ccoordsystem.cpp

linux_gcc_debug/moc_cdate.cpp: linux_gcc_debug/cdate.h
	$(QTDIR)/bin/moc linux_gcc_debug/cdate.h -olinux_gcc_debug/moc_cdate.cpp

linux_gcc_debug/moc_cdatetime.cpp: linux_gcc_debug/cdatetime.h
	$(QTDIR)/bin/moc linux_gcc_debug/cdatetime.h -olinux_gcc_debug/moc_cdatetime.cpp

linux_gcc_debug/moc_cdirectory.cpp: linux_gcc_debug/cdirectory.h
	$(QTDIR)/bin/moc linux_gcc_debug/cdirectory.h -olinux_gcc_debug/moc_cdirectory.cpp

linux_gcc_debug/moc_cfixtext.cpp: linux_gcc_debug/cfixtext.h
	$(QTDIR)/bin/moc linux_gcc_debug/cfixtext.h -olinux_gcc_debug/moc_cfixtext.cpp

linux_gcc_debug/moc_cframe.cpp: linux_gcc_debug/cframe.h
	$(QTDIR)/bin/moc linux_gcc_debug/cframe.h -olinux_gcc_debug/moc_cframe.cpp

linux_gcc_debug/moc_cgraphic.cpp: linux_gcc_debug/cgraphic.h
	$(QTDIR)/bin/moc linux_gcc_debug/cgraphic.h -olinux_gcc_debug/moc_cgraphic.cpp

linux_gcc_debug/moc_cgroupbox.cpp: linux_gcc_debug/cgroupbox.h
	$(QTDIR)/bin/moc linux_gcc_debug/cgroupbox.h -olinux_gcc_debug/moc_cgroupbox.cpp

linux_gcc_debug/moc_cgroupselectbutton.cpp: linux_gcc_debug/cgroupselectbutton.h
	$(QTDIR)/bin/moc linux_gcc_debug/cgroupselectbutton.h -olinux_gcc_debug/moc_cgroupselectbutton.cpp

linux_gcc_debug/moc_cindreqvalue.cpp: linux_gcc_debug/cindreqvalue.h
	$(QTDIR)/bin/moc linux_gcc_debug/cindreqvalue.h -olinux_gcc_debug/moc_cindreqvalue.cpp

linux_gcc_debug/moc_cinfolabel.cpp: linux_gcc_debug/cinfolabel.h
	$(QTDIR)/bin/moc linux_gcc_debug/cinfolabel.h -olinux_gcc_debug/moc_cinfolabel.cpp

linux_gcc_debug/moc_clistview.cpp: linux_gcc_debug/clistview.h
	$(QTDIR)/bin/moc linux_gcc_debug/clistview.h -olinux_gcc_debug/moc_clistview.cpp

linux_gcc_debug/moc_cpage.cpp: linux_gcc_debug/cpage.h
	$(QTDIR)/bin/moc linux_gcc_debug/cpage.h -olinux_gcc_debug/moc_cpage.cpp

linux_gcc_debug/moc_cprocgraphic.cpp: linux_gcc_debug/cprocgraphic.h
	$(QTDIR)/bin/moc linux_gcc_debug/cprocgraphic.h -olinux_gcc_debug/moc_cprocgraphic.cpp

linux_gcc_debug/moc_cprogressbar.cpp: linux_gcc_debug/cprogressbar.h
	$(QTDIR)/bin/moc linux_gcc_debug/cprogressbar.h -olinux_gcc_debug/moc_cprogressbar.cpp

linux_gcc_debug/moc_cpushbutton.cpp: linux_gcc_debug/cpushbutton.h
	$(QTDIR)/bin/moc linux_gcc_debug/cpushbutton.h -olinux_gcc_debug/moc_cpushbutton.cpp

linux_gcc_debug/moc_cradiobutton.cpp: linux_gcc_debug/cradiobutton.h
	$(QTDIR)/bin/moc linux_gcc_debug/cradiobutton.h -olinux_gcc_debug/moc_cradiobutton.cpp

linux_gcc_debug/moc_creqvalue.cpp: linux_gcc_debug/creqvalue.h
	$(QTDIR)/bin/moc linux_gcc_debug/creqvalue.h -olinux_gcc_debug/moc_creqvalue.cpp

linux_gcc_debug/moc_cringgraphic.cpp: linux_gcc_debug/cringgraphic.h
	$(QTDIR)/bin/moc linux_gcc_debug/cringgraphic.h -olinux_gcc_debug/moc_cringgraphic.cpp

linux_gcc_debug/moc_cscrollbar.cpp: linux_gcc_debug/cscrollbar.h
	$(QTDIR)/bin/moc linux_gcc_debug/cscrollbar.h -olinux_gcc_debug/moc_cscrollbar.cpp

linux_gcc_debug/moc_csimplegraphic.cpp: linux_gcc_debug/csimplegraphic.h
	$(QTDIR)/bin/moc linux_gcc_debug/csimplegraphic.h -olinux_gcc_debug/moc_csimplegraphic.cpp

linux_gcc_debug/moc_cslider.cpp: linux_gcc_debug/cslider.h
	$(QTDIR)/bin/moc linux_gcc_debug/cslider.h -olinux_gcc_debug/moc_cslider.cpp

linux_gcc_debug/moc_cspinbox.cpp: linux_gcc_debug/cspinbox.h
	$(QTDIR)/bin/moc linux_gcc_debug/cspinbox.h -olinux_gcc_debug/moc_cspinbox.cpp

linux_gcc_debug/moc_cstartupform.cpp: linux_gcc_debug/cstartupform.h
	$(QTDIR)/bin/moc linux_gcc_debug/cstartupform.h -olinux_gcc_debug/moc_cstartupform.cpp

linux_gcc_debug/moc_cstatebutton.cpp: linux_gcc_debug/cstatebutton.h
	$(QTDIR)/bin/moc linux_gcc_debug/cstatebutton.h -olinux_gcc_debug/moc_cstatebutton.cpp

linux_gcc_debug/moc_ctable.cpp: linux_gcc_debug/ctable.h
	$(QTDIR)/bin/moc linux_gcc_debug/ctable.h -olinux_gcc_debug/moc_ctable.cpp

linux_gcc_debug/moc_ctabwidget.cpp: linux_gcc_debug/ctabwidget.h
	$(QTDIR)/bin/moc linux_gcc_debug/ctabwidget.h -olinux_gcc_debug/moc_ctabwidget.cpp

linux_gcc_debug/moc_ctextedit.cpp: linux_gcc_debug/ctextedit.h
	$(QTDIR)/bin/moc linux_gcc_debug/ctextedit.h -olinux_gcc_debug/moc_ctextedit.cpp

linux_gcc_debug/moc_ctime.cpp: linux_gcc_debug/ctime.h
	$(QTDIR)/bin/moc linux_gcc_debug/ctime.h -olinux_gcc_debug/moc_ctime.cpp

linux_gcc_debug/moc_ctoolbutton.cpp: linux_gcc_debug/ctoolbutton.h
	$(QTDIR)/bin/moc linux_gcc_debug/ctoolbutton.h -olinux_gcc_debug/moc_ctoolbutton.cpp

linux_gcc_debug/moc_cvardimension.cpp: linux_gcc_debug/cvardimension.h
	$(QTDIR)/bin/moc linux_gcc_debug/cvardimension.h -olinux_gcc_debug/moc_cvardimension.cpp

linux_gcc_debug/moc_cvideo.cpp: linux_gcc_debug/cvideo.h
	$(QTDIR)/bin/moc linux_gcc_debug/cvideo.h -olinux_gcc_debug/moc_cvideo.cpp

linux_gcc_debug/moc_cvirtualkeyboard.cpp: linux_gcc_debug/cvirtualkeyboard.h
	$(QTDIR)/bin/moc linux_gcc_debug/cvirtualkeyboard.h -olinux_gcc_debug/moc_cvirtualkeyboard.cpp

linux_gcc_debug/moc_cwidget.cpp: linux_gcc_debug/cwidget.h
	$(QTDIR)/bin/moc linux_gcc_debug/cwidget.h -olinux_gcc_debug/moc_cwidget.cpp

linux_gcc_debug/moc_cwidgetstack.cpp: linux_gcc_debug/cwidgetstack.h
	$(QTDIR)/bin/moc linux_gcc_debug/cwidgetstack.h -olinux_gcc_debug/moc_cwidgetstack.cpp

linux_gcc_debug/moc_ContextExplorerDialog.o: linux_gcc_debug/moc_ContextExplorerDialog.cpp
	$(cpp)

linux_gcc_debug/moc_cQtKeyboardAlpha.o: linux_gcc_debug/moc_cQtKeyboardAlpha.cpp
	$(cpp)

linux_gcc_debug/moc_cQtKeypadNumeric.o: linux_gcc_debug/moc_cQtKeypadNumeric.cpp
	$(cpp)

linux_gcc_debug/moc_cpublicdialog.o: linux_gcc_debug/moc_cpublicdialog.cpp
	$(cpp)

linux_gcc_debug/moc_cwidgetcomm.o: linux_gcc_debug/moc_cwidgetcomm.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard.o: linux_gcc_debug/moc_qt_keyboard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_button.o: linux_gcc_debug/moc_qt_keyboard_button.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_input.o: linux_gcc_debug/moc_qt_keyboard_input.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout.o: linux_gcc_debug/moc_qt_keyboard_layout.cpp
	$(cpp)

linux_gcc_debug/moc_touch_style.o: linux_gcc_debug/moc_touch_style.cpp
	$(cpp)

linux_gcc_debug/qt_keyboard_layout_german.o: linux_gcc_debug/qt_keyboard_layout_german.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_german.cpp: linux_gcc_debug/qt_keyboard_layout_german.h
	$(QTDIR)/bin/moc linux_gcc_debug/qt_keyboard_layout_german.h -olinux_gcc_debug/moc_qt_keyboard_layout_german.cpp

linux_gcc_debug/qt_keyboard_layout_standard.o: linux_gcc_debug/qt_keyboard_layout_standard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout_standard.cpp: linux_gcc_debug/qt_keyboard_layout_standard.h
	$(QTDIR)/bin/moc linux_gcc_debug/qt_keyboard_layout_standard.h -olinux_gcc_debug/moc_qt_keyboard_layout_standard.cpp

linux_gcc_debug/qt_keyboardalpha.o: linux_gcc_debug/qt_keyboardalpha.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboardalpha.cpp: linux_gcc_debug/qt_keyboardalpha.h
	$(QTDIR)/bin/moc linux_gcc_debug/qt_keyboardalpha.h -olinux_gcc_debug/moc_qt_keyboardalpha.cpp

linux_gcc_debug/qt_keypadnumeric.o: linux_gcc_debug/qt_keypadnumeric.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keypadnumeric.cpp: linux_gcc_debug/qt_keypadnumeric.h
	$(QTDIR)/bin/moc linux_gcc_debug/qt_keypadnumeric.h -olinux_gcc_debug/moc_qt_keypadnumeric.cpp

linux_gcc_debug/ContextExplorer.cpp: ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorer.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorer.ui -o linux_gcc_debug/ContextExplorer.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorer.ui -i linux_gcc_debug/ContextExplorer.h -o linux_gcc_debug/ContextExplorer.cpp
linux_gcc_debug/ContextExplorer.h: ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorer.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorer.ui -o linux_gcc_debug/ContextExplorer.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorer.ui -i linux_gcc_debug/ContextExplorer.h -o linux_gcc_debug/ContextExplorer.cpp

linux_gcc_debug/ContextExplorerDialog.o: ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorerDialog.cpp
	$(cpp)

linux_gcc_debug/moc_ContextExplorerDialog.cpp: ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorerDialog.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Dialogs/ContextExplorerDialog.h -olinux_gcc_debug/moc_ContextExplorerDialog.cpp

linux_gcc_debug/cCCSInterface.o: ../../../Src/GUIFramework/Interface/cCCSInterface.cpp
	$(cpp)

linux_gcc_debug/cContextChooser.o: ../../../Src/GUIFramework/Interface/cContextChooser.cpp
	$(cpp)

linux_gcc_debug/cContextExplorer.o: ../../../Src/GUIFramework/QTFramework/cContextExplorer.cpp
	$(cpp)

linux_gcc_debug/cFormRequest.o: ../../../Src/GUIFramework/QTFramework/HTML/cFormRequest.cpp
	$(cpp)

linux_gcc_debug/cGroup.o: ../../../Src/GUIFramework/cGroup.cpp
	$(cpp)

linux_gcc_debug/cGroupList.o: ../../../Src/GUIFramework/cGroupList.cpp
	$(cpp)

linux_gcc_debug/cHTMLDocument.o: ../../../Src/GUIFramework/QTFramework/HTML/cHTMLDocument.cpp
	$(cpp)

linux_gcc_debug/cHTMLElement.o: ../../../Src/GUIFramework/QTFramework/HTML/cHTMLElement.cpp
	$(cpp)

linux_gcc_debug/cHelpInterface.o: ../../../Src/GUIFramework/QTFramework/cHelpInterface.cpp
	$(cpp)

linux_gcc_debug/cNode.o: ../../../Src/GUIFramework/cNode.cpp
	$(cpp)

linux_gcc_debug/cNodeList.o: ../../../Src/GUIFramework/cNodeList.cpp
	$(cpp)

linux_gcc_debug/cQTUserInterface.o: ../../../Src/GUIFramework/QTFramework/cQTUserInterface.cpp
	$(cpp)

linux_gcc_debug/cQtKeyboardAlpha.o: ../../../Src/GUIFramework/QTFramework/Keypads/cQtKeyboardAlpha.cpp
	$(cpp)

linux_gcc_debug/moc_cQtKeyboardAlpha.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/cQtKeyboardAlpha.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/cQtKeyboardAlpha.h -olinux_gcc_debug/moc_cQtKeyboardAlpha.cpp

linux_gcc_debug/cQtKeypadNumeric.o: ../../../Src/GUIFramework/QTFramework/Keypads/cQtKeypadNumeric.cpp
	$(cpp)

linux_gcc_debug/moc_cQtKeypadNumeric.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/cQtKeypadNumeric.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/cQtKeypadNumeric.h -olinux_gcc_debug/moc_cQtKeypadNumeric.cpp

linux_gcc_debug/cSyncView.o: ../../../Src/GUIFramework/QTFramework/cSyncView.cpp
	$(cpp)

linux_gcc_debug/cUserInterface.o: ../../../Src/GUIFramework/cUserInterface.cpp
	$(cpp)

linux_gcc_debug/cactiondialog.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cactiondialog.cpp
	$(cpp)

linux_gcc_debug/cactiondialog.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cactiondialog.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cactiondialog.h ../../../Src/GUIFramework/QTFramework/CWidgets/cactiondialog.pp

linux_gcc_debug/cactvalue.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cactvalue.cpp
	$(cpp)

linux_gcc_debug/cactvalue.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cactvalue.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cactvalue.h ../../../Src/GUIFramework/QTFramework/CWidgets/cactvalue.pp

linux_gcc_debug/calarmwidget.o: ../../../Src/GUIFramework/QTFramework/CWidgets/calarmwidget.cpp
	$(cpp)

linux_gcc_debug/calarmwidget.h: ../../../Src/GUIFramework/QTFramework/CWidgets/calarmwidget.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/calarmwidget.h ../../../Src/GUIFramework/QTFramework/CWidgets/calarmwidget.pp

linux_gcc_debug/cappframe.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cappframe.cpp
	$(cpp)

linux_gcc_debug/cappframe.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cappframe.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cappframe.h ../../../Src/GUIFramework/QTFramework/CWidgets/cappframe.pp

linux_gcc_debug/casyncfunction.o: ../../../Src/GUIFramework/QTFramework/CWidgets/casyncfunction.cpp
	$(cpp)

linux_gcc_debug/cbuttongroup.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cbuttongroup.cpp
	$(cpp)

linux_gcc_debug/cbuttongroup.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cbuttongroup.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cbuttongroup.h ../../../Src/GUIFramework/QTFramework/CWidgets/cbuttongroup.pp

linux_gcc_debug/ccheckbox.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ccheckbox.cpp
	$(cpp)

linux_gcc_debug/ccheckbox.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ccheckbox.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ccheckbox.h ../../../Src/GUIFramework/QTFramework/CWidgets/ccheckbox.pp

linux_gcc_debug/ccombobox.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ccombobox.cpp
	$(cpp)

linux_gcc_debug/ccombobox.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ccombobox.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ccombobox.h ../../../Src/GUIFramework/QTFramework/CWidgets/ccombobox.pp

linux_gcc_debug/ccomplistview.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ccomplistview.cpp
	$(cpp)

linux_gcc_debug/ccomplistview.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ccomplistview.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ccomplistview.h ../../../Src/GUIFramework/QTFramework/CWidgets/ccomplistview.pp

linux_gcc_debug/ccomposedstack.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ccomposedstack.cpp
	$(cpp)

linux_gcc_debug/ccomposedstack.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ccomposedstack.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ccomposedstack.h ../../../Src/GUIFramework/QTFramework/CWidgets/ccomposedstack.pp

linux_gcc_debug/ccoordsystem.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ccoordsystem.cpp
	$(cpp)

linux_gcc_debug/ccoordsystem.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ccoordsystem.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ccoordsystem.h ../../../Src/GUIFramework/QTFramework/CWidgets/ccoordsystem.pp

linux_gcc_debug/cdate.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cdate.cpp
	$(cpp)

linux_gcc_debug/cdate.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cdate.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cdate.h ../../../Src/GUIFramework/QTFramework/CWidgets/cdate.pp

linux_gcc_debug/cdatetime.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cdatetime.cpp
	$(cpp)

linux_gcc_debug/cdatetime.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cdatetime.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cdatetime.h ../../../Src/GUIFramework/QTFramework/CWidgets/cdatetime.pp

linux_gcc_debug/cdirectory.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cdirectory.cpp
	$(cpp)

linux_gcc_debug/cdirectory.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cdirectory.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cdirectory.h ../../../Src/GUIFramework/QTFramework/CWidgets/cdirectory.pp

linux_gcc_debug/cfixtext.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cfixtext.cpp
	$(cpp)

linux_gcc_debug/cfixtext.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cfixtext.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cfixtext.h ../../../Src/GUIFramework/QTFramework/CWidgets/cfixtext.pp

linux_gcc_debug/cframe.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cframe.cpp
	$(cpp)

linux_gcc_debug/cframe.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cframe.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cframe.h ../../../Src/GUIFramework/QTFramework/CWidgets/cframe.pp

linux_gcc_debug/cgraphic.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cgraphic.cpp
	$(cpp)

linux_gcc_debug/cgraphic.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cgraphic.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cgraphic.h ../../../Src/GUIFramework/QTFramework/CWidgets/cgraphic.pp

linux_gcc_debug/cgroupbox.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cgroupbox.cpp
	$(cpp)

linux_gcc_debug/cgroupbox.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cgroupbox.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cgroupbox.h ../../../Src/GUIFramework/QTFramework/CWidgets/cgroupbox.pp

linux_gcc_debug/cgroupselectbutton.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cgroupselectbutton.cpp
	$(cpp)

linux_gcc_debug/cgroupselectbutton.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cgroupselectbutton.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cgroupselectbutton.h ../../../Src/GUIFramework/QTFramework/CWidgets/cgroupselectbutton.pp

linux_gcc_debug/cguievents.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cguievents.cpp
	$(cpp)

linux_gcc_debug/cindreqvalue.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cindreqvalue.cpp
	$(cpp)

linux_gcc_debug/cindreqvalue.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cindreqvalue.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cindreqvalue.h ../../../Src/GUIFramework/QTFramework/CWidgets/cindreqvalue.pp

linux_gcc_debug/cinfolabel.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cinfolabel.cpp
	$(cpp)

linux_gcc_debug/cinfolabel.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cinfolabel.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cinfolabel.h ../../../Src/GUIFramework/QTFramework/CWidgets/cinfolabel.pp

linux_gcc_debug/cinput.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cinput.cpp
	$(cpp)

linux_gcc_debug/clistview.o: ../../../Src/GUIFramework/QTFramework/CWidgets/clistview.cpp
	$(cpp)

linux_gcc_debug/clistview.h: ../../../Src/GUIFramework/QTFramework/CWidgets/clistview.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/clistview.h ../../../Src/GUIFramework/QTFramework/CWidgets/clistview.pp

linux_gcc_debug/cpage.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cpage.cpp
	$(cpp)

linux_gcc_debug/cpage.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cpage.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cpage.h ../../../Src/GUIFramework/QTFramework/CWidgets/cpage.pp

linux_gcc_debug/cpaintutils.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cpaintutils.cpp
	$(cpp)

linux_gcc_debug/cprocgraphic.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cprocgraphic.cpp
	$(cpp)

linux_gcc_debug/cprocgraphic.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cprocgraphic.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cprocgraphic.h ../../../Src/GUIFramework/QTFramework/CWidgets/cprocgraphic.pp

linux_gcc_debug/cprogressbar.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cprogressbar.cpp
	$(cpp)

linux_gcc_debug/cprogressbar.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cprogressbar.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cprogressbar.h ../../../Src/GUIFramework/QTFramework/CWidgets/cprogressbar.pp

linux_gcc_debug/moc_cpublicdialog.cpp: ../../../Src/GUIFramework/QTFramework/CWidgets/cpublicdialog.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/CWidgets/cpublicdialog.h -olinux_gcc_debug/moc_cpublicdialog.cpp

linux_gcc_debug/cpushbutton.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cpushbutton.cpp
	$(cpp)

linux_gcc_debug/cpushbutton.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cpushbutton.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cpushbutton.h ../../../Src/GUIFramework/QTFramework/CWidgets/cpushbutton.pp

linux_gcc_debug/cradiobutton.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cradiobutton.cpp
	$(cpp)

linux_gcc_debug/cradiobutton.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cradiobutton.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cradiobutton.h ../../../Src/GUIFramework/QTFramework/CWidgets/cradiobutton.pp

linux_gcc_debug/creqvalue.o: ../../../Src/GUIFramework/QTFramework/CWidgets/creqvalue.cpp
	$(cpp)

linux_gcc_debug/creqvalue.h: ../../../Src/GUIFramework/QTFramework/CWidgets/creqvalue.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/creqvalue.h ../../../Src/GUIFramework/QTFramework/CWidgets/creqvalue.pp

linux_gcc_debug/cringgraphic.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cringgraphic.cpp
	$(cpp)

linux_gcc_debug/cringgraphic.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cringgraphic.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cringgraphic.h ../../../Src/GUIFramework/QTFramework/CWidgets/cringgraphic.pp

linux_gcc_debug/crubberband.o: ../../../Src/GUIFramework/QTFramework/CWidgets/crubberband.cpp
	$(cpp)

linux_gcc_debug/cscrollbar.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cscrollbar.cpp
	$(cpp)

linux_gcc_debug/cscrollbar.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cscrollbar.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cscrollbar.h ../../../Src/GUIFramework/QTFramework/CWidgets/cscrollbar.pp

linux_gcc_debug/csignalmanager.o: ../../../Src/GUIFramework/QTFramework/CWidgets/csignalmanager.cpp
	$(cpp)

linux_gcc_debug/csimplegraphic.o: ../../../Src/GUIFramework/QTFramework/CWidgets/csimplegraphic.cpp
	$(cpp)

linux_gcc_debug/csimplegraphic.h: ../../../Src/GUIFramework/QTFramework/CWidgets/csimplegraphic.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/csimplegraphic.h ../../../Src/GUIFramework/QTFramework/CWidgets/csimplegraphic.pp

linux_gcc_debug/cslider.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cslider.cpp
	$(cpp)

linux_gcc_debug/cslider.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cslider.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cslider.h ../../../Src/GUIFramework/QTFramework/CWidgets/cslider.pp

linux_gcc_debug/cspinbox.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cspinbox.cpp
	$(cpp)

linux_gcc_debug/cspinbox.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cspinbox.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cspinbox.h ../../../Src/GUIFramework/QTFramework/CWidgets/cspinbox.pp

linux_gcc_debug/cstartupform.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cstartupform.cpp
	$(cpp)

linux_gcc_debug/cstartupform.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cstartupform.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cstartupform.h ../../../Src/GUIFramework/QTFramework/CWidgets/cstartupform.pp

linux_gcc_debug/cstatebutton.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cstatebutton.cpp
	$(cpp)

linux_gcc_debug/cstatebutton.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cstatebutton.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cstatebutton.h ../../../Src/GUIFramework/QTFramework/CWidgets/cstatebutton.pp

linux_gcc_debug/ctable.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ctable.cpp
	$(cpp)

linux_gcc_debug/ctable.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ctable.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ctable.h ../../../Src/GUIFramework/QTFramework/CWidgets/ctable.pp

linux_gcc_debug/ctabwidget.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ctabwidget.cpp
	$(cpp)

linux_gcc_debug/ctabwidget.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ctabwidget.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ctabwidget.h ../../../Src/GUIFramework/QTFramework/CWidgets/ctabwidget.pp

linux_gcc_debug/ctextedit.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ctextedit.cpp
	$(cpp)

linux_gcc_debug/ctextedit.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ctextedit.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ctextedit.h ../../../Src/GUIFramework/QTFramework/CWidgets/ctextedit.pp

linux_gcc_debug/ctime.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ctime.cpp
	$(cpp)

linux_gcc_debug/ctime.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ctime.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ctime.h ../../../Src/GUIFramework/QTFramework/CWidgets/ctime.pp

linux_gcc_debug/ctoolbutton.o: ../../../Src/GUIFramework/QTFramework/CWidgets/ctoolbutton.cpp
	$(cpp)

linux_gcc_debug/ctoolbutton.h: ../../../Src/GUIFramework/QTFramework/CWidgets/ctoolbutton.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/ctoolbutton.h ../../../Src/GUIFramework/QTFramework/CWidgets/ctoolbutton.pp

linux_gcc_debug/cvardimension.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cvardimension.cpp
	$(cpp)

linux_gcc_debug/cvardimension.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cvardimension.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cvardimension.h ../../../Src/GUIFramework/QTFramework/CWidgets/cvardimension.pp

linux_gcc_debug/cvideo.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cvideo.cpp
	$(cpp)

linux_gcc_debug/cvideo.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cvideo.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cvideo.h ../../../Src/GUIFramework/QTFramework/CWidgets/cvideo.pp

linux_gcc_debug/cvirtualkeyboard.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cvirtualkeyboard.cpp
	$(cpp)

linux_gcc_debug/cvirtualkeyboard.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cvirtualkeyboard.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cvirtualkeyboard.h ../../../Src/GUIFramework/QTFramework/CWidgets/cvirtualkeyboard.pp

linux_gcc_debug/cwidget.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidget.cpp
	$(cpp)

linux_gcc_debug/cwidget.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidget.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cwidget.h ../../../Src/GUIFramework/QTFramework/CWidgets/cwidget.pp

linux_gcc_debug/cwidgetbase.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetbase.cpp
	$(cpp)

linux_gcc_debug/cwidgetcomm.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetcomm.cpp
	$(cpp)

linux_gcc_debug/moc_cwidgetcomm.cpp: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetcomm.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetcomm.h -olinux_gcc_debug/moc_cwidgetcomm.cpp

linux_gcc_debug/cwidgethelper.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgethelper.cpp
	$(cpp)

linux_gcc_debug/cwidgetstack.o: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetstack.cpp
	$(cpp)

linux_gcc_debug/cwidgetstack.h: ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetstack.pp
	pp -f$(SHBIN)/ppQt.pre -olinux_gcc_debug/cwidgetstack.h ../../../Src/GUIFramework/QTFramework/CWidgets/cwidgetstack.pp

linux_gcc_debug/pluginlog.o: ../../../Src/GUIFramework/QTFramework/CWidgets/Plugin/pluginlog.cpp
	$(cpp)

linux_gcc_debug/qt_keyboard.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard.h -olinux_gcc_debug/moc_qt_keyboard.cpp

linux_gcc_debug/qt_keyboard_button.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_button.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_button.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_button.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_button.h -olinux_gcc_debug/moc_qt_keyboard_button.cpp

linux_gcc_debug/qt_keyboard_input.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_input.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_input.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_input.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_input.h -olinux_gcc_debug/moc_qt_keyboard_input.cpp

linux_gcc_debug/qt_keyboard_layout.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout.cpp
	$(cpp)

linux_gcc_debug/moc_qt_keyboard_layout.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout.h -olinux_gcc_debug/moc_qt_keyboard_layout.cpp

linux_gcc_debug/qt_keyboard_layout_german.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -o linux_gcc_debug/qt_keyboard_layout_german.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -i linux_gcc_debug/qt_keyboard_layout_german.h -o linux_gcc_debug/qt_keyboard_layout_german.cpp
linux_gcc_debug/qt_keyboard_layout_german.h: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -o linux_gcc_debug/qt_keyboard_layout_german.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_german.ui -i linux_gcc_debug/qt_keyboard_layout_german.h -o linux_gcc_debug/qt_keyboard_layout_german.cpp

linux_gcc_debug/qt_keyboard_layout_standard.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -o linux_gcc_debug/qt_keyboard_layout_standard.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -i linux_gcc_debug/qt_keyboard_layout_standard.h -o linux_gcc_debug/qt_keyboard_layout_standard.cpp
linux_gcc_debug/qt_keyboard_layout_standard.h: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -o linux_gcc_debug/qt_keyboard_layout_standard.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboard_layout_standard.ui -i linux_gcc_debug/qt_keyboard_layout_standard.h -o linux_gcc_debug/qt_keyboard_layout_standard.cpp

linux_gcc_debug/qt_keyboardalpha.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboardalpha.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboardalpha.ui -o linux_gcc_debug/qt_keyboardalpha.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboardalpha.ui -i linux_gcc_debug/qt_keyboardalpha.h -o linux_gcc_debug/qt_keyboardalpha.cpp
linux_gcc_debug/qt_keyboardalpha.h: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboardalpha.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboardalpha.ui -o linux_gcc_debug/qt_keyboardalpha.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keyboardalpha.ui -i linux_gcc_debug/qt_keyboardalpha.h -o linux_gcc_debug/qt_keyboardalpha.cpp

linux_gcc_debug/qt_keypadnumeric.cpp: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keypadnumeric.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keypadnumeric.ui -o linux_gcc_debug/qt_keypadnumeric.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keypadnumeric.ui -i linux_gcc_debug/qt_keypadnumeric.h -o linux_gcc_debug/qt_keypadnumeric.cpp
linux_gcc_debug/qt_keypadnumeric.h: ../../../Src/GUIFramework/QTFramework/Keypads/qt_keypadnumeric.ui
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keypadnumeric.ui -o linux_gcc_debug/qt_keypadnumeric.h
	$(QTDIR)/bin/uic ../../../Src/GUIFramework/QTFramework/Keypads/qt_keypadnumeric.ui -i linux_gcc_debug/qt_keypadnumeric.h -o linux_gcc_debug/qt_keypadnumeric.cpp

linux_gcc_debug/qt_navigation_widget.o: ../../../Src/GUIFramework/QTFramework/Dialogs/qt_navigation_widget.cpp
	$(cpp)

linux_gcc_debug/qt_number_validator.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_number_validator.cpp
	$(cpp)

linux_gcc_debug/qt_property_widget.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_property_widget.cpp
	$(cpp)

linux_gcc_debug/qt_string_validator.o: ../../../Src/GUIFramework/QTFramework/Keypads/qt_string_validator.cpp
	$(cpp)

linux_gcc_debug/touch_style.o: ../../../Src/GUIFramework/QTFramework/Styles/touch_style.cpp
	$(cpp)

linux_gcc_debug/moc_touch_style.cpp: ../../../Src/GUIFramework/QTFramework/Styles/touch_style.h
	$(QTDIR)/bin/moc ../../../Src/GUIFramework/QTFramework/Styles/touch_style.h -olinux_gcc_debug/moc_touch_style.cpp

