TEMPLATE	= app
LANGUAGE	= C++

CONFIG	+= qt warn_off

HEADERS += Funcs/Demo.txt

SOURCES	+= Funcs/Demo.txt

FORMS	= Forms/demoframe.ui \
	Forms/demostartup.ui \
	Forms/page1.ui \
	Forms/page2.ui \
	Forms/page3.ui \
	Forms/page4.ui

IMAGES	=

# qmake project generated by QMsDev
#
# General settings

TARGET  += main


# Input




TRANSLATIONS    = en-US.ts \
                  fr.ts \
                  zh.ts \
                  sv.ts
