/* [calc_pim.h] Parser table for 'calc'  */

/* File generated by 'ctoh'. Don't change manually. */

#ifndef calc_pim_INCL
#define calc_pim_INCL


#include "prs.h"


#ifdef __cplusplus
extern "C" {
#endif


PLR_Tab PLR_get_calc();                /* simulates a PLR_getTab            */


#ifdef __cplusplus
}
#endif

#endif
