/* [Shac_lim.c] Scanner table for 'Shacira'  */

/* File generated by 'ctoh'. Don't change manually. */

#ifndef shac_lim_INCL
#define shac_lim_INCL


#include "scn_io.h"


#ifdef __cplusplus
extern "C" {
#endif


void Scn_get_Shacira(Scn_T *scn);      /* simulates a Scn_get               */


#ifdef __cplusplus
}
#endif

#endif
