/* [Shac_pim.c] Parser table for 'Shacira'  */

/* File generated by 'ctoh'. Don't change manually. */

#ifndef shac_pim_INCL
#define shac_pim_INCL


#include "prs.h"


#ifdef __cplusplus
extern "C" {
#endif


PLR_Tab PLR_get_Shacira();             /* simulates a PLR_getTab            */


#ifdef __cplusplus
}
#endif

#endif
