pp ../../Src/GUIFramework/QTFramework/CWidgets/cactiondialog.pp -opp/cactiondialog.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cactvalue.pp -opp/cactvalue.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/calarmwidget.pp -opp/calarmwidget.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cappframe.pp -opp/cappframe.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cbuttongroup.pp -opp/cbuttongroup.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ccheckbox.pp -opp/ccheckbox.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ccombobox.pp -opp/ccombobox.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ccomplistview.pp -opp/ccomplistview.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ccomposedstack.pp -opp/ccomposedstack.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ccoordsystem.pp -opp/ccoordsystem.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cdate.pp -opp/cdate.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cdatetime.pp -opp/cdatetime.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cdirectory.pp -opp/cdirectory.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cfixtext.pp -opp/cfixtext.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cframe.pp -opp/cframe.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cGraphic.pp -opp/cGraphic.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cgroupbox.pp -opp/cgroupbox.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cgroupselectbutton.pp -opp/cgroupselectbutton.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cindreqvalue.pp -opp/cindreqvalue.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cinfolabel.pp -opp/cinfolabel.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/clistview.pp -opp/clistview.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cpage.pp -opp/cpage.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cprocgraphic.pp -opp/cprocgraphic.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cprogressbar.pp -opp/cprogressbar.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cpushbutton.pp -opp/cpushbutton.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cradiobutton.pp -opp/cradiobutton.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/creqvalue.pp -opp/creqvalue.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cringgraphic.pp -opp/cringgraphic.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cscrollbar.pp -opp/cscrollbar.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/csimplegraphic.pp -opp/csimplegraphic.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cslider.pp -opp/cslider.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cspinbox.pp -opp/cspinbox.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cstartupform.pp -opp/cstartupform.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cstatebutton.pp -opp/cstatebutton.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ctable.pp -opp/ctable.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ctabwidget.pp -opp/ctabwidget.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ctextedit.pp -opp/ctextedit.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ctime.pp -opp/ctime.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/ctoolbutton.pp -opp/ctoolbutton.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cvardimension.pp -opp/cvardimension.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cvideo.pp -opp/cvideo.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cvirtualkeyboard.pp -opp/cvirtualkeyboard.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cwidget.pp -opp/cwidget.h
pp ../../Src/GUIFramework/QTFramework/CWidgets/cwidgetstack.pp -opp/cwidgetstack.h
