
/// PR 15.06.05 - added english version of the system text table


#include "FirstHeader.h"
#include "System/text/SystemText.h"

const TEXT_ENTRY_T _SystemText[] = {
// new system texts: place at the end of the table
{UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "Unbehandelte Ausnahme (#1,#2,#3,#4)")},
{VARIANT_CONVERSION_ERROR, QT_TRANSLATE_NOOP("system", "#1 kann nicht in den Datentyp #2 umgewandelt werden")},
{FILE_NOT_FOUND, QT_TRANSLATE_NOOP("system", "Datei #1 fehlt")},
{JOB_ENTRY_INVALID_PROPERTY_INDEX, QT_TRANSLATE_NOOP("system", "Ungültiger Eigenschaftsindex #2 beim Zugriff auf Job-Eintrag in #1")},
{JOB_ENTRY_INVALID_VALUE_INDEX, QT_TRANSLATE_NOOP("system", "Ungültiger Wertindex #2 beim Zugriff auf Job-Eintrag in #1")},
{JOB_ENTRY_INVALID_PROPERTY, QT_TRANSLATE_NOOP("system", "Unbekannte Eigenschaft #2 beim Zugriff auf Job-Eintrag in #1")},
{JOB_ENTRY_INVALID_OPERATION, QT_TRANSLATE_NOOP("system", "Operation #3 mit Index #2 nicht erlaubt beim Zugriff auf Job-Eintrag in #1")},
{JOB_SPEC_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "Ungültiger Index #2 beim Zugriff auf Job-Spezifikation #1")},
{ASYNC_CHANNEL_NULL_OBJECT, QT_TRANSLATE_NOOP("system", "Nullobjekt im asynchronen Kanal #1")},
{ASYNC_CHANNEL_INVALID_OBJECT, QT_TRANSLATE_NOOP("system", "Ungültiges Objekt im asynchronen Kanal #1")},
{ASYNC_CHANNEL_UNKNOWN_MSG_ID, QT_TRANSLATE_NOOP("system", "Unbekannte Nachrichtenkennung #2 im asynchronen Kanal #1")},
{INI_FILE_LINE_LENGTH_EXCEEDED, QT_TRANSLATE_NOOP("system", "Maximale Zeilenlänge von #1 in Datei #2 überschritten")},
{VIRTUAL_METHOD_NOT_IMPLEMENTED, QT_TRANSLATE_NOOP("system", "Virtuelle Methode #1 im Objekt #2 ist nicht implementiert")},
{INVALID_PARAMETER_VALUE, QT_TRANSLATE_NOOP("system", "Ungültiger Parameterwert #1 in Funktion #2")},
{STATIC_OBJECT_EVENTFUNC_NOTIMPL, QT_TRANSLATE_NOOP("system", "Ereignismethode in #1 ist nicht implementiert. Ereignisobjekttyp ist #2")},
{METHOD_NOT_OVERLOADED, QT_TRANSLATE_NOOP("system", "Virtuelle Methode ist nicht überladen Datei #1 Zeile #2")},
{CONFIG_FILE_NOT_FOUND, QT_TRANSLATE_NOOP("system", "Konfigurationsdatei #1 fehlt")},
{CONFIG_NO_CONFIG_OBJECT, QT_TRANSLATE_NOOP("system", "Kein Konfigurationsobjekt in #1 gefunden")},
{CONFIG_AMBIGUOUS_OBJECT, QT_TRANSLATE_NOOP("system", "Objekt #1 ist mindestens zweimal definiert")},
{CONFIG_INVALID_TYPEDEF, QT_TRANSLATE_NOOP("system", "Typdefinition #1 von Objekt #2 fehlt oder ist ungültig")},
{CONFIG_AMBIGUOUS_PROPERTY, QT_TRANSLATE_NOOP("system", "Eigenschaft #1 ist mindestens zweimal definiert")},
{CONFIG_NO_DEFFILE_SPEC, QT_TRANSLATE_NOOP("system", "Keine Definitionsdatei in #1 spezifiziert (Eigenschaft DefFile)")},
{CONFIG_NO_CONFIGOBJECT_SPEC, QT_TRANSLATE_NOOP("system", "Kein Konfigurationsobjekt in #1 nicht spezifiziert (Objekt Configuration)")},
{CONFIG_NO_PROPERTYDEF, QT_TRANSLATE_NOOP("system", "Eigenschaft #1 in Objekt #2 ist nicht definiert")},
{CONFIG_NO_TYPEDEF, QT_TRANSLATE_NOOP("system", "Typ der Eigenschaft #1 in Objekt #2 ist nicht definiert")},
{CONFIG_INVALID_BASETYPE, QT_TRANSLATE_NOOP("system", "Basistyp #1 der Eigenschaft #2 in Objekt #3 ist ungültig")},
{CONFIG_PROPERTY_ALREADY_RESOLVED, QT_TRANSLATE_NOOP("system", "Eigenschaft #1 schon aufgelöst")},
{CONFIG_UNABLE_TO_RESOLVE_OBJECT, QT_TRANSLATE_NOOP("system", "Objekt #1 kann nicht aufgelöst werden")},
{CONFIG_UNKNOWN_TYPEDEF, QT_TRANSLATE_NOOP("system", "Unbekannte Typdefinition #1 für Eigenschaft #2")},
{CONFIG_AMBIGUOUS_BASETYPE, QT_TRANSLATE_NOOP("system", "Basistyp für #1 mindestens zweimal definiert")},
{CONFIG_AMBIGUOUS_RANGETYPE, QT_TRANSLATE_NOOP("system", "Basistyp (range type) für #1 mindestens zweimal definiert")},
{CONFIG_CANNOT_SET_RANGE, QT_TRANSLATE_NOOP("system", "Bereichsangaben #2 für #1 ungültig")},
{CONFIG_UNDEFINED_BASETYPE, QT_TRANSLATE_NOOP("system", "Basistyp für #1 undefiniert")},
{CONFIG_INVALID_TYPESPEC, QT_TRANSLATE_NOOP("system", "Ungültige Typangabe #1 für #2")},
{CONFIG_NO_TYPESPEC, QT_TRANSLATE_NOOP("system", "Keine Typangabe für #1")},
{CONFIG_AMBIGUOUS_TYPEDEF, QT_TRANSLATE_NOOP("system", "Typ #1 mindestens zweimal definiert")},
{CONFIG_OBJECT_TYPE_MISMATCH, QT_TRANSLATE_NOOP("system", "In der Eigenschaft #1 des Objekts #2 können nur Objekte vom Typ #3 spezifiziert werden (#4)")},
{CONFIG_NO_SCALAR, QT_TRANSLATE_NOOP("system", "Eigenschaft #1 des Objekts #2 ist kein Skalar")},
{CONFIG_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "Typ der Eigenschaft #1 des Objekts #2 ist ungültig (#3)")},
{CONFIG_NO_VALUE, QT_TRANSLATE_NOOP("system", "Kein Wert für Eigenschaft #1 des Objekts #2")},
{CONFIG_NO_VECTOR, QT_TRANSLATE_NOOP("system", "Eigenschaft #1 des Objekts #2 ist kein Vektor")},
{CONFIG_INVALID_VALUE, QT_TRANSLATE_NOOP("system", "Ungültiger Wert #1 für Eigenschaft #2 des Objekts #3")},
{CONFIG_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "Zugriff mit ungültigem Index auf Eigenschaft #1 des Objekts #2")},
{CONFIG_NOT_NUMERIC, QT_TRANSLATE_NOOP("system", "Wert für Eigenschaft #1 des Objekts #2 ist nicht numerisch (#3)")},
{CONFIG_INVALID_BOOL_SPEC, QT_TRANSLATE_NOOP("system", "Wert für Eigenschaft #1 des Objekts #2 ist kein Boolescher Wert (#3)")},
{CONFIG_NO_PROPVAL, QT_TRANSLATE_NOOP("system", "Die Eigenschaft #1 des Objekts #2 muss spezifiziert werden")},
{VALUE_NO_TYPEDEF, QT_TRANSLATE_NOOP("system", "Typ des Werts #1 ist nicht definiert")},
{VALUE_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "Ungültiger Typ #2 für Zugriff auf Wert #1")},
{ORB_BROKER_INACTIVE, QT_TRANSLATE_NOOP("system", "Der Object Request Broker ist inaktiv (noch nicht gestartet)")},
{ORB_BROKER_ACTIVE, QT_TRANSLATE_NOOP("system", "Der Object Request Broker ist aktiv (wurde schon gestartet)")},
{ORB_START_FAILURE, QT_TRANSLATE_NOOP("system", "Der Object Request Broker #1 kann nicht getartet werden")},
{ORB_ORB_INACTIVE, QT_TRANSLATE_NOOP("system", "Der ORB des Object Request Broker #1 ist nicht aktiv")},
{ORB_BOA_INACTIVE, QT_TRANSLATE_NOOP("system", "Der BOA des Object Request Broker #1 ist nicht aktiv")},
{SOCKET_SETSOCKOPT, QT_TRANSLATE_NOOP("system", "Setzen der Socketoption #3 fehlgeschlagen für #1/#2")},
{SOCKET_VERSION, QT_TRANSLATE_NOOP("system", "Falsche Version der Winsock DLL #1/#2")},
{SOCKET_CREATE, QT_TRANSLATE_NOOP("system", "Socket kann auf #1/#2 nicht erzeugt werden")},
{SOCKET_RECVFROM, QT_TRANSLATE_NOOP("system", "Socketfehler beim Empfangen auf #1/#2 #3")},
{SOCKET_SENDTO, QT_TRANSLATE_NOOP("system", "Socketfehler beim Senden auf #1/#2")},
{SOCKET_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "Empfangspuffer zu klein für Socket auf #1/#2 (#4 < #3)")},
{SOCKET_STARTUP, QT_TRANSLATE_NOOP("system", "Socket Subsystem kann nicht gestartet werden")},
{SOCKET_BIND, QT_TRANSLATE_NOOP("system", "Socketfehler beim Binden von #1/#2")},
{PROXY_UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "Unbekannter Fehler beim Zugriff auf Proxy: #1")},
{PROXY_NO_INTERFACE, QT_TRANSLATE_NOOP("system", "Proxy Schnittstelle nicht initialisiert in #1")},
{PROXY_NO_OBJECT_INTERFACE, QT_TRANSLATE_NOOP("system", "Objekt bietet keine Schnittstelle für #1 an")},
{PROXY_NO_OBJECT, QT_TRANSLATE_NOOP("system", "Kein Zugriff auf Objekt über #1")},
{PROXY_CORBA_SYSTEM, QT_TRANSLATE_NOOP("system", "CORBA Systemfehler beim Zugriff auf #1")},
{PROXY_TYPE_MISMATCH, QT_TRANSLATE_NOOP("system", "Typen beim Aktualisieren der Proxydaten von #1 stimmen nicht überein (#2 != #3)")},
{CORBA_UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "Unbekannter Fehler beim Aufruf der Methode #1")},
{CONSOLE_INVALID_DIRECTION, QT_TRANSLATE_NOOP("system", "Ungültige Richtung für Konsole #1")},
{FACTORY_INVALID_VALUE, QT_TRANSLATE_NOOP("system", "Ungültiger Wert #1 beim Erzeugen eines Objekts vom Typ #2")},
{CHANNEL_WRAPPER_START_PROCESS, QT_TRANSLATE_NOOP("system", "Prozess #1 #2 kann nicht gestartet werden (#3)")},
{CHANNEL_WRAPPER_NO_CONTACT, QT_TRANSLATE_NOOP("system", "Zum Ereigniskanalobjekt #1 kann keine Verbindung hergestellt werden")},
{PROXY_RECEIVER_UNKNOWN_POT, QT_TRANSLATE_NOOP("system", "Unbekannter Proxytyp #1 auf Empfänger #2 #3")},
{PROXY_RECEIVER_FAILED_TO_CONSTRUCT, QT_TRANSLATE_NOOP("system", "Proxy-Rekonstruktion auf Empfänger #1 nicht möglich #2")},
{OBJECT_PARSER_FAILURE, QT_TRANSLATE_NOOP("system", "Objekt Parser: Objekt kann nicht interpretiert werden #1")},
{OBJECT_PARSER_CONSTRUCT_HEADER, QT_TRANSLATE_NOOP("system", "Objekt Parser: Header des Objekts kann nicht konstruiert werden #1")},
{OBJECT_PARSER_INVALID_OBJECTTYPE, QT_TRANSLATE_NOOP("system", "Objekt Parser: Ungültiger Objekttyp #1 im Header #2")},
{OBJECT_PARSER_INVALID_SUBTYPE1, QT_TRANSLATE_NOOP("system", "Objekt Parser: Ungültiger Typ1 #1 im Header #2")},
{OBJECT_PARSER_INVALID_SUBTYPE2, QT_TRANSLATE_NOOP("system", "Objekt Parser: Ungültiger Typ2 #1 im Header #2")},
{EVENT_CHANNEL_NO_CHANNEL, QT_TRANSLATE_NOOP("system", "Ereigniskanal #1 nicht verfügbar")},
{CYCLEBUF_COLUMN_INDEX_INVALID, QT_TRANSLATE_NOOP("system", "Im Zykluspuffer existiert keine Spalte mit Index #1")},
{CYCLEBUF_COLUMN_NAME_INVALID, QT_TRANSLATE_NOOP("system", "Im Zykluspuffer existiert keine Spalte mit Namen #1")},
{CYCLEBUF_ROW_INVALID, QT_TRANSLATE_NOOP("system", "Im Zykluspuffer existiert keine Zeile mit Index #1")},
{CYCLEBUF_ROW_COUNT, QT_TRANSLATE_NOOP("system", "Ungültige Grössenangabe im Zykluspuffer (#1 > #2)")},
{SOCKET_CHANNEL_NO_PORT_NAME, QT_TRANSLATE_NOOP("system", "Kein Portname für W&T-Kanal #1")},
{SOCKET_CHANNEL_NO_SERIAL_PORT, QT_TRANSLATE_NOOP("system", "Kein Port für W&T-Kanal #1 (A,B,C,D)")},
{SOCKET_CHANNEL_INVALID_SERIAL_PORT, QT_TRANSLATE_NOOP("system", "Ungültiger Port #2 für W&T-Kanal #1 (A,B,C,D)")},
{SOCKET_CHANNEL_NO_IP_ADDRESS, QT_TRANSLATE_NOOP("system", "Keine IP-Adresse für W&T-Kanal #1")},
{SOCKET_CHANNEL_BAD_IP_ADDRESS, QT_TRANSLATE_NOOP("system", "Ungültige IP-Adresse #2 für W&T-Kanal #1")},
{STDSER_NO_PORT_NAME, QT_TRANSLATE_NOOP("system", "Kein Portname für serielle Schnittstelle")},
{STDSER_PORT_NAME_SIZE, QT_TRANSLATE_NOOP("system", "Länge des Portnamens #1 überschreitet die maximale Grösse")},
{STDSER_INVALID_HANDLE, QT_TRANSLATE_NOOP("system", "Ungültiges Handle beim Zugriff auf Schnittstelle #1")},
{STDSER_SET_COMM_STATE, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen der Kommunikationsparameter auf Port #1")},
{STDSER_GET_COMM_STATE, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen der Kommunikationsparameter auf Port #1")},
{STDSER_CREATE_FILE, QT_TRANSLATE_NOOP("system", "Fehler beim Öffnen der Schnittstelle auf Port #1")},
{STDSER_SET_COMM_TIMEOUTS, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen der Timeout-Parameter von Port #1")},
{STDSER_GET_COMM_TIMEOUTS, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen der Timeout-Parameter von Port #1")},
{STDSER_CLEAR_COMM_ERROR, QT_TRANSLATE_NOOP("system", "Fehler beim Rücksetzen von Fehlerbedingungen auf Port #1")},
{STDSER_WRITE_FILE, QT_TRANSLATE_NOOP("system", "Fehler beim Schreiben von Daten auf Port #1")},
{STDSER_READ_FILE, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen von Daten auf Port #1")},
{DIGIO_INVALID_CARDTYPE, QT_TRANSLATE_NOOP("system", "Ungültiger Kartentyp #1")},
{PA150_OPEN, QT_TRANSLATE_NOOP("system", "Fehler beim Öffnen der PA150 im digitalen Kanal #1")},
{PA150_READ1_INPUT, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen des Eingangs #1 der PA150 im digitalen Kanal #2")},
{PA150_READ16_INPUT, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen der Eingänge der PA150 im digitalen Kanal #1")},
{PA150_SET1_OUTPUT_ON, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Ausgangs #1 der PA150 im digitalen Kanal #2")},
{PA150_SET1_OUTPUT_OFF, QT_TRANSLATE_NOOP("system", "Fehler beim Rücksetzen des Ausgangs #1 der PA150 im digitalen Kanal #2")},
{ADDI_UNIVERSAL_OPEN, QT_TRANSLATE_NOOP("system", "Fehler beim Öffnen der ADDI_UNIVERSAL im digitalen Kanal #1")},
{ADDI_UNIVERSAL_READ1_INPUT, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen des Eingangs #1 der ADDI_UNIVERSAL im digitalen Kanal #2")},
{ADDI_UNIVERSAL_READ_INPUTS, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen der Eingänge der ADDI_UNIVERSAL im digitalen Kanal #1")},
{ADDI_UNIVERSAL_SET1_OUTPUT_ON, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Ausgangs #1 der ADDI_UNIVERSAL im digitalen Kanal #2")},
{ADDI_UNIVERSAL_SET1_OUTPUT_OFF, QT_TRANSLATE_NOOP("system", "Fehler beim Rücksetzen des Ausgangs #1 der ADDI_UNIVERSAL im digitalen Kanal #2")},
{ADDI_UNIVERSAL_GET_INPUT_NO, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen der Anzahl Eingänge der ADDI_UNIVERSAL im digitalen Kanal #1")},
{ADDI_UNIVERSAL_GET_OUTPUT_NO, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen der Anzahl Ausgänge der ADDI_UNIVERSAL im digitalen Kanal #1")},
{ADDI_UNIVERSAL_SET_OUTPUT_MEM, QT_TRANSLATE_NOOP("system", "Fehler beim Initialisieren des Speichers ADDI_UNIVERSAL im digitalen Kanal #1")},
{ADDI_UNIVERSAL_INVALID_NOOFINPUTS, QT_TRANSLATE_NOOP("system", "Ungültige Anzahl von Eingängen #1 der ADDI_UNIVERSAL im digitalen Kanal #2")},
{DRIVER_NOT_CONNECTED, QT_TRANSLATE_NOOP("system", "Keine Verbindung zu #1")},
{DRIVER_READ_SUBTRACTING_SHOTCOUNT, QT_TRANSLATE_NOOP("system", "Unbekannter Fehler beim Lesen des subtrahierenden Schusszählers in #1")},
{DRIVER_READ_ADDING_SHOTCOUNT, QT_TRANSLATE_NOOP("system", "Unbekannter Fehler beim Lesen des addierenden Schusszählers in #1")},
{DRIVER_RCV_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "Überlauf im Empfangspuffer von #1")},
{DRIVER_NO_BUFFER, QT_TRANSLATE_NOOP("system", "Im Treiber #2 existiert kein physikalisher Puffer für Index #1")},
{DRIVER_INVALID_PHYS_SPEC, QT_TRANSLATE_NOOP("system", "Spezifikation des physikalischen Speichers #1 in Treiber #2 unbekannt")},
{VIRTDATA_ITEM_EXISTS, QT_TRANSLATE_NOOP("system", "Virtuelle Variable #1 ist in #2 schon definiert")},
{VIRTDATA_ITEM_NOT_FOUND, QT_TRANSLATE_NOOP("system", "Virtuelle Variable #1 ist in #2 unbekannt")},
{FM_MACHINE_ERROR, QT_TRANSLATE_NOOP("system", "Maschine #1 meldet Fehler #2 auf Anfrage #3")},
{FM_ABORT, QT_TRANSLATE_NOOP("system", "Kommunikationsabbruch durch Maschine in #1")},
{FM_CR_LF_ERROR, QT_TRANSLATE_NOOP("system", "CR LF erwartet in #1")},
{FM_CHECKSUM_ERROR, QT_TRANSLATE_NOOP("system", "Checksummenfehler in #1")},
{FM_MISSING_ETX, QT_TRANSLATE_NOOP("system", "ETX erwartet in #1")},
{FM_RCV_CHAR_TIMEOUT, QT_TRANSLATE_NOOP("system", "Timeout beim Empfang eines Zeichens in #1")},
{FM_CONTACT_RETRIES, QT_TRANSLATE_NOOP("system", "Anzahl Wiederholungsversuche bei der Kontaktaufnahme überschritten in #1")},
{FM_BLK_RETRIES_1, QT_TRANSLATE_NOOP("system", "Anzahl Wiederholungsversuche bei der Blockübertragung Zustand 1 überschritten in #1")},
{FM_CHAR_TIMEOUT_5, QT_TRANSLATE_NOOP("system", "Timeout beim Empfang eines Zeichens im Zustand 5 in #1")},
{FM_UNDEF_CHAR_5, QT_TRANSLATE_NOOP("system", "Unerwartetes Zeichen im Zustand 5 empfangen in #1")},
{FM_BLK_RETRIES_2, QT_TRANSLATE_NOOP("system", "Anzahl Wiederholungsversuche bei der Blockübertragung Zustand 2 überschritten in #1")},
{FM_CHAR_TIMEOUT_10, QT_TRANSLATE_NOOP("system", "Timeout beim Empfang eines Zeichens im Zustand 10 in #1")},
{FM_UNDEF_CHAR_10, QT_TRANSLATE_NOOP("system", "Unerwartetes Zeichen im Zustand 10 empfangen in #1")},
{FM_BLK_RETRIES_3, QT_TRANSLATE_NOOP("system", "Anzahl Wiederholungsversuche bei der Blockübertragung Zustand 3 überschritten in #1")},
{FM_UNDEF_CHAR_13, QT_TRANSLATE_NOOP("system", "Unerwartetes Zeichen im Zustand 13 empfangen in #1")},
{FM_CHAR_TIMEOUT_15, QT_TRANSLATE_NOOP("system", "Timeout beim Empfang eines Zeichens im Zustand 15 in #1")},
{FM_UNDEF_CHAR_15, QT_TRANSLATE_NOOP("system", "Unerwartetes Zeichen im Zustand 15 empfangen in #1")},
{FM_BLK_RETRIES_4, QT_TRANSLATE_NOOP("system", "Anzahl Wiederholungsversuche bei der Blockübertragung Zustand 4 überschritten in #1")},
{FM_RCV_COMM_ABORTED, QT_TRANSLATE_NOOP("system", "Kommunikation von der Maschine abgebrochen in #1")},
{FM_ECHO, QT_TRANSLATE_NOOP("system", "Fehlerhaftes Echo empfangen in #1")},
{FM_UNKNOWN_COMMAND, QT_TRANSLATE_NOOP("system", "Unbekanntes Kommando #1 in #2")},
{FM_MS_SYNTAX, QT_TRANSLATE_NOOP("system", "Maschinenstatus kann nicht interpretiert werden in #1 #2")},
{FM_TB_SYNTAX, QT_TRANSLATE_NOOP("system", "Zykluspuffer kann nicht interpretiert werden in #1 #2")},
{FM_CB_SYNTAX, QT_TRANSLATE_NOOP("system", "Änderungspuffer kann nicht interpretiert werden in #1 #2")},
{FM_EB_SYNTAX, QT_TRANSLATE_NOOP("system", "Fehlerpuffer kann nicht interpretiert werden in #1 #2")},
{FM_MS_ERROR, QT_TRANSLATE_NOOP("system", "Fehler beim interpretieren des Maschinenstatus in #1 #2")},
{FM_TB_ERROR, QT_TRANSLATE_NOOP("system", "Fehler beim interpretieren des Zykluspuffers in #1 #2")},
{FM_CB_ERROR, QT_TRANSLATE_NOOP("system", "Fehler beim interpretieren des Änderungspuffers in #1 #2")},
{FM_EB_ERROR, QT_TRANSLATE_NOOP("system", "Fehler beim interpretieren des Fehlerpuffers in #1 #2")},
{VARIABLE_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "Ungültiger Index #2 beim Zugriff auf Variable #1 an Stelle #3 Maximum ist #4")},
{VARIABLE_INVALID_DIM, QT_TRANSLATE_NOOP("system", "Ungültige Indexposition #2 beim Zugriff auf Variable #1 (#3 Dimensionen)")},
{VARIABLE_NOT_FOUND, QT_TRANSLATE_NOOP("system", "Variable #1 konnte (noch) nicht gefunden werden")},
{VARIABLE_NO_MAPPING, QT_TRANSLATE_NOOP("system", "Kein Mapping für Variable #1 Position #2")},
{VARIABLE_NO_MAP_ITEM, QT_TRANSLATE_NOOP("system", "Kein Map-Element für Variable #1 Position #2")},
{VARIABLE_NO_DEVICE, QT_TRANSLATE_NOOP("system", "Kein Geraet für Mapping der Variable #1 Position #2")},
{VARIABLE_READ_ONLY, QT_TRANSLATE_NOOP("system", "Variable #1 kann nich beschrieben werden")},
{VARIABLE_NULL_MAPPING, QT_TRANSLATE_NOOP("system", "Null Mapping für Variable #1 Position #2")},
{FUNC_INVALID_PARAMPOS, QT_TRANSLATE_NOOP("system", "Ungültige Parameterposition #2 beim Zugriff auf Funktion")},
{PARSE_FUNCREF_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "Funktion #3 ist nicht deklariert (Zeile #1, Spalte #2)")},
{PARSE_FUNCREF_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "Ungültiger Typ der Funktion #3 in Referenz (Zeile #1, Spalte #2)")},
{PARSE_FUNCREF_TOO_MUCH_PARAMS, QT_TRANSLATE_NOOP("system", "Zu viele Parameter in Funktionsreferenz von #3 (Zeile #1, Spalte #2)")},
{PARSE_FUNCREF_TOO_FEW_PARAMS, QT_TRANSLATE_NOOP("system", "Zu wenige Parameter in Funktionsreferenz von #3 (Zeile #1, Spalte #2)")},
{PARSE_FUNCREF_INVALID_PARAMTYPE, QT_TRANSLATE_NOOP("system", "Falscher Parametertyp an Position #4 in Funktionsreferenz von #3 (Zeile #1, Spalte #2)")},
{PARSE_FUNCREF_NO_PARAMTYPE, QT_TRANSLATE_NOOP("system", "Parametertyp an Position #4 in Funktionsreferenz von #3 kann nicht ermittelt werden (Zeile #1, Spalte #2)")},
{PARSE_TYPES_NOT_COMPATIBLE, QT_TRANSLATE_NOOP("system", "Ungültige Typverwendung. Erwartet: #3, Verwendet: #4 (Zeile #1, Spalte #2)")},
{PARSE_FUNCREF_INVALID_CLASS, QT_TRANSLATE_NOOP("system", "Ungültige Fuktionsklasse: Erwartet: #3, Verwendet: #4 (Zeile #1, Spalte #2)")},
{PARSE_BITPOS, QT_TRANSLATE_NOOP("system", "Ungültige Bitposition: #3 (Zeile #1, Spalte #2)")},
{PARSE_BITPOS_SPECIFICATION, QT_TRANSLATE_NOOP("system", "Ungültige Bitpositionnsangabe: #3 (Zeile #1, Spalte #2)")},
{PARSE_VARREF_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "Variable #3 ist nicht definiert (Zeile #1, Spalte #2)")},
{PARSE_VARREF_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "Ungültiger Index für Variable #3 in Referenz (Zeile #1, Spalte #2)")},
{PARSE_VARREF_TOO_MUCH_INDICES, QT_TRANSLATE_NOOP("system", "Zu viele Indices in Variablenreferenz von #3 (Zeile #1, Spalte #2)")},
{PARSE_VARREF_TOO_FEW_INDICES, QT_TRANSLATE_NOOP("system", "Zu wenige Indices in Variablenreferenz von #3 (Zeile #1, Spalte #2)")},
{PARSE_VARREF_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "Ungültiger Typ für Index der Variable #3 in Referenz (Zeile #1, Spalte #2)")},
{PARSE_VARREF_NO_INDEX, QT_TRANSLATE_NOOP("system", "Indextyp für Index #4 der Variable #3 kann nicht ermittelt werden (Zeile #1, Spalte #2)")},
{PARSE_SYMBOL_RESOLVE, QT_TRANSLATE_NOOP("system", "Symbol #3 kann nicht aufgelöst werden (Zeile #1, Spalte #2)")},
{PARSE_SYNTAX_ERRORS_IN_FILE, QT_TRANSLATE_NOOP("system", "Syntaxfehler in Datei #1 Zeile #2 Spalte #3")},
{PARSE_SYNTAX_ERRORS_IN_STRING, QT_TRANSLATE_NOOP("system", "Syntaxfehler Zeile #2 Spalte #3 im Text: #1")},
{VARREF_NO_VARIABLE, QT_TRANSLATE_NOOP("system", "Variablenreferenz #1 hat keinen Verweis auf eine Variable")},
{FUNCREF_FAILED_TO_RESOLVE, QT_TRANSLATE_NOOP("system", "Funktion #1 kann nicht aufgelöst werden")},
{FUNCREF_FUNCTION_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "Funktion #1 ist nicht deklariert")},
{FUNCREF_FUNCTION_NOT_RESOLVED, QT_TRANSLATE_NOOP("system", "Funktion #1 ist nicht implementiert")},
{FUNCREF_PARAMETER_TYPE_NOT_SUPPORTED, QT_TRANSLATE_NOOP("system", "Datentyp #1 in Parameter #2 wird nicht unterstützt")},
{CELL_NO_DIGITALIO, QT_TRANSLATE_NOOP("system", "Keine digitale I/O konfiguriert (wird für Signal #1 benötigt)")},
{CELL_NO_DRIVER, QT_TRANSLATE_NOOP("system", "Kein Treiber für Variable #1")},
{CELL_CYCLESPEC_DRIVER_UNKNOWN, QT_TRANSLATE_NOOP("system", "Der Variablen #2 an Position #1 des Zykluspuffers von #3 ist kein Treiber zugeordnet")},
{CELL_NO_DISPATCHER, QT_TRANSLATE_NOOP("system", "Kein Dispatcher Kanal verfügbar")},
{CELL_NO_FAST_CHANNEL, QT_TRANSLATE_NOOP("system", "Kein schneller Kanal verfügbar")},
{CELL_CREATE_DEVICE, QT_TRANSLATE_NOOP("system", "Device Objekt #1 kann nicht erzeugt werden")},
{CELL_CREATE_PROGRAM, QT_TRANSLATE_NOOP("system", "Programm Objekt #1 kann nicht erzeugt werden")},
{CELL_UNKNOWN_PROGRAM, QT_TRANSLATE_NOOP("system", "Programm #1 ist unbekannt")},
{PROGRAM_UNKNOWN_IOSIGNAL, QT_TRANSLATE_NOOP("system", "Zugriff auf unbekanntes I/O-Signal #1 im Programm #1")},
{PROGRAMMABLE_COMMAND_UNKNOWN, QT_TRANSLATE_NOOP("system", "Kommando #1 im Treiber #2 ist unbekannt")},
{PROGRAMMABLE_SYNTAX_ERROR, QT_TRANSLATE_NOOP("system", "Syntaxfehler in Programm #1 für Treiber #2")},
{PROGRAMMABLE_UNKNOWN_DATA_TYPE, QT_TRANSLATE_NOOP("system", "Unbekannter Datentyp #1 im Programm für Treiber #2")},
{PROGRAMMABLE_INVALID_FORMAT_SPEC, QT_TRANSLATE_NOOP("system", "Ungültige Formatangabe #1 in Programm für Treiber #2")},
{PROGRAMMABLE_INVALID_CONSTRAINT, QT_TRANSLATE_NOOP("system", "Ungültige Constraint-Spezifikation #1 in Programm für Treiber #2")},
{PROGRAMMABLE_CONSTRAINT, QT_TRANSLATE_NOOP("system", "Randbedingung #1 verletzt in Treiber #2")},
{MAPPING_INVALID_ADDRESS, QT_TRANSLATE_NOOP("system", "Ungültige Adresse #1 in der Abbildung der Variable #2")},
{MAPPING_INVALID_MAPPING_TYPE, QT_TRANSLATE_NOOP("system", "Ungültige Abbildungstyp an Position #2 der Variable #1")},
{MAPPING_INVALID_MAPITEM_POS, QT_TRANSLATE_NOOP("system", "Ungültige Position für Map Item #1/#2")},
{DATA_OBJECT_VARIABLE_NOT_CREATED, QT_TRANSLATE_NOOP("system", "Variable #1 ist bei der Treiberabbildung nicht instanziiert")},
{MODBUS_HREGS_NO_RESPONSE, QT_TRANSLATE_NOOP("system", "Keine Antwort bei Register #2 in #1")},
{MODBUS_HREGS_INVALID_NODE, QT_TRANSLATE_NOOP("system", "Ungültige Knotennummer in Antwort bei Register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_INVALID_FUNCTION, QT_TRANSLATE_NOOP("system", "Ungültige Funktion in Antwort bei Register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_INVALID_BYTE_COUNT, QT_TRANSLATE_NOOP("system", "Ungültige Längenangabe in Antwort bei Register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_RESPONSE_TOO_SHORT, QT_TRANSLATE_NOOP("system", "Ungültige Antwortlänge bei Register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_RESPONSE_CRC_ERROR, QT_TRANSLATE_NOOP("system", "Ungültiger CRC in Antwort bei Register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_BUFFER_TOO_SHORT, QT_TRANSLATE_NOOP("system", "Pufferbereich zu klein für #3 (#4) Register in #1 bei Übertragung von Adresse #2")},
{CARRIER_UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "Unbehandelte Ausnahme beim Zugriff auf die Datenträger-Schnittstelle")},
{CARRIER_DEVICE_ACCESS, QT_TRANSLATE_NOOP("system", "Fehler beim Zugriff auf den Datenträger")},
{STRING_CACHE_TOO_MUCH_ELEMENTS, QT_TRANSLATE_NOOP("system", "Im String Cache ist maximal ein Element lesbar")},
{DEVICE_INVALID_MEMORY_ORGANIZATION, QT_TRANSLATE_NOOP("system", "Ungültige Grösse der Speicherorganisation für Geraet #1 Speicher #2: #3")},
{DEVICE_INVALID_DATATYPE, QT_TRANSLATE_NOOP("system", "Ungültiger Datentyp #1 für Bitoperator")},
{DEVICE_INVALID_GRANULARITY, QT_TRANSLATE_NOOP("system", "Ungültige Elementgrösse der Speicherstruktur #1 für Bitoperator")},
{DEVICE_NO_MEMORY_INFO, QT_TRANSLATE_NOOP("system", "Für die Speicherspezifikation #1 existiert keine Information")},
{DEVICE_NOT_CONNECTED, QT_TRANSLATE_NOOP("system", "Keine Verbindung zu #1")},
{GRABBER_OPEN_DEVICE, QT_TRANSLATE_NOOP("system", "Fehler beim Öffnen der Kamera: #1")},
{GRABBER_INIT_BOARD, QT_TRANSLATE_NOOP("system", "Fehler beim Initialisieren der Kamera: #1")},
{GRABBER_BOARD_INFO, QT_TRANSLATE_NOOP("system", "Fehler beim Abfragen der Board-Info der Kamera: #1")},
{GRABBER_SENSOR_INFO, QT_TRANSLATE_NOOP("system", "Fehler beim Abfragen der Sensor-Info der Kamera: #1")},
{GRABBER_SET_DISPLAY_MODE, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Display Modus der Kamera auf #2: #1")},
{GRABBER_SET_COLOR_MODE, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Farb Modus der Kamera auf #2: #1")},
{GRABBER_SET_IMAGE_SIZE, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen der Bildgrösse Farb Modus der Kamera auf (#2,#3): #1")},
{GRABBER_SET_CAPTURE_MODE, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Capture Modus der Kamera auf #2: #1")},
{GRABBER_CAPTURE_VIDEO, QT_TRANSLATE_NOOP("system", "Fehler beim Aktivieren der Aufnahme-Sequenz der Kamera: #1")},
{GRABBER_ALLOC_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "Fehler beim Anfordern von Videospeicher für Pixelgröße #2 : #1")},
{GRABBER_SET_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Videospeicher: #1")},
{GRABBER_FREE_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "Fehler beim Freigeben des Videospeicher: #1")},
{GRABBER_COPY_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "Fehler beim Kopieren des Videospeicher: #1")},
{GRABBER_SET_VIDEO_INPUT, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Video-Eingangs #2: #1")},
{GRABBER_INVALID_CHANNEL, QT_TRANSLATE_NOOP("system", "Ungültiger Video-Eingang #1")},
{TRAEGER_S7_OPEN, QT_TRANSLATE_NOOP("system", "Fehler beim Öffnen des Traeger-S7-Treibers Com: #1 SPS Adresse #2 Client Adresse #3")},
{TRAEGER_S7_READ, QT_TRANSLATE_NOOP("system", "Fehler beim Lesen vom Traeger-S7-Treiber Com: #1 Command #2 Adresse #3 Länge #4")},
{TRAEGER_S7_WRITE, QT_TRANSLATE_NOOP("system", "Fehler beim Schreiben auf Traeger-S7-Treiber Com: #1 Command #2 Adresse #3 Länge #4")},
{I60_READ, QT_TRANSLATE_NOOP("system", "Fehler in I60Load #1: Command #2 Adresse #3 Länge #4")},
{I60_WRITE, QT_TRANSLATE_NOOP("system", "Fehler in I60Save #1: Command #2 Adresse #3 Länge #4")},
{SHARED_LIBRARY_LOAD, QT_TRANSLATE_NOOP("system", "Fehler beim Laden der dynamischen Bibliothek #1")},
{SHARED_FUNCTION_LOAD, QT_TRANSLATE_NOOP("system", "Fehler beim Laden der dynamischen Funktion #2 aus Bibliothek #1")},
{STEPPER_READ_ONLY, QT_TRANSLATE_NOOP("system", "Schreiben auf schreibgeschütztes Datum #2 der #1-Achse")},
{STEPPER_MIN_VALUE, QT_TRANSLATE_NOOP("system", "Parameterwert zu klein für Parameter #2 Achse #1: #3 Minimum ist #4")},
{STEPPER_MAX_VALUE, QT_TRANSLATE_NOOP("system", "Parameterwert zu groß für Parameter #2 Achse #1: #3 Maximum ist #4")},
{STEPPER_DLL_LOAD, QT_TRANSLATE_NOOP("system", "Fehler beim Laden der DLL #1 für die Schrittmotorenansteuerung")},
{STEPPER_TARGET_TIMEOUT, QT_TRANSLATE_NOOP("system", "Zeitüberschreitung beim warten auf Position #2 auf Achse #1")},
{STEPPER_LOAD_PROC, QT_TRANSLATE_NOOP("system", "Fehler beim Laden der Funktion #2 aus DLL #1 für die Schrittmotorenansteuerung")},
{STEPPER_WRITE_ONLY, QT_TRANSLATE_NOOP("system", "Datum #2 der #1-Achse kann nicht gelesen werden (write only)")},
{STEPPER_SETREG, QT_TRANSLATE_NOOP("system", "Interner Fehler in der Funktion SetReg der DLL #1")},
{STEPPER_GETREG, QT_TRANSLATE_NOOP("system", "Interner Fehler in der Funktion GetReg der DLL #1")},
{IMAGE_BUFFER_TOO_SMALL, QT_TRANSLATE_NOOP("system", "Puffergröße für Bilddaten ist zu klein: benötigt #1 aktuell #2")},
{FAILED_TO_WRITE_DEVICE_BLOB_DATA, QT_TRANSLATE_NOOP("system", "Blobdaten von Variable #1 können nicht auf das Gerät geschrieben werden")},
{NO_BUFFER_FOR_BLOB_DATA, QT_TRANSLATE_NOOP("system", "Kein Puffer für Blobdaten von Variable #1 vorhanden")},
{NOT_CONNECTED, QT_TRANSLATE_NOOP("system", "Keine Verbindung zur SPS #1")},
{NO_SUCH_JOB, QT_TRANSLATE_NOOP("system", "Job #1 ist nicht vorhanden")},
{OBJECT_SERIALIZE_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "Der Puffer zum Serialisieren des Objekts ist zu klein")},
{OBJECT_SERIALIZE_STRING_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "Der Puffer zum Serialisieren eines Strings im Objekt ist zu klein")},
{DOWNLOAD_MESSAGE, QT_TRANSLATE_NOOP("system", "Daten werden zur SPS geschickt")},
{DOWNLOAD_NO_CONNECTION, QT_TRANSLATE_NOOP("system", "Keine Verbindung zur SPS beim Download")},
{DOWNLOAD_UNKNOWN_ERROR, QT_TRANSLATE_NOOP("system", "Unbekannter Fehler beim Download")},
{ERR_MIN_VALUE, QT_TRANSLATE_NOOP("system", "Wert zu klein Minimum ist #1")},
{ERR_MAX_VALUE, QT_TRANSLATE_NOOP("system", "Wert zu groß Maximum ist #1")},
{CCS_SERVICE_CUSTOM_INIT, QT_TRANSLATE_NOOP("system", "Fehler in Initialisierungsschritt #1: #2")},
{ERR_FUNCTION_CALL, QT_TRANSLATE_NOOP("system", "Fehler beim Aufruf der benutzerdefinierten Funktion #1: #2")},
{INSUFFICIENT_CURVE_SPACE, QT_TRANSLATE_NOOP("system", "Zu wenig Speicher für Kurve: benötigt: #1 gegeben #2")},
{METHOD_NOT_SUPPORTED, QT_TRANSLATE_NOOP("system", "Methode #1 wird nicht unterstützt")},
{VARREF_DELETE_CACHED, QT_TRANSLATE_NOOP("system", "Versuch die gecachte Variablen Referenz #1 zu zerstören")},
{PARSE_UNIT_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "Einheitenbeschreibung für #3 fehlt in Zeile #1 Spalte #2")},
{GRABBER_SET_CONTRAST, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Kontrasts: #1")},
{GRABBER_SET_BRIGHTNESS, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen der Helligkeit: #1")},
{CLIENT_INTERFACE_NO_MORE_CONNECTIONS_AVAILABLE, QT_TRANSLATE_NOOP("system", "Maximale Anzahl von Client-Verbindungen überschritten Maximum: #1 Aktuell: #2")},
{CLIENT_INTERFACE_CONNECTION_TERMINATED, QT_TRANSLATE_NOOP("system", "Client-Verbindung wurde vom Server beendet")},
{CCS_INIT_FUNCTION_FAILURE, QT_TRANSLATE_NOOP("system", "CCS Initialisierungsfunktion #1 abgebrochen #2")},
{GUI_INIT_FUNCTION_FAILURE, QT_TRANSLATE_NOOP("system", "GUI Initialisierungsfunktion #1 abgebrochen #2")},
{PARSE_VARREF_ALREADY_DECLARED, QT_TRANSLATE_NOOP("system", "Variable #3 ist schon definiert vorhergehende Definition wird ignoriert (Zeile #1, Spalte #2)")},
{PARSE_PARSING_ABORTED, QT_TRANSLATE_NOOP("system", "Übersetzungsvorgang abgebrochen")},
{UPLOAD_MESSAGE, QT_TRANSLATE_NOOP("system", "Daten werden von der SPS geladen")},
{UPLOAD_NO_CONNECTION, QT_TRANSLATE_NOOP("system", "Keine Verbindung zur SPS beim Upload")},
{UPLOAD_UNKNOWN_ERROR, QT_TRANSLATE_NOOP("system", "Unbekannter Fehler beim Upload")},
{FLAT_OBJECT_NO_SPACE, QT_TRANSLATE_NOOP("system", "Speichergröße #1 zu klein für binäres Objekt Minimum ist #2")},
{RING_BUFFER_NO_SPACE, QT_TRANSLATE_NOOP("system", "Speichergröße #1 zu klein für Ringpuffer Minimum ist #2")},
{CACHE_READ_UNCACHED, QT_TRANSLATE_NOOP("system", "Adresse #2 nicht im Cache #1")},
{CELL_UNINITIALIZED, QT_TRANSLATE_NOOP("system", "Zelle ist nicht initialisiert: Datei #1 Zeile #2")},
{VARIABLE_SET_NULL_VALUE, QT_TRANSLATE_NOOP("system", "Set Operation mit ungültigem Wert (null) beim Setzen von #1")},
{BAD_ALLOC, QT_TRANSLATE_NOOP("system", "Fehler beim allokieren von Speicher")},
{BAD_NEW, QT_TRANSLATE_NOOP("system", "Fehler beim konstruieren eines Objekts (new)")},
{GRABBER_SET_VIDEO_MODE, QT_TRANSLATE_NOOP("system", "Fehler beim Setzen des Video-Mode #2: #1")},
{GRABBER_INVALID_VIDEO_MODE, QT_TRANSLATE_NOOP("system", "Ungültiger Video-Mode #1")},
{ORB_POA_INACTIVE,           QT_TRANSLATE_NOOP("system", "Der POA des Object Request Broker #1 ist nicht aktiv")},
{EM63_DIR_NOT_EXIST,         QT_TRANSLATE_NOOP("system", "Euromap 63 Verzeichnis nicht vorhanden oder nicht erreichbar (#1)")},

// new system texts: place here

   {0, NULL}
};

const TEXT_ENTRY_T _SystemTextEn[] = {
// new system texts: place at the end of the table
// this is the english version of the system text table
{UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "unhandled exception (#1,#2,#3,#4)")},
{VARIANT_CONVERSION_ERROR, QT_TRANSLATE_NOOP("system", "#1 can't be converted to #2")},
{FILE_NOT_FOUND, QT_TRANSLATE_NOOP("system", "file #1 missing")},
{JOB_ENTRY_INVALID_PROPERTY_INDEX, QT_TRANSLATE_NOOP("system", "invalid property index #2 while accessing job entry #1")},
{JOB_ENTRY_INVALID_VALUE_INDEX, QT_TRANSLATE_NOOP("system", "invalid value index #2 while accessing job entry #1")},
{JOB_ENTRY_INVALID_PROPERTY, QT_TRANSLATE_NOOP("system", "unknown property #2 while accessing job entry #1")},
{JOB_ENTRY_INVALID_OPERATION, QT_TRANSLATE_NOOP("system", "operation #3 indexed by #2 not allowed while accessing job entry #1")},
{JOB_SPEC_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "invalid #2 while accessing job specification #1")},
{ASYNC_CHANNEL_NULL_OBJECT, QT_TRANSLATE_NOOP("system", "null object in asynchronous channel #1")},
{ASYNC_CHANNEL_INVALID_OBJECT, QT_TRANSLATE_NOOP("system", "invalid object in asynchronous channel #1")},
{ASYNC_CHANNEL_UNKNOWN_MSG_ID, QT_TRANSLATE_NOOP("system", "unknown message code #2 in asynchronous channel #1")},
{INI_FILE_LINE_LENGTH_EXCEEDED, QT_TRANSLATE_NOOP("system", "max line length of #1 in file #2 exceeded")},
{VIRTUAL_METHOD_NOT_IMPLEMENTED, QT_TRANSLATE_NOOP("system", "virtual method #1 in object #2 is not implemented")},
{INVALID_PARAMETER_VALUE, QT_TRANSLATE_NOOP("system", "invalid parameter value #1 in function #2")},
{STATIC_OBJECT_EVENTFUNC_NOTIMPL, QT_TRANSLATE_NOOP("system", "event method in #1 is not implemented. event type is #2")},
{METHOD_NOT_OVERLOADED, QT_TRANSLATE_NOOP("system", "virtual method not overloaded file #1 line #2")},
{CONFIG_FILE_NOT_FOUND, QT_TRANSLATE_NOOP("system", "configuration file #1 missing")},
{CONFIG_NO_CONFIG_OBJECT, QT_TRANSLATE_NOOP("system", "found no configuration object for #1")},
{CONFIG_AMBIGUOUS_OBJECT, QT_TRANSLATE_NOOP("system", "object #1 defined twice")},
{CONFIG_INVALID_TYPEDEF, QT_TRANSLATE_NOOP("system", "type definition #1 of object #2 is missing or invalid")},
{CONFIG_AMBIGUOUS_PROPERTY, QT_TRANSLATE_NOOP("system", "property #1 is defined twice")},
{CONFIG_NO_DEFFILE_SPEC, QT_TRANSLATE_NOOP("system", "no definition file #1 specified (property DefFile)")},
{CONFIG_NO_CONFIGOBJECT_SPEC, QT_TRANSLATE_NOOP("system", "no configuration object in #1 specified (object Configuration)")},
{CONFIG_NO_PROPERTYDEF, QT_TRANSLATE_NOOP("system", "property #1 in object #2 is not defined")},
{CONFIG_NO_TYPEDEF, QT_TRANSLATE_NOOP("system", "property type #1 in object #2 is not defined")},
{CONFIG_INVALID_BASETYPE, QT_TRANSLATE_NOOP("system", "base type #1 of property #2 in object #3 is invalid")},
{CONFIG_PROPERTY_ALREADY_RESOLVED, QT_TRANSLATE_NOOP("system", "property #1 is already resolved")},
{CONFIG_UNABLE_TO_RESOLVE_OBJECT, QT_TRANSLATE_NOOP("system", "object #1 cannot be resolved")},
{CONFIG_UNKNOWN_TYPEDEF, QT_TRANSLATE_NOOP("system", "unknown type definition #1 for property #2")},
{CONFIG_AMBIGUOUS_BASETYPE, QT_TRANSLATE_NOOP("system", "base type for #1 defined twice")},
{CONFIG_AMBIGUOUS_RANGETYPE, QT_TRANSLATE_NOOP("system", "base type (range type) for #1 defined twice")},
{CONFIG_CANNOT_SET_RANGE, QT_TRANSLATE_NOOP("system", "range specification #2 for #1 invalid")},
{CONFIG_UNDEFINED_BASETYPE, QT_TRANSLATE_NOOP("system", "base type for #1 id undefined")},
{CONFIG_INVALID_TYPESPEC, QT_TRANSLATE_NOOP("system", "invalid type specification #1 for #2")},
{CONFIG_NO_TYPESPEC, QT_TRANSLATE_NOOP("system", "no type specification for #1")},
{CONFIG_AMBIGUOUS_TYPEDEF, QT_TRANSLATE_NOOP("system", "type #1 is defined twice")},
{CONFIG_OBJECT_TYPE_MISMATCH, QT_TRANSLATE_NOOP("system", "property #1 of object #2 must refer to objects of type #3 (#4)")},
{CONFIG_NO_SCALAR, QT_TRANSLATE_NOOP("system", "property #1 of object #2 is no L-value")},
{CONFIG_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "type of property #1 of object #2 is invalid (#3)")},
{CONFIG_NO_VALUE, QT_TRANSLATE_NOOP("system", "no value for property #1 of object #2")},
{CONFIG_NO_VECTOR, QT_TRANSLATE_NOOP("system", "property #1 of object #2 is kein Vektor")},
{CONFIG_INVALID_VALUE, QT_TRANSLATE_NOOP("system", "invalid value #1 for property #2 of object #3")},
{CONFIG_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "invalid index while accessing property #1 of object #2")},
{CONFIG_NOT_NUMERIC, QT_TRANSLATE_NOOP("system", "value for property #1 of object #2 is not numeric (#3)")},
{CONFIG_INVALID_BOOL_SPEC, QT_TRANSLATE_NOOP("system", "value for property #1 of object #2 is no bool value (#3)")},
{CONFIG_NO_PROPVAL, QT_TRANSLATE_NOOP("system", "property #1 of object #2 must be specified")},
{VALUE_NO_TYPEDEF, QT_TRANSLATE_NOOP("system", "type of value #1 is not defined")},
{VALUE_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "invalid type #2 for Zugriff auf value #1")},
{ORB_BROKER_INACTIVE, QT_TRANSLATE_NOOP("system", "orb is not active (not yet started)")},
{ORB_BROKER_ACTIVE, QT_TRANSLATE_NOOP("system", "orb already active (already started)")},
{ORB_START_FAILURE, QT_TRANSLATE_NOOP("system", "failed to start orb #1")},
{ORB_ORB_INACTIVE, QT_TRANSLATE_NOOP("system", "ORB of broker  #1 inactive")},
{ORB_BOA_INACTIVE, QT_TRANSLATE_NOOP("system", "BOA broker #1 inactive")},
{SOCKET_SETSOCKOPT, QT_TRANSLATE_NOOP("system", "failed to set socket options #3 for #1/#2")},
{SOCKET_VERSION, QT_TRANSLATE_NOOP("system", "invalid version of winsock DLL #1/#2")},
{SOCKET_CREATE, QT_TRANSLATE_NOOP("system", "failed to create socket #1/#2")},
{SOCKET_RECVFROM, QT_TRANSLATE_NOOP("system", "socket error while receiving on #1/#2 #3")},
{SOCKET_SENDTO, QT_TRANSLATE_NOOP("system", "socket error while sending to #1/#2")},
{SOCKET_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "receive buffer full socket on #1/#2 (#4 < #3)")},
{SOCKET_STARTUP, QT_TRANSLATE_NOOP("system", "socket subsystem cannot gestartet werden")},
{SOCKET_BIND, QT_TRANSLATE_NOOP("system", "socket error in bind #1/#2")},
{PROXY_UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "unknown error accessing proxy: #1")},
{PROXY_NO_INTERFACE, QT_TRANSLATE_NOOP("system", "proxy not initialized in #1")},
{PROXY_NO_OBJECT_INTERFACE, QT_TRANSLATE_NOOP("system", "object exposes no interface for #1")},
{PROXY_NO_OBJECT, QT_TRANSLATE_NOOP("system", "no access to object via #1")},
{PROXY_CORBA_SYSTEM, QT_TRANSLATE_NOOP("system", "CORBA system error accessing #1")},
{PROXY_TYPE_MISMATCH, QT_TRANSLATE_NOOP("system", "type mismatch when refreshing proxy data of #1 (#2 != #3)")},
{CORBA_UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "unknown error while calling method #1")},
{CONSOLE_INVALID_DIRECTION, QT_TRANSLATE_NOOP("system", "invalid direction for console #1")},
{FACTORY_INVALID_VALUE, QT_TRANSLATE_NOOP("system", "invalid value #1 creating an object of type #2")},
{CHANNEL_WRAPPER_START_PROCESS, QT_TRANSLATE_NOOP("system", "failed to start process #1 #2 (#3)")},
{CHANNEL_WRAPPER_NO_CONTACT, QT_TRANSLATE_NOOP("system", "failed to connect to event channel object #1")},
{PROXY_RECEIVER_UNKNOWN_POT, QT_TRANSLATE_NOOP("system", "unknown proxy type #1 in proxy receiver #2 #3")},
{PROXY_RECEIVER_FAILED_TO_CONSTRUCT, QT_TRANSLATE_NOOP("system", "failed to create in receiver #1 #2")},
{OBJECT_PARSER_FAILURE, QT_TRANSLATE_NOOP("system", "parser object: failed to interprete object #1")},
{OBJECT_PARSER_CONSTRUCT_HEADER, QT_TRANSLATE_NOOP("system", "parser object: failed to construct header of object #1")},
{OBJECT_PARSER_INVALID_OBJECTTYPE, QT_TRANSLATE_NOOP("system", "parser object: invalid object type #1 in header #2")},
{OBJECT_PARSER_INVALID_SUBTYPE1, QT_TRANSLATE_NOOP("system", "parser object: invalid type 1 #1 in header #2")},
{OBJECT_PARSER_INVALID_SUBTYPE2, QT_TRANSLATE_NOOP("system", "parser object: invalid type 2 #1 in header #2")},
{EVENT_CHANNEL_NO_CHANNEL, QT_TRANSLATE_NOOP("system", "event channel #1 not available")},
{CYCLEBUF_COLUMN_INDEX_INVALID, QT_TRANSLATE_NOOP("system", "no column with index #1 in cycle buffer")},
{CYCLEBUF_COLUMN_NAME_INVALID, QT_TRANSLATE_NOOP("system", "no column with name #1 in cycle buffer")},
{CYCLEBUF_ROW_INVALID, QT_TRANSLATE_NOOP("system", "no line with index #1 in cycle buffer")},
{CYCLEBUF_ROW_COUNT, QT_TRANSLATE_NOOP("system", "invalid size specification in cycle buffer (#1 > #2)")},
{SOCKET_CHANNEL_NO_PORT_NAME, QT_TRANSLATE_NOOP("system", "no port name for W&T-channel #1")},
{SOCKET_CHANNEL_NO_SERIAL_PORT, QT_TRANSLATE_NOOP("system", "no port for W&T-channel #1 (A,B,C,D)")},
{SOCKET_CHANNEL_INVALID_SERIAL_PORT, QT_TRANSLATE_NOOP("system", "invalid port #2 for W&T-channel #1 (A,B,C,D)")},
{SOCKET_CHANNEL_NO_IP_ADDRESS, QT_TRANSLATE_NOOP("system", "no IP-address for W&T-channel #1")},
{SOCKET_CHANNEL_BAD_IP_ADDRESS, QT_TRANSLATE_NOOP("system", "invalid IP-address #2 for W&T-channel #1")},
{STDSER_NO_PORT_NAME, QT_TRANSLATE_NOOP("system", "no port name for serial interface")},
{STDSER_PORT_NAME_SIZE, QT_TRANSLATE_NOOP("system", "port name length #1 exceeds maximum")},
{STDSER_INVALID_HANDLE, QT_TRANSLATE_NOOP("system", "invalid handle accessing interface #1")},
{STDSER_SET_COMM_STATE, QT_TRANSLATE_NOOP("system", "error setting communication parameters on port #1")},
{STDSER_GET_COMM_STATE, QT_TRANSLATE_NOOP("system", "error reading communication parameters on port #1")},
{STDSER_CREATE_FILE, QT_TRANSLATE_NOOP("system", "error while opening interface on port #1")},
{STDSER_SET_COMM_TIMEOUTS, QT_TRANSLATE_NOOP("system", "error reading timeout parameter of port #1")},
{STDSER_GET_COMM_TIMEOUTS, QT_TRANSLATE_NOOP("system", "error setting timeout parameter of port #1")},
{STDSER_CLEAR_COMM_ERROR, QT_TRANSLATE_NOOP("system", "error resetting error conditions on port #1")},
{STDSER_WRITE_FILE, QT_TRANSLATE_NOOP("system", "error writing data of port #1")},
{STDSER_READ_FILE, QT_TRANSLATE_NOOP("system", "error reading data to port #1")},
{DIGIO_INVALID_CARDTYPE, QT_TRANSLATE_NOOP("system", "invalid card type #1")},
{PA150_OPEN, QT_TRANSLATE_NOOP("system", "error while opening PA150 in digital channel #1")},
{PA150_READ1_INPUT, QT_TRANSLATE_NOOP("system", "error reading input #1 in PA150 in digital channel #2")},
{PA150_READ16_INPUT, QT_TRANSLATE_NOOP("system", "error reading inputs in PA150 in digital channel #1")},
{PA150_SET1_OUTPUT_ON, QT_TRANSLATE_NOOP("system", "error setting output #1 in PA150 in digital channel #2")},
{PA150_SET1_OUTPUT_OFF, QT_TRANSLATE_NOOP("system", "error while resetting output #1 in PA150 in digital channel #2")},
{ADDI_UNIVERSAL_OPEN, QT_TRANSLATE_NOOP("system", "error while opening ADDI_UNIVERSAL in digital channel #1")},
{ADDI_UNIVERSAL_READ1_INPUT, QT_TRANSLATE_NOOP("system", "error reading input #1 in ADDI_UNIVERSAL in digital channel #2")},
{ADDI_UNIVERSAL_READ_INPUTS, QT_TRANSLATE_NOOP("system", "error reading inputs in ADDI_UNIVERSAL in digital channel #1")},
{ADDI_UNIVERSAL_SET1_OUTPUT_ON, QT_TRANSLATE_NOOP("system", "error setting output #1 in ADDI_UNIVERSAL in digital channel #2")},
{ADDI_UNIVERSAL_SET1_OUTPUT_OFF, QT_TRANSLATE_NOOP("system", "error while resetting output #1 in ADDI_UNIVERSAL in digital channel #2")},
{ADDI_UNIVERSAL_GET_INPUT_NO, QT_TRANSLATE_NOOP("system", "error reading number of outputs in ADDI_UNIVERSAL in digital channel #1")},
{ADDI_UNIVERSAL_GET_OUTPUT_NO, QT_TRANSLATE_NOOP("system", "error reading number of outputs in ADDI_UNIVERSAL in digital channel #1")},
{ADDI_UNIVERSAL_SET_OUTPUT_MEM, QT_TRANSLATE_NOOP("system", "error while initializing memory of ADDI_UNIVERSAL in digital channel #1")},
{ADDI_UNIVERSAL_INVALID_NOOFINPUTS, QT_TRANSLATE_NOOP("system", "invalid number of inputs #1 in ADDI_UNIVERSAL in digital channel #2")},
{DRIVER_NOT_CONNECTED, QT_TRANSLATE_NOOP("system", "no connection zu #1")},
{DRIVER_READ_SUBTRACTING_SHOTCOUNT, QT_TRANSLATE_NOOP("system", "unknown error reading subtracting shot counter in #1")},
{DRIVER_READ_ADDING_SHOTCOUNT, QT_TRANSLATE_NOOP("system", "unknown error reading adding shot counter in #1")},
{DRIVER_RCV_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "receive buffer overflow in #1")},
{DRIVER_NO_BUFFER, QT_TRANSLATE_NOOP("system", "no physical buffer for index #1 in #2")},
{DRIVER_INVALID_PHYS_SPEC, QT_TRANSLATE_NOOP("system", "physical buffer specification #1 in driver #2 unknown")},
{VIRTDATA_ITEM_EXISTS, QT_TRANSLATE_NOOP("system", "virtual variable #1 already defined in #2")},
{VIRTDATA_ITEM_NOT_FOUND, QT_TRANSLATE_NOOP("system", "virtual variable #1 unknown in #2")},
{FM_MACHINE_ERROR, QT_TRANSLATE_NOOP("system", "machine #1 signals error condition #2 on request #3")},
{FM_ABORT, QT_TRANSLATE_NOOP("system", "communication aborted by machine in #1")},
{FM_CR_LF_ERROR, QT_TRANSLATE_NOOP("system", "CR LF expected in #1")},
{FM_CHECKSUM_ERROR, QT_TRANSLATE_NOOP("system", "checksum error in #1")},
{FM_MISSING_ETX, QT_TRANSLATE_NOOP("system", "ETX expected in #1")},
{FM_RCV_CHAR_TIMEOUT, QT_TRANSLATE_NOOP("system", "timeout when receiving a character in #1")},
{FM_CONTACT_RETRIES, QT_TRANSLATE_NOOP("system", "retries while contacting exceeded in #1")},
{FM_BLK_RETRIES_1, QT_TRANSLATE_NOOP("system", "retries while block transmission state 1 exceeded in #1")},
{FM_CHAR_TIMEOUT_5, QT_TRANSLATE_NOOP("system", "timeout when receiving a character in state 5 in #1")},
{FM_UNDEF_CHAR_5, QT_TRANSLATE_NOOP("system", "unexpected character in state 5 received in #1")},
{FM_BLK_RETRIES_2, QT_TRANSLATE_NOOP("system", "retries while block transmission state 2 exceeded in #1")},
{FM_CHAR_TIMEOUT_10, QT_TRANSLATE_NOOP("system", "timeout when receiving a character in state 10 in #1")},
{FM_UNDEF_CHAR_10, QT_TRANSLATE_NOOP("system", "unexpected character in state 10 received in #1")},
{FM_BLK_RETRIES_3, QT_TRANSLATE_NOOP("system", "retries while block transmission state 3 exceeded in #1")},
{FM_UNDEF_CHAR_13, QT_TRANSLATE_NOOP("system", "unexpected character in state 13 received in #1")},
{FM_CHAR_TIMEOUT_15, QT_TRANSLATE_NOOP("system", "timeout when receiving a character in state 15 in #1")},
{FM_UNDEF_CHAR_15, QT_TRANSLATE_NOOP("system", "unexpected character in state 15 received in #1")},
{FM_BLK_RETRIES_4, QT_TRANSLATE_NOOP("system", "retries while block transmission state 4 exceeded in #1")},
{FM_RCV_COMM_ABORTED, QT_TRANSLATE_NOOP("system", "communication to machine aborted in #1")},
{FM_ECHO, QT_TRANSLATE_NOOP("system", "erroneous echo received in #1")},
{FM_UNKNOWN_COMMAND, QT_TRANSLATE_NOOP("system", "unknown command #1 in #2")},
{FM_MS_SYNTAX, QT_TRANSLATE_NOOP("system", "failed to interprete machine state in #1 #2")},
{FM_TB_SYNTAX, QT_TRANSLATE_NOOP("system", "failed to interprete cycle buffer in #1 #2")},
{FM_CB_SYNTAX, QT_TRANSLATE_NOOP("system", "failed to interprete error buffer in #1 #2")},
{FM_EB_SYNTAX, QT_TRANSLATE_NOOP("system", "failed to interprete error buffer in #1 #2")},
{FM_MS_ERROR, QT_TRANSLATE_NOOP("system", "error interpreting machine state in #1 #2")},
{FM_TB_ERROR, QT_TRANSLATE_NOOP("system", "error interpreting cycle buffer in #1 #2")},
{FM_CB_ERROR, QT_TRANSLATE_NOOP("system", "error interpreting error buffer in #1 #2")},
{FM_EB_ERROR, QT_TRANSLATE_NOOP("system", "error interpreting error buffer in #1 #2")},
{VARIABLE_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "invalid index #2 accessing variable #1 at position #3 maximum is #4")},
{VARIABLE_INVALID_DIM, QT_TRANSLATE_NOOP("system", "invalid index position #2 accessing variable #1 (#3 dimensions)")},
{VARIABLE_NOT_FOUND, QT_TRANSLATE_NOOP("system", "variable #1 not found")},
{VARIABLE_NO_MAPPING, QT_TRANSLATE_NOOP("system", "no mapping for variable #1 position #2")},
{VARIABLE_NO_MAP_ITEM, QT_TRANSLATE_NOOP("system", "no map element for variable #1 position #2")},
{VARIABLE_NO_DEVICE, QT_TRANSLATE_NOOP("system", "no device for variable mapping #1 position #2")},
{VARIABLE_READ_ONLY, QT_TRANSLATE_NOOP("system", "variable #1 not writeable")},
{VARIABLE_NULL_MAPPING, QT_TRANSLATE_NOOP("system", "null mapping for variable #1 position #2")},
{FUNC_INVALID_PARAMPOS, QT_TRANSLATE_NOOP("system", "invalid parameter position #2 accessing function")},
{PARSE_FUNCREF_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "function #3 is not declared (line #1, column #2)")},
{PARSE_FUNCREF_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "invalid type of function #3 in reference (line #1, column #2)")},
{PARSE_FUNCREF_TOO_MUCH_PARAMS, QT_TRANSLATE_NOOP("system", "too much parameters in function reference of #3 (line #1, column #2)")},
{PARSE_FUNCREF_TOO_FEW_PARAMS, QT_TRANSLATE_NOOP("system", "too few parameters in function reference of #3 (line #1, column #2)")},
{PARSE_FUNCREF_INVALID_PARAMTYPE, QT_TRANSLATE_NOOP("system", "invalid parameter type at position #4 in function reference of #3 (line #1, column #2)")},
{PARSE_FUNCREF_NO_PARAMTYPE, QT_TRANSLATE_NOOP("system", "parameter type at position #4 in function reference of #3 cannot ermittelt werden (line #1, column #2)")},
{PARSE_TYPES_NOT_COMPATIBLE, QT_TRANSLATE_NOOP("system", "invalid type usage. expected: #3, used: #4 (line #1, column #2)")},
{PARSE_FUNCREF_INVALID_CLASS, QT_TRANSLATE_NOOP("system", "invalid function class: expected: #3, used: #4 (line #1, column #2)")},
{PARSE_BITPOS, QT_TRANSLATE_NOOP("system", "invalid Bitposition: #3 (line #1, column #2)")},
{PARSE_BITPOS_SPECIFICATION, QT_TRANSLATE_NOOP("system", "invalid bitposition: #3 (line #1, column #2)")},
{PARSE_VARREF_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "variable #3 is not defined (line #1, column #2)")},
{PARSE_VARREF_INVALID_INDEX, QT_TRANSLATE_NOOP("system", "invalid index for variable #3 in reference (line #1, column #2)")},
{PARSE_VARREF_TOO_MUCH_INDICES, QT_TRANSLATE_NOOP("system", "too much indices in variable reference of #3 (line #1, column #2)")},
{PARSE_VARREF_TOO_FEW_INDICES, QT_TRANSLATE_NOOP("system", "too few indices in variable reference of #3 (line #1, column #2)")},
{PARSE_VARREF_INVALID_TYPE, QT_TRANSLATE_NOOP("system", "invalid type for index of variable #3 in reference (line #1, column #2)")},
{PARSE_VARREF_NO_INDEX, QT_TRANSLATE_NOOP("system", "index type for index #4 of variable #3 unknown (line #1, column #2)")},
{PARSE_SYMBOL_RESOLVE, QT_TRANSLATE_NOOP("system", "symbol #3 cannot be resolved (line #1, column #2)")},
{PARSE_SYNTAX_ERRORS_IN_FILE, QT_TRANSLATE_NOOP("system", "syntax error in file #1 line #2 column #3")},
{PARSE_SYNTAX_ERRORS_IN_STRING, QT_TRANSLATE_NOOP("system", "syntax error line #2 column #3 in text: #1")},
{VARREF_NO_VARIABLE, QT_TRANSLATE_NOOP("system", "variable reference #1 does not reference a variable")},
{FUNCREF_FAILED_TO_RESOLVE, QT_TRANSLATE_NOOP("system", "function #1 cannot be resolved")},
{FUNCREF_FUNCTION_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "function #1 is not declared")},
{FUNCREF_FUNCTION_NOT_RESOLVED, QT_TRANSLATE_NOOP("system", "function #1 is not implemented")},
{FUNCREF_PARAMETER_TYPE_NOT_SUPPORTED, QT_TRANSLATE_NOOP("system", "data type #1 in parameter #2 is not supported")},
{CELL_NO_DIGITALIO, QT_TRANSLATE_NOOP("system", "no digitale I/O configured (required for #1)")},
{CELL_NO_DRIVER, QT_TRANSLATE_NOOP("system", "no driver for variable #1")},
{CELL_CYCLESPEC_DRIVER_UNKNOWN, QT_TRANSLATE_NOOP("system", "variable #2 at position #1 of cycle buffer of #3 does not reference a device")},
{CELL_NO_DISPATCHER, QT_TRANSLATE_NOOP("system", "no dispatcher channel available")},
{CELL_NO_FAST_CHANNEL, QT_TRANSLATE_NOOP("system", "no fast channel available")},
{CELL_CREATE_DEVICE, QT_TRANSLATE_NOOP("system", "cannot create device object #1")},
{CELL_CREATE_PROGRAM, QT_TRANSLATE_NOOP("system", "cannot create program object #1")},
{CELL_UNKNOWN_PROGRAM, QT_TRANSLATE_NOOP("system", "program #1 unknown")},
{PROGRAM_UNKNOWN_IOSIGNAL, QT_TRANSLATE_NOOP("system", "tried to access unknown I/O-signal #1 in program #1")},
{PROGRAMMABLE_COMMAND_UNKNOWN, QT_TRANSLATE_NOOP("system", "command #1 in device #2 unknown")},
{PROGRAMMABLE_SYNTAX_ERROR, QT_TRANSLATE_NOOP("system", "syntax error in program #1 for driver #2")},
{PROGRAMMABLE_UNKNOWN_DATA_TYPE, QT_TRANSLATE_NOOP("system", "unknown data type #1 in program for driver #2")},
{PROGRAMMABLE_INVALID_FORMAT_SPEC, QT_TRANSLATE_NOOP("system", "invalid format specification #1 in program for driver #2")},
{PROGRAMMABLE_INVALID_CONSTRAINT, QT_TRANSLATE_NOOP("system", "invalid constraint specifikation #1 in program for driver #2")},
{PROGRAMMABLE_CONSTRAINT, QT_TRANSLATE_NOOP("system", "constraint #1 vioplated in driver #2")},
{MAPPING_INVALID_ADDRESS, QT_TRANSLATE_NOOP("system", "invalid address #1 in mapping of variable #2")},
{MAPPING_INVALID_MAPPING_TYPE, QT_TRANSLATE_NOOP("system", "invalid mapping type at position #2 of variable #1")},
{MAPPING_INVALID_MAPITEM_POS, QT_TRANSLATE_NOOP("system", "invalid position for map item #1/#2")},
{DATA_OBJECT_VARIABLE_NOT_CREATED, QT_TRANSLATE_NOOP("system", "variable #1 not instantiated")},
{MODBUS_HREGS_NO_RESPONSE, QT_TRANSLATE_NOOP("system", "no response for register #2 in #1")},
{MODBUS_HREGS_INVALID_NODE, QT_TRANSLATE_NOOP("system", "invalid node number in response for register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_INVALID_FUNCTION, QT_TRANSLATE_NOOP("system", "invalid function in response for register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_INVALID_BYTE_COUNT, QT_TRANSLATE_NOOP("system", "invalid size in response for register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_RESPONSE_TOO_SHORT, QT_TRANSLATE_NOOP("system", "invalid response length in response for register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_RESPONSE_CRC_ERROR, QT_TRANSLATE_NOOP("system", "invalid CRC in response for register #2 in #1 (#3,#4)")},
{MODBUS_HREGS_BUFFER_TOO_SHORT, QT_TRANSLATE_NOOP("system", "buffer size too small for #3 (#4) register in #1 transferring address data #2")},
{CARRIER_UNHANDLED_EXCEPTION, QT_TRANSLATE_NOOP("system", "unhandled exception accessing die carrier interface")},
{CARRIER_DEVICE_ACCESS, QT_TRANSLATE_NOOP("system", "error accessing carrier")},
{STRING_CACHE_TOO_MUCH_ELEMENTS, QT_TRANSLATE_NOOP("system", "at most one element can be read from a string cache")},
{DEVICE_INVALID_MEMORY_ORGANIZATION, QT_TRANSLATE_NOOP("system", "invalid size of memory management for device #1 memory #2: #3")},
{DEVICE_INVALID_DATATYPE, QT_TRANSLATE_NOOP("system", "invalid data type #1 for bitoperator")},
{DEVICE_INVALID_GRANULARITY, QT_TRANSLATE_NOOP("system", "invalid element size in memory management #1 for bitoperator")},
{DEVICE_NO_MEMORY_INFO, QT_TRANSLATE_NOOP("system", "no information concerning buffer specification #1")},
{DEVICE_NOT_CONNECTED, QT_TRANSLATE_NOOP("system", "no connection zu #1")},
{GRABBER_OPEN_DEVICE, QT_TRANSLATE_NOOP("system", "error while opening camera: #1")},
{GRABBER_INIT_BOARD, QT_TRANSLATE_NOOP("system", "error while initializing camera: #1")},
{GRABBER_BOARD_INFO, QT_TRANSLATE_NOOP("system", "error querying board info of camera: #1")},
{GRABBER_SENSOR_INFO, QT_TRANSLATE_NOOP("system", "error beim requesting sensor info of camera: #1")},
{GRABBER_SET_DISPLAY_MODE, QT_TRANSLATE_NOOP("system", "error setting display mode of camera #2: #1")},
{GRABBER_SET_COLOR_MODE, QT_TRANSLATE_NOOP("system", "error setting colour mode of camera #2: #1")},
{GRABBER_SET_IMAGE_SIZE, QT_TRANSLATE_NOOP("system", "error setting resolution of camera (#2,#3): #1")},
{GRABBER_SET_CAPTURE_MODE, QT_TRANSLATE_NOOP("system", "error setting capture mode of camera #2: #1")},
{GRABBER_CAPTURE_VIDEO, QT_TRANSLATE_NOOP("system", "error while activating sample mode of camera: #1")},
{GRABBER_ALLOC_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "error while requesting video buffer for pixel size #2 : #1")},
{GRABBER_SET_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "error setting video buffer: #1")},
{GRABBER_FREE_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "error releasing video buffer: #1")},
{GRABBER_COPY_IMAGE_MEM, QT_TRANSLATE_NOOP("system", "error while copying video buffer: #1")},
{GRABBER_SET_VIDEO_INPUT, QT_TRANSLATE_NOOP("system", "error setting video input channel #2: #1")},
{GRABBER_INVALID_CHANNEL, QT_TRANSLATE_NOOP("system", "invalid video channel #1")},
{TRAEGER_S7_OPEN, QT_TRANSLATE_NOOP("system", "error while opening Traeger-S7-driver Com: #1 PLC address #2 Client address #3")},
{TRAEGER_S7_READ, QT_TRANSLATE_NOOP("system", "error reading from Traeger-S7-driver Com: #1 command #2 address #3 Länge #4")},
{TRAEGER_S7_WRITE, QT_TRANSLATE_NOOP("system", "error writing to Traeger-S7-driver Com: #1 command #2 address #3 Länge #4")},
{I60_READ, QT_TRANSLATE_NOOP("system", "error in I60Load #1: command #2 address #3 Länge #4")},
{I60_WRITE, QT_TRANSLATE_NOOP("system", "error in I60Save #1: command #2 address #3 Länge #4")},
{SHARED_LIBRARY_LOAD, QT_TRANSLATE_NOOP("system", "error loading shared library #1")},
{SHARED_FUNCTION_LOAD, QT_TRANSLATE_NOOP("system", "error loading shared function #2 aus Bibliothek #1")},
{STEPPER_READ_ONLY, QT_TRANSLATE_NOOP("system", "write operation on write-protected data #2 of #1-axis")},
{STEPPER_MIN_VALUE, QT_TRANSLATE_NOOP("system", "parameter value too small for parameter #2 axis #1: #3 minimum is #4")},
{STEPPER_MAX_VALUE, QT_TRANSLATE_NOOP("system", "parameter value too big for parameter #2 axis #1: #3 maximum is #4")},
{STEPPER_DLL_LOAD, QT_TRANSLATE_NOOP("system", "error loading DLL #1 for stepper control")},
{STEPPER_TARGET_TIMEOUT, QT_TRANSLATE_NOOP("system", "timeout waiting for position #2 on axis #1")},
{STEPPER_LOAD_PROC, QT_TRANSLATE_NOOP("system", "error loading function #2 from DLL #1 for stepper control")},
{STEPPER_WRITE_ONLY, QT_TRANSLATE_NOOP("system", "data #2 of #1-axis cannot be read (write only)")},
{STEPPER_SETREG, QT_TRANSLATE_NOOP("system", "internal error in function SetReg of DLL #1")},
{STEPPER_GETREG, QT_TRANSLATE_NOOP("system", "internal error in function GetReg of DLL #1")},
{IMAGE_BUFFER_TOO_SMALL, QT_TRANSLATE_NOOP("system", "buffer size for image data is too small: required #1 current #2")},
{FAILED_TO_WRITE_DEVICE_BLOB_DATA, QT_TRANSLATE_NOOP("system", "blob data of variable #1 can not be written to device")},
{NO_BUFFER_FOR_BLOB_DATA, QT_TRANSLATE_NOOP("system", "no buffer for blob data of variable #1 vorhanden")},
{NOT_CONNECTED, QT_TRANSLATE_NOOP("system", "no connection to PLC #1")},
{NO_SUCH_JOB, QT_TRANSLATE_NOOP("system", "job #1 is nicht vorhanden")},
{OBJECT_SERIALIZE_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "serialization buffer of object is too small")},
{OBJECT_SERIALIZE_STRING_BUF_TOO_SMALL, QT_TRANSLATE_NOOP("system", "serialization buffer of a string in object is too small")},
{DOWNLOAD_MESSAGE, QT_TRANSLATE_NOOP("system", "data is sent to PLC")},
{DOWNLOAD_NO_CONNECTION, QT_TRANSLATE_NOOP("system", "no connection to PLC while sending data")},
{DOWNLOAD_UNKNOWN_ERROR, QT_TRANSLATE_NOOP("system", "unknown error while sending data")},
{ERR_MIN_VALUE, QT_TRANSLATE_NOOP("system", "value too small minimum is #1")},
{ERR_MAX_VALUE, QT_TRANSLATE_NOOP("system", "value too big maximum is #1")},
{CCS_SERVICE_CUSTOM_INIT, QT_TRANSLATE_NOOP("system", "error in initialzation step #1: #2")},
{ERR_FUNCTION_CALL, QT_TRANSLATE_NOOP("system", "error calling user defined function #1: #2")},
{INSUFFICIENT_CURVE_SPACE, QT_TRANSLATE_NOOP("system", "no memory for curve: required: #1 gegeben #2")},
{METHOD_NOT_SUPPORTED, QT_TRANSLATE_NOOP("system", "method #1 is not supported")},
{VARREF_DELETE_CACHED, QT_TRANSLATE_NOOP("system", "tried to delete cached variable reference #1")},
{PARSE_UNIT_NOT_DECLARED, QT_TRANSLATE_NOOP("system", "missing unit specification for #3 in line #1 column #2")},
{GRABBER_SET_CONTRAST, QT_TRANSLATE_NOOP("system", "failed to set contrast: #1")},
{GRABBER_SET_BRIGHTNESS, QT_TRANSLATE_NOOP("system", "failed to set brightness: #1")},
{CLIENT_INTERFACE_NO_MORE_CONNECTIONS_AVAILABLE, QT_TRANSLATE_NOOP("system", "no more client connections available max is #1 current #2")},
{CLIENT_INTERFACE_CONNECTION_TERMINATED, QT_TRANSLATE_NOOP("system", "client connection shutdown by server")},
{CCS_INIT_FUNCTION_FAILURE, QT_TRANSLATE_NOOP("system", "CCS init function #1 failed #2")},
{GUI_INIT_FUNCTION_FAILURE, QT_TRANSLATE_NOOP("system", "GUI init function #1 failed #2")},
{PARSE_VARREF_ALREADY_DECLARED, QT_TRANSLATE_NOOP("system", "variable #3 already defined previous definition ignored (line #1, column #2)")},
{PARSE_PARSING_ABORTED, QT_TRANSLATE_NOOP("system", "parsing process aborted")},
{UPLOAD_MESSAGE, QT_TRANSLATE_NOOP("system", "data is loaded from PLC")},
{UPLOAD_NO_CONNECTION, QT_TRANSLATE_NOOP("system", "no connection to PLC while loading data")},
{UPLOAD_UNKNOWN_ERROR, QT_TRANSLATE_NOOP("system", "unknown error while loading data")},
{FLAT_OBJECT_NO_SPACE, QT_TRANSLATE_NOOP("system", "inappropriate size #1 for binary object #2 required at minimum")},
{RING_BUFFER_NO_SPACE, QT_TRANSLATE_NOOP("system", "inappropriate size #1 for ringbuffer #2 required at minimum")},
{CACHE_READ_UNCACHED, QT_TRANSLATE_NOOP("system", "address #2 not registered in cache #1")},
{CELL_UNINITIALIZED, QT_TRANSLATE_NOOP("system", "Cell not initialized: file #1 line #2")},
{VARIABLE_SET_NULL_VALUE, QT_TRANSLATE_NOOP("system", "invalid value (null) when setting #1")},
{BAD_ALLOC, QT_TRANSLATE_NOOP("system", "failed to allocate memory")},
{BAD_NEW, QT_TRANSLATE_NOOP("system", "failed to construct an object (new)")},
{GRABBER_SET_VIDEO_MODE, QT_TRANSLATE_NOOP("system", "failed to set video mode to #2: #1")},
{GRABBER_INVALID_VIDEO_MODE, QT_TRANSLATE_NOOP("system", "invalid video mode #1")},
{ORB_POA_INACTIVE,           QT_TRANSLATE_NOOP("system", "POA broker #1 inactive")},
{EM63_DIR_NOT_EXIST,         QT_TRANSLATE_NOOP("system", "Euromap 63 directory not existent or not reachable (#1)")},

// new system texts: place here

   {0, NULL}
};

