

#ifndef _SystemText_h_
#define _SystemText_h_

typedef struct text_entry {
   ULONG_T text_id;
   CONST_STRING_T text;
}  TEXT_ENTRY_T;
extern const TEXT_ENTRY_T _SystemText[];
extern const TEXT_ENTRY_T _SystemTextEn[];

#define START_SYSTEM_TEXT     100
#define START_CUSTOM_TEXT     5000

#define SYSTEM_MESSAGE(id) (id + START_SYSTEM_TEXT)
#define CUSTOM_MESSAGE(id) (id + START_CUSTOM_TEXT)

#ifdef _NO_QT_

#ifndef QT_TR_NOOP
#define QT_TR_NOOP(x) (x)
#endif

#ifndef QT_TRANSLATE_NOOP
#define QT_TRANSLATE_NOOP(c,x) (x)
#endif

#else

#include <qobject.h>

#endif

// new constant definitions for system texts: place at the end of the file

#define UNHANDLED_EXCEPTION	100
#define VARIANT_CONVERSION_ERROR	101
#define FILE_NOT_FOUND	102
#define JOB_ENTRY_INVALID_PROPERTY_INDEX	103
#define JOB_ENTRY_INVALID_VALUE_INDEX	104
#define JOB_ENTRY_INVALID_PROPERTY	105
#define JOB_ENTRY_INVALID_OPERATION	106
#define JOB_SPEC_INVALID_INDEX	107
#define ASYNC_CHANNEL_NULL_OBJECT	108
#define ASYNC_CHANNEL_INVALID_OBJECT	109
#define ASYNC_CHANNEL_UNKNOWN_MSG_ID	110
#define INI_FILE_LINE_LENGTH_EXCEEDED	111
#define VIRTUAL_METHOD_NOT_IMPLEMENTED	112
#define INVALID_PARAMETER_VALUE	113
#define STATIC_OBJECT_EVENTFUNC_NOTIMPL	114
#define METHOD_NOT_OVERLOADED	115
#define CONFIG_FILE_NOT_FOUND	116
#define CONFIG_NO_CONFIG_OBJECT	117
#define CONFIG_AMBIGUOUS_OBJECT	118
#define CONFIG_INVALID_TYPEDEF	119
#define CONFIG_AMBIGUOUS_PROPERTY	120
#define CONFIG_NO_DEFFILE_SPEC	121
#define CONFIG_NO_CONFIGOBJECT_SPEC	122
#define CONFIG_NO_PROPERTYDEF	123
#define CONFIG_NO_TYPEDEF	124
#define CONFIG_INVALID_BASETYPE	125
#define CONFIG_PROPERTY_ALREADY_RESOLVED	126
#define CONFIG_UNABLE_TO_RESOLVE_OBJECT	127
#define CONFIG_UNKNOWN_TYPEDEF	128
#define CONFIG_AMBIGUOUS_BASETYPE	129
#define CONFIG_AMBIGUOUS_RANGETYPE	130
#define CONFIG_CANNOT_SET_RANGE	131
#define CONFIG_UNDEFINED_BASETYPE	132
#define CONFIG_INVALID_TYPESPEC	133
#define CONFIG_NO_TYPESPEC	134
#define CONFIG_AMBIGUOUS_TYPEDEF	135
#define CONFIG_OBJECT_TYPE_MISMATCH	136
#define CONFIG_NO_SCALAR	137
#define CONFIG_INVALID_TYPE	138
#define CONFIG_NO_VALUE	139
#define CONFIG_NO_VECTOR	140
#define CONFIG_INVALID_VALUE	141
#define CONFIG_INVALID_INDEX	142
#define CONFIG_NOT_NUMERIC	143
#define CONFIG_INVALID_BOOL_SPEC	144
#define CONFIG_NO_PROPVAL	145
#define VALUE_NO_TYPEDEF	146
#define VALUE_INVALID_TYPE	147
#define ORB_BROKER_INACTIVE	148
#define ORB_BROKER_ACTIVE	149
#define ORB_START_FAILURE	150
#define ORB_ORB_INACTIVE	151
#define ORB_BOA_INACTIVE	152
#define SOCKET_SETSOCKOPT	153
#define SOCKET_VERSION	154
#define SOCKET_CREATE	155
#define SOCKET_RECVFROM	156
#define SOCKET_SENDTO	157
#define SOCKET_BUF_TOO_SMALL	158
#define SOCKET_STARTUP	159
#define SOCKET_BIND	160
#define PROXY_UNHANDLED_EXCEPTION	161
#define PROXY_NO_INTERFACE	162
#define PROXY_NO_OBJECT_INTERFACE	163
#define PROXY_NO_OBJECT	164
#define PROXY_CORBA_SYSTEM	165
#define PROXY_TYPE_MISMATCH	166
#define CORBA_UNHANDLED_EXCEPTION	167
#define CONSOLE_INVALID_DIRECTION	168
#define FACTORY_INVALID_VALUE	169
#define CHANNEL_WRAPPER_START_PROCESS	170
#define CHANNEL_WRAPPER_NO_CONTACT	171
#define PROXY_RECEIVER_UNKNOWN_POT	172
#define PROXY_RECEIVER_FAILED_TO_CONSTRUCT	173
#define OBJECT_PARSER_FAILURE	174
#define OBJECT_PARSER_CONSTRUCT_HEADER	175
#define OBJECT_PARSER_INVALID_OBJECTTYPE	176
#define OBJECT_PARSER_INVALID_SUBTYPE1	177
#define OBJECT_PARSER_INVALID_SUBTYPE2	178
#define EVENT_CHANNEL_NO_CHANNEL	179
#define CYCLEBUF_COLUMN_INDEX_INVALID	180
#define CYCLEBUF_COLUMN_NAME_INVALID	181
#define CYCLEBUF_ROW_INVALID	182
#define CYCLEBUF_ROW_COUNT	183
#define SOCKET_CHANNEL_NO_PORT_NAME	184
#define SOCKET_CHANNEL_NO_SERIAL_PORT	185
#define SOCKET_CHANNEL_INVALID_SERIAL_PORT	186
#define SOCKET_CHANNEL_NO_IP_ADDRESS	187
#define SOCKET_CHANNEL_BAD_IP_ADDRESS	188
#define STDSER_NO_PORT_NAME	189
#define STDSER_PORT_NAME_SIZE	190
#define STDSER_INVALID_HANDLE	191
#define STDSER_SET_COMM_STATE	192
#define STDSER_GET_COMM_STATE	193
#define STDSER_CREATE_FILE	194
#define STDSER_SET_COMM_TIMEOUTS	195
#define STDSER_GET_COMM_TIMEOUTS	196
#define STDSER_CLEAR_COMM_ERROR	197
#define STDSER_WRITE_FILE	198
#define STDSER_READ_FILE	199
#define DIGIO_INVALID_CARDTYPE	200
#define PA150_OPEN	201
#define PA150_READ1_INPUT	202
#define PA150_READ16_INPUT	203
#define PA150_SET1_OUTPUT_ON	204
#define PA150_SET1_OUTPUT_OFF	205
#define ADDI_UNIVERSAL_OPEN	206
#define ADDI_UNIVERSAL_READ1_INPUT	207
#define ADDI_UNIVERSAL_READ_INPUTS	208
#define ADDI_UNIVERSAL_SET1_OUTPUT_ON	209
#define ADDI_UNIVERSAL_SET1_OUTPUT_OFF	210
#define ADDI_UNIVERSAL_GET_INPUT_NO	211
#define ADDI_UNIVERSAL_GET_OUTPUT_NO	212
#define ADDI_UNIVERSAL_SET_OUTPUT_MEM	213
#define ADDI_UNIVERSAL_INVALID_NOOFINPUTS	214
#define DRIVER_NOT_CONNECTED	215
#define DRIVER_READ_SUBTRACTING_SHOTCOUNT	216
#define DRIVER_READ_ADDING_SHOTCOUNT	217
#define DRIVER_RCV_BUF_TOO_SMALL	218
#define DRIVER_NO_BUFFER	219
#define DRIVER_INVALID_PHYS_SPEC	220
#define VIRTDATA_ITEM_EXISTS	221
#define VIRTDATA_ITEM_NOT_FOUND	222
#define FM_MACHINE_ERROR	223
#define FM_ABORT	224
#define FM_CR_LF_ERROR	225
#define FM_CHECKSUM_ERROR	226
#define FM_MISSING_ETX	227
#define FM_RCV_CHAR_TIMEOUT	228
#define FM_CONTACT_RETRIES	229
#define FM_BLK_RETRIES_1	230
#define FM_CHAR_TIMEOUT_5	231
#define FM_UNDEF_CHAR_5	232
#define FM_BLK_RETRIES_2	233
#define FM_CHAR_TIMEOUT_10	234
#define FM_UNDEF_CHAR_10	235
#define FM_BLK_RETRIES_3	236
#define FM_UNDEF_CHAR_13	237
#define FM_CHAR_TIMEOUT_15	238
#define FM_UNDEF_CHAR_15	239
#define FM_BLK_RETRIES_4	240
#define FM_RCV_COMM_ABORTED	241
#define FM_ECHO	242
#define FM_UNKNOWN_COMMAND	243
#define FM_MS_SYNTAX	244
#define FM_TB_SYNTAX	245
#define FM_CB_SYNTAX	246
#define FM_EB_SYNTAX	247
#define FM_MS_ERROR	248
#define FM_TB_ERROR	249
#define FM_CB_ERROR	250
#define FM_EB_ERROR	251
#define VARIABLE_INVALID_INDEX	252
#define VARIABLE_INVALID_DIM	253
#define VARIABLE_NOT_FOUND	254
#define VARIABLE_NO_MAPPING	255
#define VARIABLE_NO_MAP_ITEM	256
#define VARIABLE_NO_DEVICE	257
#define VARIABLE_READ_ONLY	258
#define VARIABLE_NULL_MAPPING	259
#define FUNC_INVALID_PARAMPOS	260
#define PARSE_FUNCREF_NOT_DECLARED	261
#define PARSE_FUNCREF_INVALID_TYPE	262
#define PARSE_FUNCREF_TOO_MUCH_PARAMS	263
#define PARSE_FUNCREF_TOO_FEW_PARAMS	264
#define PARSE_FUNCREF_INVALID_PARAMTYPE	265
#define PARSE_FUNCREF_NO_PARAMTYPE	266
#define PARSE_TYPES_NOT_COMPATIBLE	267
#define PARSE_FUNCREF_INVALID_CLASS	268
#define PARSE_BITPOS	269
#define PARSE_BITPOS_SPECIFICATION	270
#define PARSE_VARREF_NOT_DECLARED	271
#define PARSE_VARREF_INVALID_INDEX	272
#define PARSE_VARREF_TOO_MUCH_INDICES	273
#define PARSE_VARREF_TOO_FEW_INDICES	274
#define PARSE_VARREF_INVALID_TYPE	275
#define PARSE_VARREF_NO_INDEX	276
#define PARSE_SYMBOL_RESOLVE	277
#define PARSE_SYNTAX_ERRORS_IN_FILE	278
#define PARSE_SYNTAX_ERRORS_IN_STRING	279
#define VARREF_NO_VARIABLE	280
#define FUNCREF_FAILED_TO_RESOLVE	281
#define FUNCREF_FUNCTION_NOT_DECLARED	282
#define FUNCREF_FUNCTION_NOT_RESOLVED	283
#define FUNCREF_PARAMETER_TYPE_NOT_SUPPORTED	284
#define CELL_NO_DIGITALIO	285
#define CELL_NO_DRIVER	286
#define CELL_CYCLESPEC_DRIVER_UNKNOWN	287
#define CELL_NO_DISPATCHER	288
#define CELL_NO_FAST_CHANNEL	289
#define CELL_CREATE_DEVICE	290
#define CELL_CREATE_PROGRAM	291
#define CELL_UNKNOWN_PROGRAM	292
#define PROGRAM_UNKNOWN_IOSIGNAL	293
#define PROGRAMMABLE_COMMAND_UNKNOWN	294
#define PROGRAMMABLE_SYNTAX_ERROR	295
#define PROGRAMMABLE_UNKNOWN_DATA_TYPE	296
#define PROGRAMMABLE_INVALID_FORMAT_SPEC	297
#define PROGRAMMABLE_INVALID_CONSTRAINT	298
#define PROGRAMMABLE_CONSTRAINT	299
#define MAPPING_INVALID_ADDRESS	300
#define MAPPING_INVALID_MAPPING_TYPE	301
#define MAPPING_INVALID_MAPITEM_POS	302
#define DATA_OBJECT_VARIABLE_NOT_CREATED	303
#define MODBUS_HREGS_NO_RESPONSE	304
#define MODBUS_HREGS_INVALID_NODE	305
#define MODBUS_HREGS_INVALID_FUNCTION	306
#define MODBUS_HREGS_INVALID_BYTE_COUNT	307
#define MODBUS_HREGS_RESPONSE_TOO_SHORT	308
#define MODBUS_HREGS_RESPONSE_CRC_ERROR	309
#define MODBUS_HREGS_BUFFER_TOO_SHORT	310
#define CARRIER_UNHANDLED_EXCEPTION	311
#define CARRIER_DEVICE_ACCESS	312
#define STRING_CACHE_TOO_MUCH_ELEMENTS	313
#define DEVICE_INVALID_MEMORY_ORGANIZATION	314
#define DEVICE_INVALID_DATATYPE	315
#define DEVICE_INVALID_GRANULARITY	316
#define DEVICE_NO_MEMORY_INFO	317
#define DEVICE_NOT_CONNECTED	318
#define GRABBER_OPEN_DEVICE	319
#define GRABBER_INIT_BOARD	320
#define GRABBER_BOARD_INFO	321
#define GRABBER_SENSOR_INFO	322
#define GRABBER_SET_DISPLAY_MODE	323
#define GRABBER_SET_COLOR_MODE	324
#define GRABBER_SET_IMAGE_SIZE	325
#define GRABBER_SET_CAPTURE_MODE	326
#define GRABBER_CAPTURE_VIDEO	327
#define GRABBER_ALLOC_IMAGE_MEM	328
#define GRABBER_SET_IMAGE_MEM	329
#define GRABBER_FREE_IMAGE_MEM	330
#define GRABBER_COPY_IMAGE_MEM	331
#define GRABBER_SET_VIDEO_INPUT	332
#define GRABBER_INVALID_CHANNEL	333
#define TRAEGER_S7_OPEN	334
#define TRAEGER_S7_READ	335
#define TRAEGER_S7_WRITE	336
#define I60_READ	337
#define I60_WRITE	338
#define SHARED_LIBRARY_LOAD	339
#define SHARED_FUNCTION_LOAD	340
#define STEPPER_READ_ONLY	341
#define STEPPER_MIN_VALUE	342
#define STEPPER_MAX_VALUE	343
#define STEPPER_DLL_LOAD	344
#define STEPPER_TARGET_TIMEOUT	345
#define STEPPER_LOAD_PROC	346
#define STEPPER_WRITE_ONLY	347
#define STEPPER_SETREG	348
#define STEPPER_GETREG	349
#define IMAGE_BUFFER_TOO_SMALL	350
#define FAILED_TO_WRITE_DEVICE_BLOB_DATA	351
#define NO_BUFFER_FOR_BLOB_DATA	352
#define NOT_CONNECTED	353
#define NO_SUCH_JOB	354
#define OBJECT_SERIALIZE_BUF_TOO_SMALL	355
#define OBJECT_SERIALIZE_STRING_BUF_TOO_SMALL	356
#define DOWNLOAD_MESSAGE	357
#define DOWNLOAD_NO_CONNECTION	358
#define DOWNLOAD_UNKNOWN_ERROR	359
#define ERR_MIN_VALUE 		360
#define ERR_MAX_VALUE 		361
#define CCS_SERVICE_CUSTOM_INIT  362
#define ERR_FUNCTION_CALL  363
#define INSUFFICIENT_CURVE_SPACE  364
#define METHOD_NOT_SUPPORTED  365
#define VARREF_DELETE_CACHED  366
#define PARSE_UNIT_NOT_DECLARED	367
#define GRABBER_SET_CONTRAST  368
#define GRABBER_SET_BRIGHTNESS  369
#define CLIENT_INTERFACE_NO_MORE_CONNECTIONS_AVAILABLE   370
#define CLIENT_INTERFACE_CONNECTION_TERMINATED  371
#define CCS_INIT_FUNCTION_FAILURE  372
#define GUI_INIT_FUNCTION_FAILURE  373
#define PARSE_VARREF_ALREADY_DECLARED  374
#define PARSE_PARSING_ABORTED  375
#define UPLOAD_MESSAGE	376
#define UPLOAD_NO_CONNECTION	377
#define UPLOAD_UNKNOWN_ERROR	378
#define FLAT_OBJECT_NO_SPACE  379
#define RING_BUFFER_NO_SPACE  380
#define CACHE_READ_UNCACHED   381
#define CELL_UNINITIALIZED    382
#define VARIABLE_SET_NULL_VALUE	383
#define BAD_ALLOC             384
#define BAD_NEW               385
#define GRABBER_SET_VIDEO_MODE	386
#define GRABBER_INVALID_VIDEO_MODE  387
#define ORB_POA_INACTIVE            388
#define EM63_DIR_NOT_EXIST          389

// new constant definitions for system texts: place here

#endif // _SystemText_h_
